function [in, context] = routeA_prepare_electrical_boundary_input( ...
    model, modelDir, caseCfg, studyCfg)
% Assemble one Route A electrical-boundary case into SimulationInput.
%
% The caller owns the case definition. This function owns initial-state
% selection, logical-to-model time translation, model variables, solver
% settings, air/cEGR controls, and mode-specific electrical inputs.

if nargin < 4 || isempty(studyCfg)
    studyCfg = struct();
end
validateattributes(model, {'char', 'string'}, {'scalartext'});
if ~isstruct(caseCfg) || numel(caseCfg) ~= 1
    error('RouteA:ElectricalBoundaryCase', ...
        'caseCfg must be a scalar struct.');
end
study = studyDefaults(studyCfg, modelDir);
boundary = getBoundary(caseCfg);
type = string(boundary.type);
if ~any(type == ["Current", "Power", "Voltage"])
    error('RouteA:ElectricalBoundaryType', ...
        'Electrical boundary type must be Current, Power, or Voltage.');
end

in = Simulink.SimulationInput(char(model));
[in, initialMetadata] = routeA_attach_platform_default_initial_state( ...
    in, char(model), modelDir, study.initialStateFile, type);
paths = routeA_block_paths(char(model));
sourceValue = sourceCommandValue(initialMetadata, type);
startupValue = startupCommandValue(sourceValue, type, study);
boundaryOptions = struct( ...
    'duration_s', study.researchDuration_s, ...
    'commandStartOffset_s', study.commandStartOffset_s, ...
    'startupRampDuration_s', study.startupRampDuration_s, ...
    'initialValue', startupValue, ...
    'label', "electrical_" + lower(type));
boundaryProfile = routeA_normalize_electrical_profile( ...
    boundary.profile, type, boundaryOptions);

cegrSpec = getCegrProfile(caseCfg);
cegrOptions = struct( ...
    'duration_s', study.researchDuration_s, ...
    'commandStartOffset_s', study.commandStartOffset_s, ...
    'initialValue', 0, ...
    'label', "cegr_ratio");
cegrProfile = routeA_normalize_electrical_profile( ...
    cegrSpec, "CEGR", cegrOptions);

researchStart = initialMetadata.snapshotTimeS;
modelStop = researchStart + study.researchDuration_s;
tailWindow = researchStart + study.tailLogicalWindow_s;
boundaryModelTime = researchStart + boundaryProfile.time_s;
cegrModelTime = researchStart + cegrProfile.time_s;

in = in.setBlockParameter(paths.electricalLoad, 'input_type', char(type));
in = in.setModelParameter( ...
    'StopTime', sprintf('%.16g', modelStop), ...
    'Solver', char(study.solver), ...
    'SolverType', 'Variable-step', ...
    'RelTol', sprintf('%.16g', study.relativeTolerance), ...
    'AbsTol', sprintf('%.16g', study.absoluteTolerance), ...
    'MaxStep', sprintf('%.16g', study.studyMaxStep_s), ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SimscapeLogType', 'all', ...
    'SaveFinalState', 'on', ...
    'FinalStateName', 'routeA_research_operating_point', ...
    'SaveOperatingPoint', 'on');

air = getAirConfig(caseCfg);
in = in.setVariable('routeA_air_control_mode_id', air.modeId, ...
    'Workspace', char(model));
if air.modeId == 1
    in = in.setVariable('routeA_target_mdot_comp_inlet', air.targetMdot_kg_s, ...
        'Workspace', char(model));
elseif air.modeId == 2
    in = in.setVariable('routeA_target_oer', air.targetOer, ...
        'Workspace', char(model));
else
    in = in.setVariable('routeA_compressor_cmd_direct', ...
        air.directCommand, 'Workspace', char(model));
end
in = in.setVariable('routeA_egr_control_mode_id', 1, ...
    'Workspace', char(model));
in = in.setVariable('routeA_cegr_enabled', true, 'Workspace', char(model));
in = in.setVariable('routeA_cegr_valve_mode_id', 1, ...
    'Workspace', char(model));
in = in.setVariable('routeA_egr_target_input_mode_id', 1, ...
    'Workspace', char(model));
in = in.setVariable('routeA_target_egr_ratio_comp_in', cegrProfile.value(1), ...
    'Workspace', char(model));
in = in.setVariable('routeA_target_egr_ratio_comp_in_profile', ...
    [cegrModelTime, cegrProfile.value], 'Workspace', char(model));

switch type
    case "Current"
        in = in.setVariable('drive_cycle_time', boundaryModelTime, ...
            'Workspace', char(model));
        in = in.setVariable('drive_cycle_current', boundaryProfile.value, ...
            'Workspace', char(model));
    case "Power"
        in = in.setVariable('drive_cycle_time', boundaryModelTime, ...
            'Workspace', char(model));
        in = in.setVariable('drive_cycle_power', boundaryProfile.value, ...
            'Workspace', char(model));
    case "Voltage"
        in = in.setVariable('drive_cycle_time', boundaryModelTime, ...
            'Workspace', char(model));
        in = in.setVariable('drive_cycle_voltage', boundaryProfile.value, ...
            'Workspace', char(model));
        controller = getControllerConfig(caseCfg);
        in = in.setVariable('routeA_voltage_pi_Kp', controller.Kp_A_V, ...
            'Workspace', char(model));
        in = in.setVariable('routeA_voltage_pi_Ki', controller.Ki_A_V_s, ...
            'Workspace', char(model));
        in = in.setVariable('routeA_voltage_current_min_A', ...
            controller.currentMin_A, 'Workspace', char(model));
        in = in.setVariable('routeA_voltage_current_max_A', ...
            controller.currentMax_A, 'Workspace', char(model));
end

thermal = getOptionalStruct(caseCfg, 'thermal');
[in, cathode] = applyCathodeControls(in, char(model), caseCfg);
[in, anode] = applyAnodeControls(in, char(model), caseCfg);
[in, thermal] = applyThermalControls(in, char(model), thermal);

mw = get_param(char(model), 'ModelWorkspace');
context = struct();
context.model = string(model);
context.modelDir = string(modelDir);
context.caseCfg = caseCfg;
context.boundaryType = type;
context.boundaryProfile = boundaryProfile;
context.cegrProfile = cegrProfile;
context.boundaryModelTime_s = boundaryModelTime;
context.cegrModelTime_s = cegrModelTime;
context.initialStateMetadata = initialMetadata;
context.initialStateFile = string(study.initialStateFile);
context.researchStartTime_s = researchStart;
context.researchDuration_s = study.researchDuration_s;
context.modelStopTime_s = modelStop;
context.tailLogicalWindow_s = study.tailLogicalWindow_s;
context.tailWindow_s = tailWindow;
context.calculationType = study.calculationType;
context.logicalStartTime_s = 0;
context.modelTimeOrigin_s = researchStart;
context.steadyRelativeVariationLimit = ...
    study.steadyRelativeVariationLimit;
context.steadyWindowDuration_s = study.steadyWindowDuration_s;
context.solver = struct('name', study.solver, ...
    'relativeTolerance', study.relativeTolerance, ...
    'absoluteTolerance', study.absoluteTolerance, ...
    'maxStep_s', study.studyMaxStep_s);
context.studyMaxStep_s = study.studyMaxStep_s;
context.commandStartOffset_s = study.commandStartOffset_s;
context.startupRampDuration_s = study.startupRampDuration_s;
context.startupValue = startupValue;
context.air = air;
context.cathode = cathode;
context.anode = anode;
context.thermal = thermal;
context.stackCells = mw.getVariable('stack_num_cells');
context.cegrValveMaxArea_m2 = mw.getVariable('cegr_valve_max_area');
context.compressorRpmLookupBounds = compressorBounds(mw);
context.faradayConstant_C_mol = 96485.33212;
context.molarMass_kg_mol = [0.0280134, 0.0319988, 0.00201588, 0.01801528];
context.gas = struct( ...
    'n2Index', 1, 'o2Index', 2, 'h2oIndex', 4, ...
    'absoluteResidualTolerance_kg_s', 5e-4, ...
    'relativeResidualTolerance', 0.05);
context.controller = getControllerConfig(caseCfg);
end

function study = studyDefaults(user, modelDir)
study = struct( ...
    'initialStateFile', fullfile(modelDir, ...
        'RouteA_platform_default_initial_state.mat'), ...
    'calculationType', "steady", ...
    'researchDuration_s', 600, ...
    'tailLogicalWindow_s', [540, 600], ...
    'steadyWindowDuration_s', 60, ...
    'steadyRelativeVariationLimit', 0.005, ...
    'solver', "VariableStepAuto", ...
    'relativeTolerance', 1e-3, ...
    'absoluteTolerance', 1e-3, ...
    'studyMaxStep_s', 5, ...
    'commandStartOffset_s', 0.5);
study.startupRampDuration_s = 60;
study.voltageNoLoadMargin_V = 20;
hasExplicitMaxStep = isfield(user, 'studyMaxStep_s');
names = fieldnames(user);
for idx = 1:numel(names)
    if ~isfield(study, names{idx})
        error('RouteA:ElectricalBoundaryStudyField', ...
            'Unsupported study configuration field: %s.', names{idx});
    end
    study.(names{idx}) = user.(names{idx});
end
validateattributes(study.researchDuration_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
study.calculationType = lower(string(study.calculationType));
if ~isscalar(study.calculationType) || ...
        ~any(study.calculationType == ["steady", "transient"])
    error('RouteA:ElectricalBoundaryCalculationType', ...
        'calculationType must be steady or transient.');
end
if study.calculationType == "transient" && ~hasExplicitMaxStep
    study.studyMaxStep_s = 0.1;
end
study.solver = string(study.solver);
if ~isscalar(study.solver) || study.solver ~= "VariableStepAuto"
    error('RouteA:ElectricalBoundarySolver', ...
        'Route A currently supports the VariableStepAuto solver only.');
end
validateattributes(study.relativeTolerance, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.absoluteTolerance, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.tailLogicalWindow_s, {'numeric'}, ...
    {'vector', 'numel', 2, 'nonnegative', 'finite'});
study.tailLogicalWindow_s = study.tailLogicalWindow_s(:).';
if study.tailLogicalWindow_s(2) > study.researchDuration_s || ...
        study.tailLogicalWindow_s(2) <= study.tailLogicalWindow_s(1)
    error('RouteA:ElectricalBoundaryTailWindow', ...
        'The logical tail window is outside the research duration.');
end
validateattributes(study.studyMaxStep_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.steadyWindowDuration_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.steadyRelativeVariationLimit, {'numeric'}, ...
    {'scalar', 'positive', 'finite', '<=', 1});
if study.calculationType == "steady" && ...
        diff(study.tailLogicalWindow_s) + eps < study.steadyWindowDuration_s
    error('RouteA:ElectricalBoundarySteadyWindow', ...
        'The steady tail window must cover steadyWindowDuration_s.');
end
validateattributes(study.commandStartOffset_s, {'numeric'}, ...
    {'scalar', 'nonnegative', 'finite'});
validateattributes(study.startupRampDuration_s, {'numeric'}, ...
    {'scalar', 'nonnegative', 'finite'});
validateattributes(study.voltageNoLoadMargin_V, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
if study.commandStartOffset_s + study.startupRampDuration_s >= ...
        study.researchDuration_s
    error('RouteA:ElectricalBoundaryStartupRamp', ...
        'The startup ramp must finish before the study ends.');
end
end

function boundary = getBoundary(caseCfg)
if ~isfield(caseCfg, 'boundary') || ~isstruct(caseCfg.boundary)
    error('RouteA:ElectricalBoundaryMissing', ...
        'Each case must define boundary.type and boundary.profile.');
end
boundary = caseCfg.boundary;
if ~isfield(boundary, 'type')
    error('RouteA:ElectricalBoundaryMissingType', ...
        'Each boundary must define type.');
end
if ~isfield(boundary, 'profile')
    if isfield(boundary, 'value')
        boundary.profile = boundary.value;
    else
        error('RouteA:ElectricalBoundaryMissingProfile', ...
            'Each boundary must define profile.');
    end
end
end

function value = getCegrProfile(caseCfg)
if ~isfield(caseCfg, 'cegr') || isempty(caseCfg.cegr)
    value = 0;
    return;
end
cegr = caseCfg.cegr;
if isnumeric(cegr)
    value = cegr;
elseif isstruct(cegr) && isfield(cegr, 'profile')
    value = cegr.profile;
elseif isstruct(cegr) && isfield(cegr, 'targetRatio')
    value = cegr.targetRatio;
else
    value = cegr;
end
end

function value = sourceCommandValue(metadata, type)
switch type
    case "Current"
        field = 'targetCurrentA';
    case "Power"
        field = 'targetPower_kW';
    case "Voltage"
        field = 'targetVoltage_V';
end
if ~isfield(metadata, field)
    error('RouteA:ElectricalBoundaryInitialMetadata', ...
        'Initial-state metadata does not define %s.', field);
end
value = metadata.(field);
validateattributes(value, {'numeric'}, {'scalar', 'real', 'finite'});
end

function value = startupCommandValue(sourceValue, type, study)
switch type
    case {"Current", "Power"}
        value = 0;
    case "Voltage"
        % A voltage reference above the matched hot-state voltage requests
        % the controller's zero-load side before the reference ramps down.
        value = sourceValue + study.voltageNoLoadMargin_V;
end
validateattributes(value, {'numeric'}, {'scalar', 'real', 'finite'});
end

function air = getAirConfig(caseCfg)
air = struct('modeId', 2, 'targetOer', 3, 'targetMdot_kg_s', NaN, ...
    'directCommand', NaN);
air = mergeKnownFields(air, getOptionalStruct(caseCfg, 'air'), ...
    'RouteA:AirControlField');
validateattributes(air.modeId, {'numeric'}, {'scalar', 'integer', '>=', 1, '<=', 3});
if air.modeId == 1
    validateattributes(air.targetMdot_kg_s, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});
elseif air.modeId == 2
    validateattributes(air.targetOer, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});
else
    validateattributes(air.directCommand, {'numeric'}, ...
        {'scalar', '>=', 0, '<=', 1, 'finite'});
end
end

function [in, cathode] = applyCathodeControls(in, model, caseCfg)
mw = get_param(model, 'ModelWorkspace');
cathode = struct( ...
    'sourcePressure_MPa_abs', mw.getVariable('env_p'), ...
    'sourceTemperature_C', mw.getVariable('env_T'), ...
    'freshAirO2MoleFraction', mw.getVariable('env_yO2'), ...
    'freshAirWaterMoleFraction', mw.getVariable('env_yH20'), ...
    'outletPressure_MPa_abs', ...
        mw.getVariable('routeA_target_p_ca_out_MPa'), ...
    'humidifierRelativeHumidity', ...
        mw.getVariable('routeA_cathode_rh_setpoint'), ...
    'humidifierEnabled', ...
        mw.getVariable('routeA_cathode_humidifier_gain'));
cathode = mergeKnownFields(cathode, ...
    getOptionalStruct(caseCfg, 'cathode'), ...
    'RouteA:CathodeControlField');
validateattributes(cathode.sourcePressure_MPa_abs, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(cathode.sourceTemperature_C, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(cathode.freshAirO2MoleFraction, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
validateattributes(cathode.freshAirWaterMoleFraction, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
if cathode.freshAirO2MoleFraction + ...
        cathode.freshAirWaterMoleFraction > 1
    error('RouteA:CathodeSourceComposition', ...
        'Cathode O2 and H2O mole fractions must sum to no more than one.');
end
validateattributes(cathode.outletPressure_MPa_abs, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(cathode.humidifierRelativeHumidity, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
validateattributes(cathode.humidifierEnabled, {'numeric', 'logical'}, ...
    {'scalar', 'binary'});
in = in.setVariable('env_p', cathode.sourcePressure_MPa_abs, ...
    'Workspace', model);
in = in.setVariable('env_T', cathode.sourceTemperature_C, ...
    'Workspace', model);
in = in.setVariable('env_yO2', cathode.freshAirO2MoleFraction, ...
    'Workspace', model);
in = in.setVariable('env_yH20', cathode.freshAirWaterMoleFraction, ...
    'Workspace', model);
in = in.setVariable('routeA_target_p_ca_out_MPa', ...
    cathode.outletPressure_MPa_abs, 'Workspace', model);
in = in.setVariable('routeA_cathode_rh_setpoint', ...
    cathode.humidifierRelativeHumidity, 'Workspace', model);
in = in.setVariable('routeA_cathode_humidifier_gain', ...
    cathode.humidifierEnabled, 'Workspace', model);
end

function [in, anode] = applyAnodeControls(in, model, caseCfg)
mw = get_param(model, 'ModelWorkspace');
anode = struct( ...
    'tankPressure_MPa_abs', mw.getVariable('tank_p'), ...
    'sourceTemperature_C', mw.getVariable('tank_T'), ...
    'hydrogenMoleFraction', mw.getVariable('tank_yH2'), ...
    'inletPressure_MPa_abs', ...
        mw.getVariable('routeA_anode_inlet_pressure_MPa_abs'), ...
    'humidifierRelativeHumidity', ...
        mw.getVariable('routeA_anode_rh_setpoint'), ...
    'recirculationBaseCommand', ...
        mw.getVariable('routeA_anode_recirculation_base_command'), ...
    'recirculationCurrentGain_A_inv', ...
        mw.getVariable('routeA_anode_recirculation_current_gain_A_inv'), ...
    'purgeEnabled', mw.getVariable('routeA_anode_purge_enable'), ...
    'purgeOnN2MoleFraction', ...
        mw.getVariable('routeA_anode_purge_on_n2_mole_fraction'), ...
    'purgeOffN2MoleFraction', ...
        mw.getVariable('routeA_anode_purge_off_n2_mole_fraction'));
anode = mergeKnownFields(anode, getOptionalStruct(caseCfg, 'anode'), ...
    'RouteA:AnodeControlField');
validateattributes(anode.tankPressure_MPa_abs, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(anode.sourceTemperature_C, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(anode.hydrogenMoleFraction, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
validateattributes(anode.inletPressure_MPa_abs, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
if anode.tankPressure_MPa_abs <= anode.inletPressure_MPa_abs
    error('RouteA:AnodePressureOrder', ...
        'tankPressure_MPa_abs must exceed inletPressure_MPa_abs.');
end
validateattributes(anode.humidifierRelativeHumidity, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
validateattributes(anode.recirculationBaseCommand, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
validateattributes(anode.recirculationCurrentGain_A_inv, {'numeric'}, ...
    {'scalar', 'nonnegative', 'finite'});
validateattributes(anode.purgeEnabled, {'numeric', 'logical'}, ...
    {'scalar', 'binary'});
validateattributes(anode.purgeOnN2MoleFraction, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
validateattributes(anode.purgeOffN2MoleFraction, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
if anode.purgeOnN2MoleFraction <= anode.purgeOffN2MoleFraction
    error('RouteA:AnodePurgeThresholdOrder', ...
        'purgeOnN2MoleFraction must exceed purgeOffN2MoleFraction.');
end
in = in.setVariable('tank_p', anode.tankPressure_MPa_abs, ...
    'Workspace', model);
in = in.setVariable('tank_T', anode.sourceTemperature_C, ...
    'Workspace', model);
in = in.setVariable('tank_yH2', anode.hydrogenMoleFraction, ...
    'Workspace', model);
in = in.setVariable('routeA_anode_inlet_pressure_MPa_abs', ...
    anode.inletPressure_MPa_abs, 'Workspace', model);
in = in.setVariable('routeA_anode_rh_setpoint', ...
    anode.humidifierRelativeHumidity, 'Workspace', model);
in = in.setVariable('routeA_anode_recirculation_base_command', ...
    anode.recirculationBaseCommand, 'Workspace', model);
in = in.setVariable('routeA_anode_recirculation_current_gain_A_inv', ...
    anode.recirculationCurrentGain_A_inv, 'Workspace', model);
in = in.setVariable('routeA_anode_purge_enable', ...
    anode.purgeEnabled, 'Workspace', model);
in = in.setVariable('routeA_anode_purge_on_n2_mole_fraction', ...
    anode.purgeOnN2MoleFraction, 'Workspace', model);
in = in.setVariable('routeA_anode_purge_off_n2_mole_fraction', ...
    anode.purgeOffN2MoleFraction, 'Workspace', model);
end

function [in, thermal] = applyThermalControls(in, model, user)
mw = get_param(model, 'ModelWorkspace');
thermal = struct('stackTemperatureSet_C', ...
    mw.getVariable('routeA_stack_temperature_set_C'));
thermal = mergeKnownFields(thermal, user, 'RouteA:ThermalControlField');
validateattributes(thermal.stackTemperatureSet_C, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
in = in.setVariable('routeA_stack_temperature_set_C', ...
    thermal.stackTemperatureSet_C, 'Workspace', model);
end

function result = mergeKnownFields(defaults, user, errorId)
result = defaults;
names = fieldnames(user);
for idx = 1:numel(names)
    if ~isfield(result, names{idx})
        error(errorId, 'Unsupported control field: %s.', names{idx});
    end
    result.(names{idx}) = user.(names{idx});
end
end

function controller = getControllerConfig(caseCfg)
controller = struct('Kp_A_V', 1, 'Ki_A_V_s', 0.05, ...
    'currentMin_A', 0, 'currentMax_A', 392);
controller = mergeKnownFields(controller, ...
    getOptionalStruct(caseCfg, 'controller'), ...
    'RouteA:VoltageControlField');
validateattributes(controller.Kp_A_V, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(controller.Ki_A_V_s, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(controller.currentMin_A, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(controller.currentMax_A, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', controller.currentMin_A});
end

function value = getOptionalStruct(parent, fieldName)
if ~isfield(parent, fieldName) || isempty(parent.(fieldName))
    value = struct();
elseif isstruct(parent.(fieldName)) && isscalar(parent.(fieldName))
    value = parent.(fieldName);
else
    error('RouteA:ElectricalBoundaryControlType', ...
        '%s must be a scalar struct.', fieldName);
end
end

function bounds = compressorBounds(mw)
table = mw.getVariable('comp_rpm_TLU');
bounds = [min(table), max(table)];
end
