% Route A Phase 1 parameter matching and interface-contract audit.
%
% This runner is read-only with respect to the committed model and its
% platform_default parameters. It reuses the nine-case study, builds an
% engineering-order demand ledger, and records observability gaps.

scriptDir = fileparts(mfilename('fullpath'));
modelDir = fullfile(scriptDir, '..', '..', '01_模型', 'RouteA_GasMixture_Derived');
model = 'PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01';
modelFile = fullfile(modelDir, [model '.slx']);
oldDir = pwd;
addpath(scriptDir);
addpath(modelDir);
cd(modelDir);
cleanup = onCleanup(@() restoreModelAndFolder(oldDir, model, modelFile));

auditCfg = auditConfig(model, modelFile);
verifyPlatformDefault(auditCfg);

study = loadOrRunFullcaseStudy(model);

reactionLedger = buildReactionLedger(auditCfg);
coolingLedger = buildCoolingLedger(reactionLedger, auditCfg);
parameterRegistry = buildParameterRegistry(auditCfg);
interfaceContract = buildInterfaceContract(auditCfg);
passiveDiagnostics = runPassiveCegrDiagnostics(study, auditCfg, model, modelFile);
parameterRegistry = applyPassiveCegrDiagnosticStatus(parameterRegistry, ...
    passiveDiagnostics);
gaps = buildGapTable(passiveDiagnostics, auditCfg);

audit = struct();
audit.timestamp = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
audit.model = string(model);
audit.parameterLayer = string(auditCfg.parameterLayer);
audit.externalCaseEnabled = auditCfg.externalCaseEnabled;
audit.fullcaseStudy = study;
audit.reactionLedger = reactionLedger;
audit.coolingLedger = coolingLedger;
audit.passiveCegrDiagnostics = passiveDiagnostics;
audit.parameterRegistry = parameterRegistry;
audit.interfaceContract = interfaceContract;
audit.gaps = gaps;
audit.summary = buildSummary(study, reactionLedger, parameterRegistry, ...
    passiveDiagnostics, gaps);
audit.auditComplete = audit.summary.auditComplete;
audit.engineeringMatchReady = audit.summary.engineeringMatchReady;

assignin('base', 'routeA_phase1_audit', audit);
displayAuditSummary(audit);

function cfg = auditConfig(model, modelFile)
resetModelFromDisk(model, modelFile);
mw = get_param(model, 'ModelWorkspace');
if strcmp(mw.DataSource, 'MATLAB File')
    mw.reload;
end

cfg = struct();
cfg.model = string(model);
cfg.modelFile = string(modelFile);
cfg.modelWorkspace = mw;
cfg.parameterLayer = getWorkspaceValue(mw, 'routeA_parameter_layer', "");
cfg.externalCaseEnabled = logical(getWorkspaceValue(mw, ...
    'routeA_external_case_enabled', true));
cfg.stackAreaCm2 = getWorkspaceValue(mw, 'stack_area', NaN);
cfg.stackCells = getWorkspaceValue(mw, 'stack_num_cells', NaN);
cfg.envYO2 = getWorkspaceValue(mw, 'env_yO2', NaN);
cfg.envYH2O = getWorkspaceValue(mw, 'env_yH20', NaN);
cfg.cegrValveOpenMinArea = getWorkspaceValue(mw, 'cegr_valve_open_min_area', NaN);
cfg.cegrValveMaxArea = getWorkspaceValue(mw, 'cegr_valve_max_area', NaN);
cfg.compressorRpmTable = getWorkspaceValue(mw, 'comp_rpm_TLU', NaN);
cfg.compressorPressureRatioTable = getWorkspaceValue(mw, 'comp_p_ratio_TLU', NaN);
cfg.compressorCorrectedMdotTable = getWorkspaceValue(mw, ...
    'comp_mdot_corr_TLU', NaN);
cfg.faradayCmol = 96485.33212;
cfg.molarMassO2KgMol = 0.0319988;
cfg.molarMassN2KgMol = 0.0280134;
cfg.molarMassH2KgMol = 0.00201588;
cfg.molarMassH2OKgMol = 0.01801528;
cfg.hydrogenLhvJkg = 120e6;
cfg.thermoneutralVoltageV = 1.48;
cfg.coolantCpJkgK = 4180;
cfg.coolantDeltaTK = [5, 10, 15];
cfg.stopTimeS = 120;
cfg.tailSeconds = 10;
cfg.egrTargets = [0.10, 0.30];
cfg.loads = [ ...
    loadDefinition("low", 0.2, 0.78, 4); ...
    loadDefinition("nominal", 0.7, 0.65, 3); ...
    loadDefinition("high", 1.2, 0.58, 2)];

required = [cfg.stackAreaCm2, cfg.stackCells, cfg.envYO2, cfg.envYH2O, ...
    cfg.cegrValveOpenMinArea, cfg.cegrValveMaxArea];
if any(~isfinite(required)) || cfg.stackAreaCm2 <= 0 || cfg.stackCells <= 0
    error('RouteA:Phase1MissingParameters', ...
        'The model workspace does not expose the required platform parameters.');
end
end

function load = loadDefinition(id, currentDensity, referenceVoltage, targetOer)
load = struct('id', string(id), 'currentDensity_A_cm2', currentDensity, ...
    'referenceVoltage_V', referenceVoltage, 'targetOer', targetOer);
end

function verifyPlatformDefault(cfg)
if cfg.parameterLayer ~= "platform_default" || cfg.externalCaseEnabled
    error('RouteA:Phase1ParameterBoundary', ...
        ['Phase 1 requires platform_default with external_case disabled. ', ...
        'No historical bench or product data may enter this audit.']);
end
end

function study = loadOrRunFullcaseStudy(model)
hasExistingStudy = evalin('base', ...
    'exist(''routeA_fullcase_study'', ''var'') == 1');
if hasExistingStudy
    candidate = evalin('base', 'routeA_fullcase_study');
    if isReusableFullcaseStudy(candidate, model)
        study = candidate;
        fprintf(['Reusing the existing Route A nine-case study from the ', ...
            'base workspace.\n']);
        return;
    end
end

run_routeA_fullcase_study;
study = evalin('base', 'routeA_fullcase_study');
if ~isReusableFullcaseStudy(study, model)
    error('RouteA:Phase1InvalidFullcaseStudy', ...
        'The full-case runner did not return the required nine-case matrix.');
end
end

function reusable = isReusableFullcaseStudy(study, model)
requiredCaseIds = ["nominal_noCEGR", "nominal_withCEGR_010", ...
    "nominal_withCEGR_030", "low_noCEGR", "low_withCEGR_010", ...
    "low_withCEGR_030", "high_noCEGR", "high_withCEGR_010", ...
    "high_withCEGR_030"];
reusable = isstruct(study) && isfield(study, 'model') && ...
    isfield(study, 'stopTime_s') && isfield(study, 'results') && ...
    isequal(string(study.model), string(model)) && ...
    isequal(study.stopTime_s, 120) && numel(study.results) == numel(requiredCaseIds);
if ~reusable
    return;
end

actualCaseIds = string({study.results.caseId});
reusable = isequal(sort(actualCaseIds(:)), sort(requiredCaseIds(:)));
end

function ledger = buildReactionLedger(cfg)
airMolarMass = ambientAirMolarMass(cfg);
oxygenMassFraction = cfg.envYO2 * cfg.molarMassO2KgMol / airMolarMass;
if ~isfinite(oxygenMassFraction) || oxygenMassFraction <= 0
    error('RouteA:Phase1InvalidAmbientComposition', ...
        'Ambient oxygen mass fraction cannot be determined.');
end

nLoads = numel(cfg.loads);
loadId = strings(nLoads, 1);
currentDensity = zeros(nLoads, 1);
stackCurrent = zeros(nLoads, 1);
referenceVoltage = zeros(nLoads, 1);
targetOer = zeros(nLoads, 1);
targetPower = zeros(nLoads, 1);
h2Mdot = zeros(nLoads, 1);
o2Mdot = zeros(nLoads, 1);
waterMdot = zeros(nLoads, 1);
freshAirMdot = zeros(nLoads, 1);
compressorMdotNoCegr = zeros(nLoads, 1);
compressorMdot010 = zeros(nLoads, 1);
compressorMdot030 = zeros(nLoads, 1);
thermalPower = zeros(nLoads, 1);
electricalEfficiencyLhv = zeros(nLoads, 1);

for idx = 1:nLoads
    load = cfg.loads(idx);
    current = load.currentDensity_A_cm2 * cfg.stackAreaCm2;
    h2MolS = cfg.stackCells * current / (2 * cfg.faradayCmol);
    o2MolS = cfg.stackCells * current / (4 * cfg.faradayCmol);
    waterMolS = h2MolS;
    powerW = cfg.stackCells * current * load.referenceVoltage_V;
    freshAir = load.targetOer * o2MolS * cfg.molarMassO2KgMol / ...
        oxygenMassFraction;

    loadId(idx) = load.id;
    currentDensity(idx) = load.currentDensity_A_cm2;
    stackCurrent(idx) = current;
    referenceVoltage(idx) = load.referenceVoltage_V;
    targetOer(idx) = load.targetOer;
    targetPower(idx) = powerW / 1000;
    h2Mdot(idx) = h2MolS * cfg.molarMassH2KgMol;
    o2Mdot(idx) = o2MolS * cfg.molarMassO2KgMol;
    waterMdot(idx) = waterMolS * cfg.molarMassH2OKgMol;
    freshAirMdot(idx) = freshAir;
    compressorMdotNoCegr(idx) = freshAir;
    compressorMdot010(idx) = freshAir / (1 - 0.10);
    compressorMdot030(idx) = freshAir / (1 - 0.30);
    thermalPower(idx) = cfg.stackCells * current * ...
        (cfg.thermoneutralVoltageV - load.referenceVoltage_V) / 1000;
    electricalEfficiencyLhv(idx) = powerW / ...
        (h2Mdot(idx) * cfg.hydrogenLhvJkg);
end

ledger = table(loadId, currentDensity, stackCurrent, referenceVoltage, ...
    targetOer, targetPower, h2Mdot, o2Mdot, waterMdot, freshAirMdot, ...
    compressorMdotNoCegr, compressorMdot010, compressorMdot030, ...
    thermalPower, electricalEfficiencyLhv, ...
    'VariableNames', {'loadId', 'currentDensity_A_cm2', 'stackCurrent_A', ...
    'referenceVoltage_V', 'targetOer', 'targetPower_kW', 'h2Demand_kg_s', ...
    'o2Demand_kg_s', 'waterGeneration_kg_s', 'freshAirDemand_kg_s', ...
    'compressorInletScreen_noCEGR_kg_s', ...
    'compressorInletScreen_010_kg_s', ...
    'compressorInletScreen_030_kg_s', 'stackThermalDemand_kW', ...
    'electricalEfficiency_LHV'});
end

function molarMass = ambientAirMolarMass(cfg)
yN2 = 1 - cfg.envYO2 - cfg.envYH2O;
if yN2 < 0
    error('RouteA:Phase1InvalidAmbientComposition', ...
        'Ambient mole fractions sum to more than one.');
end
molarMass = cfg.envYO2 * cfg.molarMassO2KgMol + ...
    yN2 * cfg.molarMassN2KgMol + cfg.envYH2O * cfg.molarMassH2OKgMol;
end

function ledger = buildCoolingLedger(reactionLedger, cfg)
nRows = height(reactionLedger) * numel(cfg.coolantDeltaTK);
loadId = strings(nRows, 1);
deltaT = zeros(nRows, 1);
thermalDemand = zeros(nRows, 1);
coolantMdot = zeros(nRows, 1);
row = 0;
for iLoad = 1:height(reactionLedger)
    for iDeltaT = 1:numel(cfg.coolantDeltaTK)
        row = row + 1;
        loadId(row) = reactionLedger.loadId(iLoad);
        deltaT(row) = cfg.coolantDeltaTK(iDeltaT);
        thermalDemand(row) = reactionLedger.stackThermalDemand_kW(iLoad);
        coolantMdot(row) = thermalDemand(row) * 1000 / ...
            (cfg.coolantCpJkgK * deltaT(row));
    end
end
ledger = table(loadId, deltaT, thermalDemand, coolantMdot, ...
    'VariableNames', {'loadId', 'coolantDeltaT_K', ...
    'stackThermalDemand_kW', 'requiredCoolantMdot_kg_s'});
end

function diagnostics = runPassiveCegrDiagnostics(study, cfg, model, modelFile)
diagnostics = repmat(emptyPassiveDiagnostic(), numel(cfg.egrTargets), 1);
for idx = 1:numel(cfg.egrTargets)
    target = cfg.egrTargets(idx);
    caseId = "nominal_withCEGR_" + compose('%03d', round(target * 100));
    result = findCaseResult(study.results, caseId);
    diagnostics(idx) = runPassiveCase(result, cfg, model, modelFile);
end
end

function result = findCaseResult(results, caseId)
ids = string({results.caseId});
index = find(ids == caseId, 1);
if isempty(index)
    error('RouteA:Phase1MissingFullcaseResult', ...
        'The full-case study did not return %s.', caseId);
end
result = results(index);
end

function diagnostic = emptyPassiveDiagnostic()
diagnostic = struct('caseId', "", 'targetEgrRatio', NaN, ...
    'targetOer', NaN, 'targetPowerKW', NaN, 'fullcasePassed', false, ...
    'simCompleted', false, 'actualEgrRatio', NaN, 'areaFractionTailMin', NaN, ...
    'areaFractionTailMax', NaN, 'pressureUpstreamTailMPa', NaN, ...
    'pressureDownstreamTailMPa', NaN, 'pressureDeltaTailMPa', NaN, ...
    'finiteOk', false, 'areaWithinBounds', false, 'notSaturated', false, ...
    'forwardPressureDrop', false, 'passed', false, 'errorId', "", ...
    'errorMessage', "");
end

function diagnostic = runPassiveCase(caseResult, cfg, model, modelFile)
diagnostic = emptyPassiveDiagnostic();
diagnostic.caseId = string(caseResult.caseId);
diagnostic.targetEgrRatio = caseResult.targetEgrRatio;
diagnostic.targetOer = caseResult.targetOer;
diagnostic.targetPowerKW = caseResult.targetPowerKW;
diagnostic.fullcasePassed = caseResult.passed;

try
    resetModelFromDisk(model, modelFile);
    mw = get_param(model, 'ModelWorkspace');
    if strcmp(mw.DataSource, 'MATLAB File')
        mw.reload;
    end
    mw.assignin('routeA_cegr_enabled', true);
    mw.assignin('routeA_cegr_valve_mode_id', ...
        double(caseResult.targetEgrRatio > 0));
    set_param(model, 'SimulationCommand', 'update');

    paths = routeA_block_paths(model);
    markDiagnosticSignals(paths);
    in = Simulink.SimulationInput(model);
    in = in.setModelParameter('StopTime', sprintf('%.16g', cfg.stopTimeS), ...
        'SignalLogging', 'on', 'SignalLoggingName', 'logsout', ...
        'ReturnWorkspaceOutputs', 'on', 'SimscapeLogType', 'all');
    in = in.setVariable('drive_cycle_time', [0; 0.5; cfg.stopTimeS], ...
        'Workspace', model);
    in = in.setVariable('drive_cycle_power', ...
        [0; caseResult.targetPowerKW; caseResult.targetPowerKW], ...
        'Workspace', model);
    in = in.setVariable('routeA_air_control_mode_id', 2, ...
        'Workspace', model);
    in = in.setVariable('routeA_target_oer', caseResult.targetOer, ...
        'Workspace', model);
    in = in.setVariable('routeA_egr_control_mode_id', 1, ...
        'Workspace', model);
    in = in.setVariable('routeA_cegr_valve_mode_id', ...
        double(caseResult.targetEgrRatio > 0), 'Workspace', model);
    in = in.setVariable('routeA_target_egr_ratio_comp_in', ...
        caseResult.targetEgrRatio, 'Workspace', model);
    out = sim(in);
    diagnostic.simCompleted = true;

    egr = loggedTimeseries(out, 'routeA_egr_ratio_comp_in');
    area = loggedTimeseries(out, 'routeA_egr_valve_area_cmd');
    pUp = loggedTimeseries(out, 'routeA_p_egr_valve_up');
    pDown = loggedTimeseries(out, 'routeA_p_egr_valve_down');
    diagnostic.actualEgrRatio = tailMean(egr, cfg.tailSeconds);
    diagnostic.areaFractionTailMin = tailMinimum(area, cfg.tailSeconds) / ...
        cfg.cegrValveMaxArea;
    diagnostic.areaFractionTailMax = tailMaximum(area, cfg.tailSeconds) / ...
        cfg.cegrValveMaxArea;
    diagnostic.pressureUpstreamTailMPa = tailMean(pUp, cfg.tailSeconds) * 1e-6;
    diagnostic.pressureDownstreamTailMPa = tailMean(pDown, cfg.tailSeconds) * 1e-6;
    diagnostic.pressureDeltaTailMPa = diagnostic.pressureUpstreamTailMPa - ...
        diagnostic.pressureDownstreamTailMPa;
    values = [diagnostic.actualEgrRatio, diagnostic.areaFractionTailMin, ...
        diagnostic.areaFractionTailMax, diagnostic.pressureUpstreamTailMPa, ...
        diagnostic.pressureDownstreamTailMPa, diagnostic.pressureDeltaTailMPa];
    diagnostic.finiteOk = builtin('all', isfinite(values));
    diagnostic.areaWithinBounds = diagnostic.areaFractionTailMin >= 0 && ...
        diagnostic.areaFractionTailMax <= 1 + 1e-9;
    diagnostic.notSaturated = diagnostic.areaFractionTailMax < 1 - 1e-6;
    diagnostic.forwardPressureDrop = diagnostic.pressureDeltaTailMPa > 0;
    diagnostic.passed = diagnostic.fullcasePassed && diagnostic.simCompleted && ...
        diagnostic.finiteOk && diagnostic.areaWithinBounds && ...
        diagnostic.notSaturated && diagnostic.forwardPressureDrop;
catch ME
    diagnostic.errorId = string(ME.identifier);
    diagnostic.errorMessage = firstLine(string(ME.message));
end
resetModelFromDisk(model, modelFile);
end

function markDiagnosticSignals(paths)
markSignalFromBlockOutput(paths.fcu, 1, 'routeA_egr_valve_area_cmd');
markSignalFromBlockOutput(paths.fcu, 4, 'routeA_egr_ratio_comp_in');
markSignalFromBlockOutput(paths.egrValveUpPConverter, 1, ...
    'routeA_p_egr_valve_up');
markSignalFromBlockOutput(paths.egrValveDownPConverter, 1, ...
    'routeA_p_egr_valve_down');
end

function markSignalFromBlockOutput(blockPath, portNumber, signalName)
if getSimulinkBlockHandle(blockPath) == -1
    error('RouteA:Phase1MissingSignalSource', ...
        'Signal source block is not available: %s.', blockPath);
end
portHandles = get_param(blockPath, 'PortHandles');
if numel(portHandles.Outport) < portNumber
    error('RouteA:Phase1MissingSignalPort', ...
        'Signal source port is not available: %s.', blockPath);
end
portHandle = portHandles.Outport(portNumber);
lineHandle = get_param(portHandle, 'Line');
if lineHandle == -1
    error('RouteA:Phase1UnconnectedSignal', ...
        'Signal source port is not connected: %s.', blockPath);
end
set_param(lineHandle, 'Name', signalName);
set_param(portHandle, 'DataLogging', 'on');
set_param(portHandle, 'DataLoggingNameMode', 'Custom', ...
    'DataLoggingName', signalName);
end

function signal = loggedTimeseries(out, name)
element = out.logsout.get(name);
if isempty(element) || isempty(element.Values)
    error('RouteA:Phase1UnobservableSignal', ...
        'The required logged signal is unavailable: %s.', name);
end
signal = element.Values;
end

function value = tailMean(signal, seconds)
data = tailData(signal, seconds);
value = mean(data, 'all');
end

function value = tailMinimum(signal, seconds)
data = tailData(signal, seconds);
value = min(data, [], 'all');
end

function value = tailMaximum(signal, seconds)
data = tailData(signal, seconds);
value = max(data, [], 'all');
end

function data = tailData(signal, seconds)
time = signal.Time(:);
mask = time >= time(end) - seconds;
data = signal.Data(mask, :);
if isempty(data)
    error('RouteA:Phase1EmptyTail', 'No samples are available in the tail window.');
end
end

function registry = buildParameterRegistry(cfg)
mw = cfg.modelWorkspace;
paths = routeA_block_paths(char(cfg.model));
entries = { ...
    'stack_num_cells', paths.stack, 'stack_physics', 'engineering_order', ...
        'platform_default workspace', 'all', 'medium', 'accepted'; ...
    'stack_area', paths.stack, 'stack_physics', 'engineering_order', ...
        'platform_default workspace', 'all', 'medium', 'accepted'; ...
    'stack_t_membrane', paths.stack, 'stack_physics', 'official_reuse', ...
        'FuelCell MEA-derived parameter', 'all', 'medium', 'accepted'; ...
    'stack_io', paths.stack, 'stack_physics', 'engineering_order', ...
        'platform_default workspace', 'all', 'high', 'accepted'; ...
    'stack_iL', paths.stack, 'stack_physics', 'engineering_order', ...
        'platform_default workspace', 'all', 'high', 'accepted'; ...
    'comp_p_ratio_TLU', paths.compressor, 'device_capacity', ...
        'engineering_order', 'current compressor map interface', 'all', ...
        'high', 'L2_pending'; ...
    'comp_rpm_TLU', paths.compressor, 'device_capacity', ...
        'engineering_order', 'current compressor map interface', 'all', ...
        'high', 'L2_pending'; ...
    'comp_mdot_corr_TLU', paths.compressor, 'device_capacity', ...
        'engineering_order', 'current compressor map interface', 'all', ...
        'high', 'L2_pending'; ...
    'intercooler_dp_nominal', paths.intercooler, 'device_capacity', ...
        'L2_interface', 'equivalent pressure-drop interface', 'all', ...
        'high', 'L2_pending'; ...
    'cegr_pipe_length', paths.egrPipe, 'device_capacity', ...
        'engineering_order', 'platform_default workspace', 'withCEGR', ...
        'medium', 'accepted'; ...
    'cegr_valve_max_area', paths.egrValve, 'device_capacity', ...
        'engineering_order', 'platform_default workspace', 'withCEGR', ...
        'high', 'pending_diagnostic'; ...
    'cegr_valve_open_min_area', paths.egrValve, 'open_state_limit', ...
        'engineering_order', 'open-state numerical lower bound', 'withCEGR', ...
        'medium', 'accepted'; ...
    'separator_l2_efficiency', paths.separatorObserver, 'device_capacity', ...
        'L2_interface', 'saturation-excess estimator', 'withCEGR', ...
        'high', 'L2_pending'; ...
    'tank_p', paths.hydrogenSource, 'device_capacity', 'engineering_order', ...
        'platform_default workspace', 'all', 'medium', 'L2_pending'; ...
    'anode_separator_dp_nominal', paths.anodeWaterSeparator, ...
        'device_capacity', 'L2_interface', 'equivalent separator interface', ...
        'all', 'high', 'L2_pending'; ...
    'coolant_tube_D', paths.coolingPump, 'device_capacity', ...
        'engineering_order', 'controlled pump flow-area parameter', 'all', ...
        'high', 'L2_pending'; ...
    'routeA_stack_temperature_set_C', paths.stackTemperature, 'control', ...
        'engineering_order', 'existing coolant controller interface', 'all', ...
        'medium', 'accepted'; ...
    'radiator_air_area_primary', paths.heatDissipation, 'device_capacity', ...
        'L2_interface', 'geometry without UA or airflow evidence', 'all', ...
        'high', 'L2_pending'; ...
    'routeA_air_pid_Kp', paths.compressorControl, 'control', ...
        'engineering_order', 'platform_default workspace', 'all', 'high', ...
        'accepted'; ...
    'routeA_air_pid_Ki', paths.compressorControl, 'control', ...
        'engineering_order', 'platform_default workspace', 'all', 'high', ...
        'accepted'; ...
    'routeA_egr_control_Kp_area', paths.fcu, 'control', ...
        'engineering_order', 'platform_default workspace', 'withCEGR', ...
        'high', 'pending_diagnostic'; ...
    'routeA_egr_control_Ki_area', paths.fcu, 'control', ...
        'engineering_order', 'platform_default workspace', 'withCEGR', ...
        'high', 'pending_diagnostic'; ...
    'routeA_external_case_enabled', char(cfg.model), 'numerical', ...
        'external_case', 'boundary guard only', 'all', 'none', 'guard'};

nEntries = size(entries, 1);
name = strings(nEntries, 1);
blockPath = strings(nEntries, 1);
category = strings(nEntries, 1);
sourceLevel = strings(nEntries, 1);
sourceDetail = strings(nEntries, 1);
applicability = strings(nEntries, 1);
uncertainty = strings(nEntries, 1);
status = strings(nEntries, 1);
value = cell(nEntries, 1);
unit = strings(nEntries, 1);
for idx = 1:nEntries
    name(idx) = string(entries{idx, 1});
    blockPath(idx) = string(entries{idx, 2});
    category(idx) = string(entries{idx, 3});
    sourceLevel(idx) = string(entries{idx, 4});
    sourceDetail(idx) = string(entries{idx, 5});
    applicability(idx) = string(entries{idx, 6});
    uncertainty(idx) = string(entries{idx, 7});
    status(idx) = string(entries{idx, 8});
    value{idx} = getWorkspaceValue(mw, char(name(idx)), NaN);
    unit(idx) = parameterUnit(name(idx));
end
registry = table(name, value, unit, category, sourceLevel, sourceDetail, ...
    applicability, uncertainty, status, blockPath);
end

function registry = applyPassiveCegrDiagnosticStatus(registry, diagnostics)
names = ["cegr_valve_max_area", "routeA_egr_control_Kp_area", ...
    "routeA_egr_control_Ki_area"];
indices = ismember(registry.name, names);
if builtin('all', [diagnostics.passed])
    registry.status(indices) = "verified_nominal";
else
    registry.status(indices) = "blocking";
end
end

function unit = parameterUnit(name)
units = struct( ...
    'stack_num_cells', '-', 'stack_area', 'cm^2', 'stack_t_membrane', 'um', ...
    'stack_io', 'A/cm^2', 'stack_iL', 'A/cm^2', 'comp_p_ratio_TLU', '-', ...
    'comp_rpm_TLU', 'rpm', 'comp_mdot_corr_TLU', 'kg/s', ...
    'intercooler_dp_nominal', 'MPa', 'cegr_pipe_length', 'm', ...
    'cegr_valve_max_area', 'm^2', 'cegr_valve_open_min_area', 'm^2', ...
    'separator_l2_efficiency', '-', 'tank_p', 'MPa', ...
    'anode_separator_dp_nominal', 'MPa', ...
    'routeA_stack_temperature_set_C', 'degC', ...
    'radiator_air_area_primary', 'm^2', 'routeA_air_pid_Kp', '-/(kg/s)', ...
    'routeA_air_pid_Ki', '-/(kg/s*s)', ...
    'routeA_egr_control_Kp_area', 'm^2', ...
    'routeA_egr_control_Ki_area', 'm^2/s', ...
    'coolant_tube_D', 'm', ...
    'routeA_external_case_enabled', '-');
unit = string(units.(char(name)));
end

function contract = buildInterfaceContract(~)
rows = { ...
    'u', 'drive_cycle_power', 'kW', 'continuous profile', ...
        'runner', 'Electrical Load', 'power request', 'verified'; ...
    'u', 'routeA_air_control_mode_id', '-', 'continuous configuration', ...
        'runner', 'Compressor Control', '1 mdot, 2 OER, 3 direct', 'verified'; ...
    'u', 'routeA_target_mdot_comp_inlet', 'kg/s', 'continuous', ...
        'runner', 'Compressor Control', 'active only in mdot mode', 'verified'; ...
    'u', 'routeA_target_oer', '-', 'continuous', ...
        'runner', 'Compressor Control', 'active only in OER mode', 'verified'; ...
    'u', 'routeA_compressor_cmd_direct', '-', 'continuous', ...
        'runner', 'Compressor Control', 'active only in direct mode', 'verified'; ...
    'u', 'routeA_cegr_enabled', '-', 'update-diagram only', ...
        'runner', 'cEGR_Mode_Selector', 'variant topology selector', 'verified'; ...
    'u', 'routeA_cegr_valve_mode_id', '-', 'update-diagram only', ...
        'runner', 'EGRValveRestriction', '0 closed, 1 open; no runtime switching', 'verified'; ...
    'u', 'routeA_egr_control_mode_id', '-', 'continuous configuration', ...
        'runner', 'FCU_BoP_Control', '1 ratio, 2 area', 'verified'; ...
    'u', 'routeA_target_egr_ratio_comp_in', '-', 'continuous', ...
        'runner', 'FCU_BoP_Control', 'abs egr mdot / abs compressor inlet mdot', 'verified'; ...
    'u', 'routeA_egr_valve_area_direct', 'm^2', 'continuous', ...
        'runner', 'FCU_BoP_Control', 'active only in direct-area mode', 'verified'; ...
    'u', 'routeA_target_p_ca_out_MPa', 'MPa', 'continuous', ...
        'runner', 'Cathode Exhaust', 'absolute cathode outlet target', 'verified'; ...
    'u', 'routeA_cathode_humidifier_gain', '-', 'continuous', ...
        'runner', 'Cathode Humidifier', 'zero bypass, one active', 'verified'; ...
    'u', 'routeA_stack_temperature_set_C', 'degC', 'continuous', ...
        'runner', 'Cooling System', 'existing thermal controller target', 'verified'; ...
    'w', 'env_p, env_T, env_RH, env_yO2', 'MPa, degC, -, -', ...
        'constant per simulation', 'platform_default', ...
        'Gas and thermal boundaries', 'ambient state', 'verified'; ...
    'w', 'tank_p, tank_yH2', 'MPa, -', 'platform_default', ...
        'platform_default', 'Hydrogen Source', 'hydrogen source state', 'verified'; ...
    'w', 'initial physical states', 'domain-specific', 'model initialization', ...
        'platform_default', 'Simscape states', 'independent simulation start only', 'verified'; ...
    'y', 'i, v, P, T', 'A, V, kW and degC', 'continuous', ...
        'Measurements', 'controller and runner', 'stack measurements', 'verified'; ...
    'y', 'routeA_mdot_comp_inlet', 'kg/s', 'continuous', ...
        'Oxygen Source', 'FCU_BoP_Control', 'compressor inlet flow', 'verified'; ...
    'y', 'routeA_egr_ratio_comp_in', '-', 'continuous', ...
        'FCU_BoP_Control', 'runner', 'actual cEGR ratio', 'verified'; ...
    'y', 'routeA_p_outlet', 'Pa', 'continuous', ...
        'Cathode Exhaust', 'runner', 'cathode outlet pressure', 'verified'; ...
    'y', 'routeA_RH_ca_in, routeA_RH_ca_out', '-', 'continuous', ...
        'Cathode humidifier and exhaust', 'runner', 'cathode humidity', 'verified'; ...
    'y', 'routeA_exhaust_mdot', 'kg/s', 'continuous', ...
        'Cathode Exhaust', 'runner', 'main exhaust mass flow', 'verified'; ...
    'z', 'routeA_mdot_species_ca_in_ts', 'kg/s by species', 'continuous', ...
        'Cathode inlet sensor', 'audit', 'inlet species-flow truth', 'verified'; ...
    'z', 'lambda_ca_in', '-', 'derived continuous', ...
        'species flow and stack current', 'audit', 'actual oxygen stoichiometry', 'verified'; ...
    'z', 'routeA_p_egr_valve_up, routeA_p_egr_valve_down', 'Pa', ...
        'temporary named logging', 'cEGR pressure converters', 'audit', ...
        'passive valve pressure direction', 'verified'; ...
    'z', 'routeA_egr_valve_area_cmd', 'm^2', 'continuous', ...
        'FCU_BoP_Control', 'audit', 'valve saturation evidence', 'verified'; ...
    'z', 'routeA_m_water_sep', 'kg or kg/s pending unit audit', 'continuous', ...
        'SeparatorOrCondensation', 'audit', 'L2 water separation KPI', 'L2_pending'; ...
    'z', 'stack thermal demand', 'kW', 'derived steady state', ...
        'reaction ledger', 'audit', 'thermoneutral heat screen', 'derived'};

contract = cell2table(rows, 'VariableNames', {'class', 'name', 'unit', ...
    'timing', 'producer', 'consumer', 'meaning', 'status'});
end

function gaps = buildGapTable(passiveDiagnostics, cfg)
name = [ ...
    "compressor_efficiency_and_shaft_power"; ...
    "compressor_pressure_ratio_coverage"; ...
    "anode_lambda_purge_and_recirculation_capacity"; ...
    "water_separator_efficiency"; ...
    "cooling_pump_capacity_and_control"; ...
    "radiator_UA_and_airflow_capacity"; ...
    "passive_cegr_pressure_and_area_capacity"];
classification = [ ...
    "L2_pending"; "unobservable"; "unobservable"; "L2_pending"; ...
    "unobservable"; "unobservable"; "verified_or_blocking"];
critical = [false; false; false; false; false; false; true];
detail = [ ...
    "Current compressor is a flow-source/map interface, not a mechanical efficiency or surge model."; ...
    "The current audit records flow and rpm; compressor pressure-ratio coverage remains an L2 observability gap."; ...
    "Phase 1 calculates stoichiometric hydrogen demand only; no anode lambda or purge proof is claimed."; ...
    "SeparatorOrCondensation is an L2 saturation-excess estimator with no component efficiency evidence."; ...
    "The cooling pump is a controlled mass-flow source; no flow-capacity map or electric-power evidence is available."; ...
    "Radiator geometry exists, but UA, fan airflow, and independent heat-rejection evidence are absent."; ...
    "Passive cEGR requires positive valve pressure drop, unsaturated area, and passing existing full-case tracking."];
status = repmat("pending", numel(name), 1);
status(1:end-1) = "deferred";
if builtin('all', [passiveDiagnostics.passed])
    status(end) = "verified";
else
    status(end) = "blocking";
end

gaps = table(name, classification, critical, status, detail);
if cfg.parameterLayer ~= "platform_default" || cfg.externalCaseEnabled
    error('RouteA:Phase1ParameterBoundary', ...
        'The audit must not continue outside platform_default.');
end
end

function summary = buildSummary(study, reactionLedger, registry, diagnostics, gaps)
matrixPassed = study.passed;
reactionFinite = builtin('all', builtin('all', ...
    isfinite(reactionLedger{:, 2:end})));
registryComplete = builtin('all', strlength(registry.name) > 0) && ...
    builtin('all', strlength(registry.unit) > 0) && ...
    builtin('all', strlength(registry.status) > 0);
passivePassed = builtin('all', [diagnostics.passed]);
blockingGaps = sum(gaps.critical & gaps.status == "blocking");
auditComplete = matrixPassed && reactionFinite && registryComplete && passivePassed;
engineeringMatchReady = auditComplete && blockingGaps == 0;
summary = table(matrixPassed, reactionFinite, registryComplete, passivePassed, ...
    blockingGaps, auditComplete, engineeringMatchReady);
end

function displayAuditSummary(audit)
fprintf('\nRoute A Phase 1 matching and interface audit\n');
disp(audit.summary);
fprintf('\nPassive cEGR diagnostics\n');
disp(struct2table(audit.passiveCegrDiagnostics));
fprintf('\nOpen gaps\n');
disp(audit.gaps(:, {'name', 'classification', 'critical', 'status'}));
end

function value = getWorkspaceValue(modelWorkspace, name, fallback)
value = fallback;
try
    value = modelWorkspace.getVariable(name);
catch
end
end

function text = firstLine(text)
parts = splitlines(text);
if ~isempty(parts)
    text = parts(1);
end
end

function resetModelFromDisk(model, modelFile)
if bdIsLoaded(model)
    close_system(model, 0);
end
load_system(modelFile);
end

function restoreModelAndFolder(oldDir, model, modelFile)
if bdIsLoaded(model)
    close_system(model, 0);
end
load_system(modelFile);
cd(oldDir);
end
