function study = run_routeA_stage1_constant_voltage_cegr_matrix(studyCfg)
% Compatibility wrapper for the generic Voltage boundary study.

if nargin < 1 || isempty(studyCfg)
    studyCfg = struct();
end
scriptDir = fileparts(mfilename('fullpath'));
modelDir = fullfile(scriptDir, '..', '..', '01_模型', ...
    'RouteA_GasMixture_Derived');
defaults = struct( ...
    'targetVoltage_V', 394.9, ...
    'targetAirEquivalentOer', 3, ...
    'researchDuration_s', 600, ...
    'tailLogicalWindow_s', [540, 600], ...
    'studyMaxStep_s', 5, ...
    'targetRatios', [0, 0.10, 0.30], ...
    'piKp_A_V', 1, ...
    'piKi_A_V_s', 0.05, ...
    'runWaterLedger', true, ...
    'caseIds', strings(1, 0), ...
    'executionMode', "parallel", ...
    'parallelWorkers', 2, ...
    'showProgress', true, ...
    'resultFile', "");
names = fieldnames(studyCfg);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(defaults, name)
        error('RouteA:VoltageWrapperConfigField', ...
            'Unsupported voltage wrapper field: %s.', name);
    end
    defaults.(name) = studyCfg.(name);
end
validateattributes(defaults.targetVoltage_V, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(defaults.targetRatios, {'numeric'}, ...
    {'vector', 'nonempty', 'nonnegative', 'finite'});
ratios = defaults.targetRatios(:).';
cases = struct([]);
for idx = 1:numel(ratios)
    ratio = ratios(idx);
    item = struct();
    item.caseId = "nominal_voltage_cegr_" + ratioText(ratio);
    item.boundary = struct('type', "Voltage", ...
        'profile', defaults.targetVoltage_V);
    item.cegr = ratio;
    item.air = struct('modeId', 2, ...
        'targetOer', defaults.targetAirEquivalentOer);
    item.controller = struct( ...
        'Kp_A_V', defaults.piKp_A_V, ...
        'Ki_A_V_s', defaults.piKi_A_V_s, ...
        'currentMin_A', 0, ...
        'currentMax_A', 392);
    item.acceptance = struct( ...
        'voltageRelativeTolerance', 5e-3, ...
        'voltageSpanFraction', 5e-3);
    if isempty(cases)
        cases = item;
    else
        cases(end + 1) = item; %#ok<AGROW>
    end
end
if ~isempty(defaults.caseIds)
    requested = string(defaults.caseIds);
    keep = ismember(string({cases.caseId}), requested);
    if ~builtin('any', keep)
        error('RouteA:VoltageWrapperCaseSelection', ...
            'None of the requested caseIds is available.');
    end
    cases = cases(keep);
end
genericCfg = struct( ...
    'initialStateFile', fullfile(modelDir, ...
        'RouteA_platform_default_initial_state.mat'), ...
    'researchDuration_s', defaults.researchDuration_s, ...
    'tailLogicalWindow_s', defaults.tailLogicalWindow_s, ...
    'studyMaxStep_s', defaults.studyMaxStep_s, ...
    'commandStartOffset_s', 0.5, ...
    'runWaterLedger', logical(defaults.runWaterLedger), ...
    'executionMode', defaults.executionMode, ...
    'parallelWorkers', defaults.parallelWorkers, ...
    'showProgress', logical(defaults.showProgress), ...
    'resultFile', defaults.resultFile, ...
    'cases', cases);
study = run_routeA_electrical_boundary_study(genericCfg);
study.wrapper = "constant_voltage";
study.targetVoltage_V = defaults.targetVoltage_V;
study.targetAirEquivalentOer = defaults.targetAirEquivalentOer;
study.pi = struct('Kp_A_V', defaults.piKp_A_V, ...
    'Ki_A_V_s', defaults.piKi_A_V_s, ...
    'currentMin_A', 0, 'currentMax_A', 392);
assignin('base', 'routeA_stage1_constant_voltage_cegr_matrix', study);
assignin('base', 'routeA_stage1_constant_voltage_summary', study.summaryTable);
assignin('base', 'routeA_stage1_constant_voltage_water_ledger', ...
    study.waterLedger);
end

function text = ratioText(ratio)
text = replace(string(sprintf('%.2f', ratio)), '.', 'p');
end
