function metadata = routeA_generate_platform_default_drive_cycle_initial_state(sourceInitialStateFile)
% Generate a candidate normal-operation state for the Power branch.
%
% ModelOperatingPoint carries a checksum of the Electrical Load branch. The
% formal Current state therefore cannot initialize the Power branch even
% when its physical source condition is the same. This generator preserves
% that source condition by using the Current-state power as the low-load
% Power command, then applies the standard mode-1 zero-cEGR periodic
% conditioning protocol.

scriptDir = fileparts(mfilename('fullpath'));
modelDir = fullfile(scriptDir, '..', '..', '01_模型', ...
    'RouteA_GasMixture_Derived');
model = 'PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01';
modelFile = fullfile(modelDir, [model '.slx']);
currentCandidateFile = fullfile(modelDir, ...
    'RouteA_platform_default_initial_state_candidate_mode1_current.mat');
candidateFile = fullfile(modelDir, ...
    'RouteA_platform_default_initial_state_candidate_mode1_power.mat');
if nargin < 1 || strlength(string(sourceInitialStateFile)) == 0
    sourceInitialStateFile = currentCandidateFile;
end
sourceInitialStateFile = char(sourceInitialStateFile);
oldDir = pwd;
addpath(scriptDir);
addpath(modelDir);
cd(modelDir);
cleanup = onCleanup(@() routeA_restore_model_and_folder( ...
    model, modelFile, oldDir));

if ~isfile(sourceInitialStateFile)
    error('RouteA:MissingCurrentInitialState', ...
        'The source Current initial state is required: %s.', sourceInitialStateFile);
end
loaded = load(sourceInitialStateFile, 'routeA_initial_metadata');
if isfield(loaded, 'routeA_initial_metadata')
    source = loaded.routeA_initial_metadata;
else
    error('RouteA:InvalidCurrentInitialState', ...
        'The formal Current initial-state metadata is unavailable.');
end
required = {'model', 'physicalSummary', 'snapshotTimeS', ...
    'cegrTopologyEnabled', 'cegrValveModeId', 'egrReferenceKind', ...
    'cegrValveMaxArea_m2'};
if ~builtin('all', isfield(source, required)) || ...
        ~isfield(source.physicalSummary, 'stackPower_kW')
    error('RouteA:InvalidCurrentInitialStateMetadata', ...
        'The formal Current initial-state metadata is incomplete.');
end
if string(source.model) ~= string(model) || ...
        ~source.cegrTopologyEnabled || source.cegrValveModeId ~= 1 || ...
        string(source.egrReferenceKind) ~= "mode1_zero_target_near_zero"
    error('RouteA:CurrentInitialStateMode', ...
        'The formal Current state is not the required mode-1 zero-cEGR state.');
end
if ~isfield(source, 'loadInputType') || ...
        string(source.loadInputType) ~= "Current" || ...
        ~isfield(source, 'schema') || ...
        ~contains(string(source.schema), "_v09_")
    error('RouteA:CurrentInitialStateRefreshRequired', ...
        ['The source must be a fresh v09 Current candidate; historical ', ...
        'or other-branch states cannot seed a new I/P/V bundle.']);
end
sourcePower_kW = source.physicalSummary.stackPower_kW;
validateattributes(sourcePower_kW, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});

preconditionCfg = struct( ...
    'loadInputType', "Power", ...
    'targetPower_kW', sourcePower_kW, ...
    'maxStep_s', 5);
[routeA_initial_state, metadata, audit] = ...
    routeA_prepare_parameter_consistent_initial_state( ...
    model, modelFile, struct(), preconditionCfg);
if ~audit.periodic.passed
    error('RouteA:PowerInitialStatePeriodic', ...
        'The Power candidate did not pass periodic verification.');
end
if abs(metadata.cegrValveMaxArea_m2 - source.cegrValveMaxArea_m2) > ...
        1e-12 * max(1, abs(source.cegrValveMaxArea_m2))
    error('RouteA:PowerInitialStateParameterMismatch', ...
        'The Power candidate does not match the formal valve area.');
end

metadata.schema = 'RouteA_platform_default_initial_state_v09_mode1_power';
metadata.candidateSource = ...
    "routeA_generate_platform_default_drive_cycle_initial_state";
metadata.loadInputType = "Power";
metadata.sourceCurrentSnapshotTimeS = source.snapshotTimeS;
metadata.sourceCurrentPower_kW = sourcePower_kW;
metadata.sourceCurrentStateSchema = string(source.schema);
metadata.stateClass = string(class(routeA_initial_state));
routeA_initial_metadata = metadata;
save(candidateFile, 'routeA_initial_state', ...
    'routeA_initial_metadata', '-v7.3');
assignin('base', 'routeA_platform_default_drive_cycle_candidate_metadata', ...
    routeA_initial_metadata);
fprintf(['Saved Route A mode-1 Power initial-state candidate: %s ', ...
    '(P_source=%.4g kW)\n'], candidateFile, sourcePower_kW);

clear cleanup;
end
