function study = run_routeA_stage1_constant_power_cegr_matrix(studyCfg)
% Compatibility wrapper for the generic Power boundary study.
%
% The former fixed-total-flow diagnostic is intentionally not part of the
% active wrapper. It remains historical evidence, while this entry point
% reproduces the three current-linked nominal Power cases.

if nargin < 1 || isempty(studyCfg)
    studyCfg = struct();
end
scriptDir = fileparts(mfilename('fullpath'));
modelDir = fullfile(scriptDir, '..', '..', '01_模型', ...
    'RouteA_GasMixture_Derived');
defaults = struct( ...
    'targetPower_kW', 77.408, ...
    'targetAirEquivalentOer', 3, ...
    'researchDuration_s', 600, ...
    'tailLogicalWindow_s', [540, 600], ...
    'studyMaxStep_s', 5, ...
    'targetRatios', [0, 0.10, 0.30], ...
    'runWaterLedger', true, ...
    'caseIds', strings(1, 0), ...
    'executionMode', "parallel", ...
    'parallelWorkers', 2, ...
    'showProgress', true, ...
    'resultFile', "");
names = fieldnames(studyCfg);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(defaults, name)
        error('RouteA:PowerWrapperConfigField', ...
            'Unsupported power wrapper field: %s.', name);
    end
    defaults.(name) = studyCfg.(name);
end
validateattributes(defaults.targetPower_kW, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(defaults.targetRatios, {'numeric'}, ...
    {'vector', 'nonempty', 'nonnegative', 'finite'});
ratios = defaults.targetRatios(:).';
cases = struct([]);
for idx = 1:numel(ratios)
    item = struct();
    ratio = ratios(idx);
    item.caseId = "nominal_power_cegr_" + ratioText(ratio);
    item.boundary = struct('type', "Power", ...
        'profile', defaults.targetPower_kW);
    item.cegr = ratio;
    item.air = struct('modeId', 2, ...
        'targetOer', defaults.targetAirEquivalentOer);
    item.acceptance = struct('powerRelativeTolerance', 5e-3);
    if isempty(cases)
        cases = item;
    else
        cases(end + 1) = item; %#ok<AGROW>
    end
end
if ~isempty(defaults.caseIds)
    requested = string(defaults.caseIds);
    keep = ismember(string({cases.caseId}), requested);
    if ~builtin('any', keep)
        error('RouteA:PowerWrapperCaseSelection', ...
            'None of the requested caseIds is available.');
    end
    cases = cases(keep);
end
genericCfg = struct( ...
    'initialStateFile', fullfile(modelDir, ...
        'RouteA_platform_default_initial_state.mat'), ...
    'researchDuration_s', defaults.researchDuration_s, ...
    'tailLogicalWindow_s', defaults.tailLogicalWindow_s, ...
    'studyMaxStep_s', defaults.studyMaxStep_s, ...
    'commandStartOffset_s', 0.5, ...
    'runWaterLedger', logical(defaults.runWaterLedger), ...
    'executionMode', defaults.executionMode, ...
    'parallelWorkers', defaults.parallelWorkers, ...
    'showProgress', logical(defaults.showProgress), ...
    'resultFile', defaults.resultFile, ...
    'cases', cases);
study = run_routeA_electrical_boundary_study(genericCfg);
study.wrapper = "constant_power_current_linked";
study.targetPower_kW = defaults.targetPower_kW;
study.targetAirEquivalentOer = defaults.targetAirEquivalentOer;
study.adaptiveAir = struct( ...
    'modeId', 2, 'cases', study.cases, ...
    'passed', study.allCasesPassed);
study.fixedTotalFlow = struct( ...
    'diagnosticOnly', true, ...
    'migrated', false, ...
    'reason', "historical_fixed_total_flow_not_in_core_runner");
study.fixedFlowDiagnosticCompleted = false;
study.fixedFlowOxygenFeasible = NaN;
study.fixedFlowPowerCommandMaintained = NaN;
assignin('base', 'routeA_stage1_constant_power_cegr_matrix', study);
assignin('base', 'routeA_stage1_constant_power_summary', study.summaryTable);
assignin('base', 'routeA_stage1_constant_power_water_ledger', ...
    study.waterLedger);
end

function text = ratioText(ratio)
text = replace(string(sprintf('%.2f', ratio)), '.', 'p');
end
