function params = routeA_focused_parameter_defaults(modelId)
% Return defaults for the focused cathode-cEGR research model.
%
% Shared Route A platform values remain the source for environment and
% solver defaults. The active focused model is sized from the explicit
% 240 kW external test case; its geometry and BOP assumptions remain
% visible rather than being promoted to platform defaults.

if nargin < 1
    modelId = "focused_legacy";
end
paths = routeA_focused_paths(modelId);
addpath(char(paths.sharedScriptDir));
platform = routeA_platform_default_parameters();

params = struct();
params.modelId = paths.modelId;
params.modelName = paths.modelName;
params.sourceModelName = ...
    "PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01";
params.parameterLayer = "external_case";
params.externalCase = struct( ...
    'id', "240kW_stack_606cell_380cm2", ...
    'source', "00_支撑材料/01_项目系统实验数据/240kw电堆数据.txt", ...
    'scope', "stack_geometry_airflow_cathode_pressure_drop_and_BOP_screening", ...
    'extrapolation', "iL_above_1p9_Acm2_and_BOP_capacity_are_screening_assumptions");
params.architectureId = ...
    "Passive_SelfHumidifying_PostSeparatorGas_CompressorInlet";
params.targetArchitectureId = ...
    "Passive_ExternalMembraneHumidifier_PostSeparatorGas_CompressorInlet";
params.architecture = struct( ...
    'drive', "passive_pressure_difference", ...
    'stackHumidification', "self_humidifying_external_MIn_disabled", ...
    'takeoff', "post_separator_gas_boundary", ...
    'returnLocation', "compressor_inlet", ...
    'controlLayer', "common_backpressure_and_return_valve", ...
    'backpressureLocation', "common_pre_split", ...
    'separatorStatus', "gas_phase_L2_no_composition_change", ...
    'status', "P3_self_humidifying_configuration_in_progress");

if params.modelId == "ejector_self_humidifying"
    params.sourceModelName = ...
        "PEMFuelCellSystem_Cathode_cEGR_SelfHumidifying_v01";
    params.architectureId = ...
        "Passive_Ejector_PostSeparatorGas_PostCompressorCathodeInlet";
    params.targetArchitectureId = params.architectureId;
    params.architecture = struct( ...
        'drive', "ejector_primary_pressure_difference", ...
        'stackHumidification', "self_humidifying_external_MIn_disabled", ...
        'takeoff', "post_intercooler_primary", ...
        'returnLocation', "post_compressor_cathode_inlet", ...
        'controlLayer', "compressor_common_backpressure_and_ejector_geometry", ...
        'backpressureLocation', "common_pre_split", ...
        'separatorStatus', "gas_phase_L2_no_composition_change", ...
        'status', "E3_ejector_structure_in_progress");
end

params.stack = struct( ...
    'numCells', 606, ...
    'area_cm2', 380, ...
    'iL_A_cm2', 2.5, ...
    'io_A_cm2', 1e-4, ...
    'alpha', 0.7, ...
    'temperature_C', 80, ...
    'temperatureSource', "focused_stack_temperature_C");

params.anode = struct( ...
    'feedPressure_MPa_abs', ...
        platform.controls.anode_source_pressure_MPa_abs.value, ...
    'inletMdot_kg_s', 0.008, ...
    'outletPressure_MPa_abs', ...
        platform.environment.ambient_p_MPa_abs.value, ...
    'boundaryTemperature_C', platform.environment.ambient_T_C.value, ...
    'hydrogenMoleFraction', platform.anode.tank.yH2.value, ...
    'pipeLength_m', 1, ...
    'pipeDiameter_m', 0.056, ...
    'pipeArea_m2', pi * 0.056^2 / 4, ...
    'pipeExtraLength_m', 0.1, ...
    'pipeRoughness_m', 15e-6);

params.cathode = struct( ...
    'sourcePressure_MPa_abs', ...
        platform.environment.ambient_p_MPa_abs.value, ...
    'sourceTemperature_C', ...
        platform.controls.cathode_source_temperature_C.value, ...
    'channelDpNominal_MPa', 0.0368422, ...
    'channelMdotNominal_kg_s', 0.27182, ...
    'channelFlowArea_m2', pi * 0.0717^2 / 4, ...
    'commonBackpressureValveMaxArea_m2', 0.00134, ...
    'commonBackpressureValveOpenMinArea_m2', 1e-10);

params.bop = struct( ...
    'compressorMap', struct( ...
        'rpm_TLU', [0, 50000, 80000], ...
        'p_ratio_TLU', [1; 1.5; 2; 2.5; 3], ...
        'mdot_corr_TLU', [ ...
            0, 0.28, 0.56; ...
            0, 0.26, 0.52; ...
            0, 0.24, 0.48; ...
            0, 0.22, 0.44; ...
            0, 0.20, 0.40]), ...
    'intercoolerMdotNominal_kg_s', 0.40798, ...
    'intercoolerDpNominal_MPa', 0.005, ...
    'intercoolerArea_m2', pi * 0.1^2 / 4, ...
    'separatorMdotNominal_kg_s', 0.40798, ...
    'separatorDpNominal_MPa', 0.002, ...
    'separatorArea_m2', pi * 0.072^2 / 4, ...
    'cegrValveMaxArea_m2', 0.001, ...
    'cegrPipeDiameter_m', 0.072);

params.interface = struct( ...
    'schemaVersion', "RouteA_Focused_ParameterBridge_v01", ...
    'anodeBoundary', "mass_flow_inlet_pressure_outlet", ...
    'thermalBoundary', "fixed_temperature_source", ...
    'standardAnodePressureMapping', ...
        "controls.anode.sourcePressure_MPa_abs -> focused_anode_feed_p_MPa_abs", ...
    'standardAnodeTemperatureMapping', ...
        "controls.anode.sourceTemperature_C -> focused_anode_boundary_T_C", ...
    'standardAnodeCompositionMapping', ...
        "controls.anode.h2MoleFraction -> focused_anode_yH2", ...
    'cathodeSourceTemperatureMapping', ...
        "controls.cathode.sourceTemperature_C -> env_T", ...
    'airInletPressureSource', ...
        "controls.environment.ambientPressure_MPa_abs -> env_p", ...
    'cathodeChannelResistanceMapping', ...
        "focused.cathodeChannel* -> cathode_channel_*", ...
    'electrochemistryMapping', ...
        "focused.stackIo_A_cm2/stackAlpha -> stack_io/stack_alpha", ...
    'freshAirHumidityMapping', ...
        "environment(T,p,RH) -> cathode.freshAirWaterMoleFraction -> env_yH20", ...
    'commonBackpressureValveMapping', ...
        "focused.commonBackpressureValve* -> common_bp_valve_*", ...
    'standardThermalMapping', ...
        "controls.thermal.stackTemperatureSet_C -> focused_stack_temperature_C", ...
    'notApplicablePolicy', ...
        "removed_BOP_parameters_are_reported_not_applied");

params.solver = struct( ...
    'solver', platform.numerics.solver.value, ...
    'relTol', platform.numerics.relTol.value, ...
    'absTol', platform.numerics.absTol.value, ...
    'maxStep_s', platform.numerics.maxStep_s.value, ...
    'stopTime_s', platform.numerics.stopTime_s.value);

params.environment = struct( ...
    'ambientTemperature_C', platform.environment.ambient_T_C.value, ...
    'ambientPressure_MPa_abs', platform.environment.ambient_p_MPa_abs.value, ...
    'ambientRelativeHumidity', 0.5);
end
