function analysis = routeA_focused_performance_analysis(study)
% Summarize the performance contract across focused study cases.

analysis = struct( ...
    'schemaVersion', "RouteA_Focused_PerformanceAnalysis_v01", ...
    'status', "no_cases", ...
    'comparisonEligibleCaseIds', strings(0, 1), ...
    'caseSummary', repmat(summaryTemplate(), 0, 1), ...
    'comparisonContract', struct( ...
        'sameBoundaryRequired', true, ...
        'sameSolverRequired', true, ...
        'sameInitializationRequired', true, ...
        'excludedFromEngineeringConclusion', ...
            ["liquid_water_inventory"; "liquid_transport"; ...
             "separator_efficiency"; "compressor_parasitic_power"]));

if ~isstruct(study) || ~isfield(study, 'cases') || isempty(study.cases)
    return;
end

rows = repmat(summaryTemplate(), numel(study.cases), 1);
for idx = 1:numel(study.cases)
    item = study.cases(idx);
    rows(idx).caseId = string(item.caseId);
    rows(idx).passed = logical(getField(item, 'passed', false));
    rows(idx).simCompleted = logical(getField(item, 'simCompleted', false));
    rows(idx).failureCategory = string(getField(item, ...
        'failureCategory', ""));
    if ~isfield(item, 'performance') || ~isstruct(item.performance)
        continue;
    end
    p = item.performance;
    rows(idx).status = string(getField(p, 'status', "not_available"));
    rows(idx).comparisonEligible = logical(getField(p, ...
        'comparisonEligible', false));
    if isfield(p, 'electrical')
        rows(idx).current_A = p.electrical.current_A;
        rows(idx).voltage_V = p.electrical.voltage_V;
        rows(idx).power_kW = p.electrical.power_kW;
        rows(idx).currentDensity_A_cm2 = p.electrical.currentDensity_A_cm2;
        rows(idx).powerDensity_kW_cm2 = p.electrical.powerDensity_kW_cm2;
    end
    if isfield(p, 'cegr')
        rows(idx).targetCegrRatio = p.cegr.targetRatio;
        rows(idx).actualCegrRatioMixBasis = p.cegr.actualRatioMixBasis;
        rows(idx).actualCegrRatioFreshBasis = p.cegr.actualRatioFreshBasis;
    end
    if isfield(p, 'cathode')
        rows(idx).lambda = p.cathode.oxygenStoich_lambda;
        rows(idx).oxygenPartialPressure_Pa = ...
            p.cathode.compressorInletO2PartialPressure_Pa;
        rows(idx).cathodeInletRH = p.cathode.cathodeInletRH;
    end
    if isfield(p, 'thermal')
        rows(idx).stackTemperature_C = p.thermal.stackTemperature_C;
        rows(idx).stackTemperatureSet_C = p.thermal.stackTemperatureSet_C;
    end
    if isfield(p, 'water')
        rows(idx).mixerCondensationRate_kg_s = ...
            p.water.mixerCondensationRate_kg_s;
        rows(idx).mixerSaturationRatio = p.water.mixerSaturationRatio;
    end
end

eligible = [rows.comparisonEligible];
analysis.caseSummary = rows;
analysis.comparisonEligibleCaseIds = [rows(eligible).caseId].';
if any(eligible)
    analysis.status = "behavior_verified_for_eligible_cases";
else
    analysis.status = "executed_but_no_case_is_comparison_eligible";
end
end

function value = getField(s, name, default)
if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
    value = s.(name);
else
    value = default;
end
end

function value = summaryTemplate()
value = struct( ...
    'caseId', "", ...
    'status', "not_available", ...
    'passed', false, ...
    'simCompleted', false, ...
    'comparisonEligible', false, ...
    'failureCategory', "", ...
    'current_A', NaN, ...
    'voltage_V', NaN, ...
    'power_kW', NaN, ...
    'currentDensity_A_cm2', NaN, ...
    'powerDensity_kW_cm2', NaN, ...
    'targetCegrRatio', NaN, ...
    'actualCegrRatioMixBasis', NaN, ...
    'actualCegrRatioFreshBasis', NaN, ...
    'lambda', NaN, ...
    'oxygenPartialPressure_Pa', NaN, ...
    'cathodeInletRH', NaN, ...
    'stackTemperature_C', NaN, ...
    'stackTemperatureSet_C', NaN, ...
    'mixerCondensationRate_kg_s', NaN, ...
    'mixerSaturationRatio', NaN);
end
