function [caseCfg, adapter] = routeA_focused_case_adapter(inputCase, defaults)
% Normalize a focused case or standard Route A simCase.
%
% The focused model keeps the standard cathode/stack input contract while
% replacing the removed anode and thermal BOPs with explicit boundary values.
% This adapter is the only place where a full simCase is translated to the
% focused runner schema.

if nargin < 2 || ~isstruct(defaults) || ~isscalar(defaults)
    error('RouteA:FocusedAdapterDefaults', ...
        'Focused adapter defaults must be a scalar struct.');
end
if ~isstruct(inputCase) || ~isscalar(inputCase)
    error('RouteA:FocusedAdapterCase', ...
        'A focused case must be a scalar struct.');
end

if isfield(inputCase, 'controls')
    caseCfg = standardSimCaseToFocused(inputCase);
    adapter = struct( ...
        'schemaVersion', "RouteA_Focused_CaseAdapter_v01", ...
        'inputSchema', "RouteA_simCase", ...
        'status', "mapped", ...
        'initialStatePolicy', "cold_start_only");
else
    caseCfg = inputCase;
    adapter = struct( ...
        'schemaVersion', "RouteA_Focused_CaseAdapter_v01", ...
        'inputSchema', "RouteA_Focused_Case_v01", ...
        'status', "native_focused_case", ...
        'initialStatePolicy', "cold_start_only");
end

if ~isfield(caseCfg, 'caseId') || strlength(string(caseCfg.caseId)) == 0
    caseCfg.caseId = "focused_case";
end
if ~isfield(caseCfg, 'description') || isempty(caseCfg.description)
    caseCfg.description = "Focused cathode-cEGR case";
end

if isfield(inputCase, 'initialState') && isstruct(inputCase.initialState) && ...
        isfield(inputCase.initialState, 'mode') && ...
        string(inputCase.initialState.mode) ~= "cold"
    error('RouteA:FocusedInitialState', ...
        'The focused runner supports cold-start-only cases.');
end

[focused, bridge] = routeA_focused_parameter_bridge(caseCfg, defaults);
caseCfg.focused = focused;
caseCfg.focusedParameterBridge = bridge;
end

function caseCfg = standardSimCaseToFocused(simCase)
% Map the standard CR3 controls to the shared electrical-boundary adapter.

controls = simCase.controls;
if ~isfield(controls, 'electrical') || ...
        ~isfield(controls.electrical, 'mode') || ...
        ~isfield(controls.electrical, 'profile')
    error('RouteA:FocusedElectricalContract', ...
        'The standard simCase electrical contract is incomplete.');
end

caseCfg = struct();
caseCfg.caseId = string(getField(simCase, 'caseId', "focused_case"));
caseCfg.description = string(getField(simCase, 'description', ...
    "Focused case adapted from Route A simCase"));
caseCfg.boundary = struct( ...
    'type', string(controls.electrical.mode), ...
    'profile', controls.electrical.profile);

if isfield(controls.electrical, 'voltageController')
    caseCfg.controller = controls.electrical.voltageController;
end

if isfield(controls, 'cathode')
    cathode = controls.cathode;
    caseCfg.air = struct( ...
        'modeId', cathode.airControlMode, ...
        'targetOer', cathode.targetOer, ...
        'targetMdot_kg_s', cathode.targetMdot_kg_s, ...
        'directCommand', cathode.directCommand, ...
        'pid', cathode.airController);
    caseCfg.cathode = struct( ...
        'sourcePressure_MPa_abs', cathode.sourcePressure_MPa_abs, ...
        'sourceTemperature_C', cathode.sourceTemperature_C, ...
        'freshAirO2MoleFraction', cathode.o2MoleFraction, ...
        'freshAirWaterMoleFraction', cathode.h2oMoleFraction, ...
        'outletPressure_MPa_abs', cathode.outletPressure_MPa_abs, ...
        'humidifierRelativeHumidity', cathode.humidifierRH, ...
        'humidifierEnabled', cathode.humidifierEnabled);
end

if isfield(controls, 'cegr')
    caseCfg.cegr = controls.cegr;
    if ~isfield(caseCfg.cegr, 'profile')
        caseCfg.cegr.profile = caseCfg.cegr.targetRatio;
    end
end
if isfield(controls, 'anode')
    anode = controls.anode;
    caseCfg.anode = struct( ...
        'tankPressure_MPa_abs', anode.sourcePressure_MPa_abs, ...
        'sourceTemperature_C', anode.sourceTemperature_C, ...
        'hydrogenMoleFraction', anode.h2MoleFraction, ...
        'inletPressure_MPa_abs', anode.inletPressure_MPa_abs, ...
        'humidifierRelativeHumidity', anode.humidifierRH, ...
        'recirculationBaseCommand', anode.recirculationBaseCommand, ...
        'recirculationCurrentGain_A_inv', ...
            anode.recirculationCurrentGain_A_inv, ...
        'purgeEnabled', anode.purgeEnabled, ...
        'purgeOnN2MoleFraction', anode.purgeOnN2MoleFraction, ...
        'purgeOffN2MoleFraction', anode.purgeOffN2MoleFraction);
end
if isfield(controls, 'thermal')
    caseCfg.thermal = controls.thermal;
end
if isfield(controls, 'environment')
    caseCfg.environment = struct( ...
        'ambientTemperature_C', controls.environment.ambientTemperature_C, ...
        'ambientPressure_MPa_abs', controls.environment.ambientPressure_MPa_abs);
end
if isfield(controls, 'stack')
    caseCfg.stack = controls.stack;
end
if isfield(controls, 'devices')
    caseCfg.devices = controls.devices;
end
if isfield(simCase, 'acceptance')
    caseCfg.acceptance = simCase.acceptance;
end
if isfield(simCase, 'focused')
    caseCfg.focused = simCase.focused;
end
end

function value = getField(s, name, default)
if isfield(s, name) && ~isempty(s.(name))
    value = s.(name);
else
    value = default;
end
end
