function params = routeA_focused_parameter_defaults()
% Return defaults for the focused cathode-cEGR research model.
%
% Shared Route A platform values remain the source for stack, cathode,
% environment, and solver defaults. Focused-only boundary values are kept
% explicit so their applicability is visible in the focused study contract.

paths = routeA_focused_paths();
addpath(char(paths.sharedScriptDir));
platform = routeA_platform_default_parameters();

params = struct();
params.modelName = "PEMFuelCellSystem_Cathode_cEGR_Focused_v01";
params.sourceModelName = ...
    "PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01";
params.parameterLayer = "platform_default";

params.stack = struct( ...
    'temperature_C', 80, ...
    'temperatureSource', "focused_stack_temperature_C");

params.anode = struct( ...
    'feedPressure_MPa_abs', ...
        platform.controls.anode_source_pressure_MPa_abs.value, ...
    'inletMdot_kg_s', 0.001, ...
    'outletPressure_MPa_abs', ...
        platform.environment.ambient_p_MPa_abs.value, ...
    'boundaryTemperature_C', platform.environment.ambient_T_C.value, ...
    'hydrogenMoleFraction', platform.anode.tank.yH2.value, ...
    'pipeLength_m', 1, ...
    'pipeDiameter_m', 0.02, ...
    'pipeArea_m2', pi * 0.02^2 / 4, ...
    'pipeExtraLength_m', 0.1, ...
    'pipeRoughness_m', 15e-6);

params.interface = struct( ...
    'schemaVersion', "RouteA_Focused_ParameterBridge_v01", ...
    'anodeBoundary', "mass_flow_inlet_pressure_outlet", ...
    'thermalBoundary', "fixed_temperature_source", ...
    'standardAnodePressureMapping', ...
        "controls.anode.sourcePressure_MPa_abs -> focused_anode_feed_p_MPa_abs", ...
    'standardAnodeTemperatureMapping', ...
        "controls.anode.sourceTemperature_C -> focused_anode_boundary_T_C", ...
    'standardAnodeCompositionMapping', ...
        "controls.anode.h2MoleFraction -> focused_anode_yH2", ...
    'standardThermalMapping', ...
        "controls.thermal.stackTemperatureSet_C -> focused_stack_temperature_C", ...
    'notApplicablePolicy', ...
        "removed_BOP_parameters_are_reported_not_applied");

params.solver = struct( ...
    'solver', platform.numerics.solver.value, ...
    'relTol', platform.numerics.relTol.value, ...
    'absTol', platform.numerics.absTol.value, ...
    'maxStep_s', platform.numerics.maxStep_s.value, ...
    'stopTime_s', platform.numerics.stopTime_s.value);

params.environment = struct( ...
    'ambientTemperature_C', platform.environment.ambient_T_C.value, ...
    'ambientPressure_MPa_abs', platform.environment.ambient_p_MPa_abs.value);
end
