function caseCfg = routeA_focused_case_template()
% Return the focused-model case contract with platform defaults.

params = routeA_focused_parameter_defaults();
standard = routeA_simCase_template();
caseCfg = struct();
caseCfg.caseId = "focused_case";
caseCfg.description = "Focused cathode-cEGR case";
caseCfg.boundary = struct('type', "Current", 'profile', 100);
caseCfg.air = struct( ...
    'modeId', standard.controls.cathode.airControlMode, ...
    'targetOer', standard.controls.cathode.targetOer, ...
    'targetMdot_kg_s', standard.controls.cathode.targetMdot_kg_s, ...
    'directCommand', standard.controls.cathode.directCommand, ...
    'pid', standard.controls.cathode.airController);
caseCfg.cathode = struct( ...
    'sourcePressure_MPa_abs', standard.controls.cathode.sourcePressure_MPa_abs, ...
    'sourceTemperature_C', standard.controls.cathode.sourceTemperature_C, ...
    'freshAirO2MoleFraction', standard.controls.cathode.o2MoleFraction, ...
    'freshAirWaterMoleFraction', standard.controls.cathode.h2oMoleFraction, ...
    'outletPressure_MPa_abs', standard.controls.cathode.outletPressure_MPa_abs, ...
    'humidifierRelativeHumidity', standard.controls.cathode.humidifierRH, ...
    'humidifierEnabled', standard.controls.cathode.humidifierEnabled);
caseCfg.cegr = standard.controls.cegr;
caseCfg.cegr.enabled = true;
caseCfg.cegr.profile = caseCfg.cegr.targetRatio;
caseCfg.anode = struct( ...
    'tankPressure_MPa_abs', standard.controls.anode.sourcePressure_MPa_abs, ...
    'sourceTemperature_C', standard.controls.anode.sourceTemperature_C, ...
    'hydrogenMoleFraction', standard.controls.anode.h2MoleFraction, ...
    'inletPressure_MPa_abs', standard.controls.anode.inletPressure_MPa_abs, ...
    'humidifierRelativeHumidity', standard.controls.anode.humidifierRH, ...
    'recirculationBaseCommand', standard.controls.anode.recirculationBaseCommand, ...
    'recirculationCurrentGain_A_inv', ...
        standard.controls.anode.recirculationCurrentGain_A_inv, ...
    'purgeEnabled', standard.controls.anode.purgeEnabled, ...
    'purgeOnN2MoleFraction', standard.controls.anode.purgeOnN2MoleFraction, ...
    'purgeOffN2MoleFraction', standard.controls.anode.purgeOffN2MoleFraction);
caseCfg.thermal = standard.controls.thermal;
caseCfg.stack = standard.controls.stack;
caseCfg.devices = standard.controls.devices;
caseCfg.controller = standard.controls.electrical.voltageController;
caseCfg.environment = params.environment;
caseCfg.focused = struct( ...
    'stackTemperature_C', [], ...
    'anodeFeedPressure_MPa_abs', [], ...
    'anodeInletMdot_kg_s', params.anode.inletMdot_kg_s, ...
    'anodeOutletPressure_MPa_abs', ...
        params.anode.outletPressure_MPa_abs, ...
    'anodeBoundaryTemperature_C', [], ...
    'anodeHydrogenMoleFraction', [], ...
    'anodePipeLength_m', params.anode.pipeLength_m, ...
    'anodePipeDiameter_m', params.anode.pipeDiameter_m, ...
    'anodePipeArea_m2', params.anode.pipeArea_m2, ...
    'anodePipeExtraLength_m', params.anode.pipeExtraLength_m, ...
    'anodePipeRoughness_m', params.anode.pipeRoughness_m);
end
