function [focused, bridge] = routeA_focused_parameter_bridge(caseCfg, defaults)
% Map standard anode and thermal inputs to focused boundary variables.
%
% The focused model does not silently pretend that removed BOP parameters are
% active. Parameters that have a physical replacement are mapped to the
% replacement boundary; parameters with no equivalent remain explicit
% not_applicable entries in the returned bridge contract.

if ~isstruct(caseCfg) || ~isscalar(caseCfg)
    error('RouteA:FocusedBridgeCase', ...
        'caseCfg must be a scalar struct.');
end

focused = struct( ...
    'stackTemperature_C', defaults.stack.temperature_C, ...
    'anodeFeedPressure_MPa_abs', defaults.anode.feedPressure_MPa_abs, ...
    'anodeInletMdot_kg_s', defaults.anode.inletMdot_kg_s, ...
    'anodeOutletPressure_MPa_abs', defaults.anode.outletPressure_MPa_abs, ...
    'anodeBoundaryTemperature_C', defaults.anode.boundaryTemperature_C, ...
    'anodeHydrogenMoleFraction', defaults.anode.hydrogenMoleFraction, ...
    'anodePipeLength_m', defaults.anode.pipeLength_m, ...
    'anodePipeDiameter_m', defaults.anode.pipeDiameter_m, ...
    'anodePipeArea_m2', defaults.anode.pipeArea_m2, ...
    'anodePipeExtraLength_m', defaults.anode.pipeExtraLength_m, ...
    'anodePipeRoughness_m', defaults.anode.pipeRoughness_m);

mapping = repmat(mappingTemplate(), 0, 1);

[focused.stackTemperature_C, source] = selectValue(caseCfg, ...
    'stackTemperature_C', {{'thermal', 'stackTemperatureSet_C'}}, ...
    focused.stackTemperature_C, "platform_default");
mapping(end + 1) = mappedEntry('thermal.stackTemperatureSet_C', ...
    source, 'focused_stack_temperature_C', focused.stackTemperature_C, ...
    'degC', 'mapped');

[focused.anodeFeedPressure_MPa_abs, source] = selectValue(caseCfg, ...
    'anodeFeedPressure_MPa_abs', ...
    {{'anode', 'tankPressure_MPa_abs'}, ...
     {'anode', 'sourcePressure_MPa_abs'}}, ...
    focused.anodeFeedPressure_MPa_abs, "platform_default");
mapping(end + 1) = mappedEntry('anode.sourcePressure_MPa_abs', ...
    source, 'focused_anode_feed_p_MPa_abs', ...
    focused.anodeFeedPressure_MPa_abs, 'MPa(abs)', 'mapped');

[focused.anodeBoundaryTemperature_C, source] = selectValue(caseCfg, ...
    'anodeBoundaryTemperature_C', ...
    {{'anode', 'sourceTemperature_C'}}, ...
    focused.anodeBoundaryTemperature_C, "platform_default");
mapping(end + 1) = mappedEntry('anode.sourceTemperature_C', source, ...
    'focused_anode_boundary_T_C', focused.anodeBoundaryTemperature_C, ...
    'degC', 'mapped');

[focused.anodeHydrogenMoleFraction, source] = selectValue(caseCfg, ...
    'anodeHydrogenMoleFraction', ...
    {{'anode', 'hydrogenMoleFraction'}, ...
     {'anode', 'h2MoleFraction'}}, ...
    focused.anodeHydrogenMoleFraction, "platform_default");
mapping(end + 1) = mappedEntry('anode.h2MoleFraction', source, ...
    'focused_anode_yH2', focused.anodeHydrogenMoleFraction, '-', 'mapped');

[focused.anodeInletMdot_kg_s, source] = selectFocusedOnly(caseCfg, ...
    'anodeInletMdot_kg_s', focused.anodeInletMdot_kg_s, "platform_default");
mapping(end + 1) = mappedEntry('focused.anodeInletMdot_kg_s', source, ...
    'focused_anode_inlet_mdot_kg_s', focused.anodeInletMdot_kg_s, ...
    'kg/s', 'mapped');

[focused.anodeOutletPressure_MPa_abs, source] = selectFocusedOnly(caseCfg, ...
    'anodeOutletPressure_MPa_abs', focused.anodeOutletPressure_MPa_abs, ...
    "platform_default");
mapping(end + 1) = mappedEntry('focused.anodeOutletPressure_MPa_abs', ...
    source, 'focused_anode_outlet_p_MPa_abs', ...
    focused.anodeOutletPressure_MPa_abs, 'MPa(abs)', 'mapped');

[focused.anodePipeLength_m, source] = selectFocusedOnly(caseCfg, ...
    'anodePipeLength_m', focused.anodePipeLength_m, "platform_default");
mapping(end + 1) = mappedEntry('focused.anodePipeLength_m', source, ...
    'focused_anode_pipe_length', focused.anodePipeLength_m, 'm', 'mapped');

[focused.anodePipeDiameter_m, source] = selectFocusedOnly(caseCfg, ...
    'anodePipeDiameter_m', focused.anodePipeDiameter_m, "platform_default");
areaWasExplicit = hasFocusedField(caseCfg, 'anodePipeArea_m2');
if areaWasExplicit
    explicitArea = caseCfg.focused.anodePipeArea_m2;
    expectedArea = pi * focused.anodePipeDiameter_m^2 / 4;
    if ~isfinite(explicitArea) || explicitArea <= 0
        error('RouteA:FocusedAnodePipeArea', ...
            'focused.anodePipeArea_m2 must be positive and finite.');
    end
    if hasFocusedField(caseCfg, 'anodePipeDiameter_m') && ...
            abs(explicitArea - expectedArea) > max(1e-12, 1e-6 * expectedArea)
        error('RouteA:FocusedAnodePipeGeometry', ...
            'Focused anode pipe diameter and area are inconsistent.');
    end
    focused.anodePipeArea_m2 = explicitArea;
    areaSource = "focused.anodePipeArea_m2 (checked)";
else
    focused.anodePipeArea_m2 = pi * focused.anodePipeDiameter_m^2 / 4;
    areaSource = "derived_from_focused.anodePipeDiameter_m";
end
mapping(end + 1) = mappedEntry('focused.anodePipeDiameter_m', source, ...
    'focused_anode_pipe_area', focused.anodePipeArea_m2, 'm^2', 'derived');
mapping(end).reason = areaSource;

[focused.anodePipeExtraLength_m, source] = selectFocusedOnly(caseCfg, ...
    'anodePipeExtraLength_m', focused.anodePipeExtraLength_m, ...
    "platform_default");
mapping(end + 1) = mappedEntry('focused.anodePipeExtraLength_m', source, ...
    'focused_anode_pipe_extra_length', focused.anodePipeExtraLength_m, ...
    'm', 'mapped');

[focused.anodePipeRoughness_m, source] = selectFocusedOnly(caseCfg, ...
    'anodePipeRoughness_m', focused.anodePipeRoughness_m, ...
    "platform_default");
mapping(end + 1) = mappedEntry('focused.anodePipeRoughness_m', source, ...
    'focused_anode_pipe_roughness', focused.anodePipeRoughness_m, ...
    'm', 'mapped');

mapping = addNotApplicable(mapping, caseCfg, 'anode.inletPressure_MPa_abs', ...
    'mass_flow_source_boundary', ...
    'The focused anode inlet is set by mass flow, not inlet pressure.');
mapping = addNotApplicable(mapping, caseCfg, 'anode.humidifierRH', ...
    'removed_anode_BOP', ...
    'The focused boundary has no anode humidifier.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'anode.recirculationBaseCommand', 'removed_anode_BOP', ...
    'The focused boundary has no anode recirculation loop.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'anode.recirculationCurrentGain_A_inv', 'removed_anode_BOP', ...
    'The focused boundary has no anode recirculation loop.');
mapping = addNotApplicable(mapping, caseCfg, 'anode.purgeEnabled', ...
    'removed_anode_BOP', ...
    'The focused boundary has no anode purge valve.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'anode.purgeOnN2MoleFraction', 'removed_anode_BOP', ...
    'The focused boundary has no anode purge valve.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'anode.purgeOffN2MoleFraction', 'removed_anode_BOP', ...
    'The focused boundary has no anode purge valve.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'devices.thermal.coolantGeometry', 'removed_thermal_BOP', ...
    'The focused temperature boundary does not contain coolant channels.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'devices.thermal.radiatorCore', 'removed_thermal_BOP', ...
    'The focused temperature boundary does not contain a radiator.');

validateFocusedValues(focused);

bridge = struct( ...
    'schemaVersion', "RouteA_Focused_ParameterBridge_v01", ...
    'status', "mapped_with_explicit_fixed_boundaries", ...
    'modelWritePoints', [ ...
        "focused_stack_temperature_C", ...
        "focused_anode_feed_p_MPa_abs", ...
        "focused_anode_inlet_mdot_kg_s", ...
        "focused_anode_outlet_p_MPa_abs", ...
        "focused_anode_boundary_T_C", ...
        "focused_anode_yH2", ...
        "focused_anode_pipe_length", ...
        "focused_anode_pipe_area", ...
        "focused_anode_pipe_extra_length", ...
        "focused_anode_pipe_roughness"], ...
    'mapping', mapping, ...
    'removedSubsystemPolicy', ...
        "accepted_standard_fields_are_reported_not_applicable_when_no_physical_replacement_exists", ...
    'engineeringUse', ...
        "fixed_anode_and_temperature_boundary_only;_not_a_full_BOP_result");
end

function [value, source] = selectValue(caseCfg, focusedName, standardPaths, default, defaultSource)
if hasFocusedField(caseCfg, focusedName)
    value = caseCfg.focused.(focusedName);
    source = "focused." + string(focusedName);
else
    value = default;
    source = defaultSource;
    for idx = 1:numel(standardPaths)
        standardPath = standardPaths{idx};
        if hasNestedField(caseCfg, standardPath)
            value = getNestedField(caseCfg, standardPath);
            source = string(standardPath{1}) + "." + string(standardPath{2});
            break;
        end
    end
end
end

function [value, source] = selectFocusedOnly(caseCfg, fieldName, default, defaultSource)
if hasFocusedField(caseCfg, fieldName)
    value = caseCfg.focused.(fieldName);
    source = "focused." + string(fieldName);
else
    value = default;
    source = defaultSource;
end
end

function present = hasFocusedField(caseCfg, fieldName)
present = isfield(caseCfg, 'focused') && isstruct(caseCfg.focused) && ...
    isfield(caseCfg.focused, fieldName) && ~isempty(caseCfg.focused.(fieldName));
end

function present = hasNestedField(s, path)
present = isfield(s, path{1}) && isstruct(s.(path{1})) && ...
    isfield(s.(path{1}), path{2}) && ~isempty(s.(path{1}).(path{2}));
end

function value = getNestedField(s, path)
value = s.(path{1}).(path{2});
end

function mapping = addNotApplicable(mapping, caseCfg, canonicalName, reason, text)
entry = mappedEntry(canonicalName, "case field if supplied", "", NaN, ...
    "", "not_applicable");
entry.reason = string(text);
entry.sourcePresent = hasCanonicalField(caseCfg, canonicalName);
entry.targetVariable = string(reason);
mapping(end + 1) = entry;
end

function present = hasCanonicalField(caseCfg, canonicalName)
parts = split(string(canonicalName), '.');
if string(canonicalName) == "anode.humidifierRH"
    canonicalName = "anode.humidifierRelativeHumidity";
    parts = split(canonicalName, '.');
end
value = caseCfg;
for idx = 1:numel(parts)
    if ~isstruct(value) || ~isfield(value, char(parts(idx)))
        present = false;
        return;
    end
    value = value.(char(parts(idx)));
end
present = ~isempty(value);
end

function entry = mappedEntry(canonicalName, sourcePath, targetVariable, value, unit, status)
entry = mappingTemplate();
entry.canonicalName = string(canonicalName);
entry.sourcePath = string(sourcePath);
entry.targetVariable = string(targetVariable);
entry.value = value;
entry.unit = string(unit);
entry.status = string(status);
entry.reason = "";
entry.sourcePresent = false;
end

function entry = mappingTemplate()
entry = struct( ...
    'canonicalName', "", ...
    'sourcePath', "", ...
    'targetVariable', "", ...
    'value', NaN, ...
    'unit', "", ...
    'status', "", ...
    'reason', "", ...
    'sourcePresent', false);
end

function validateFocusedValues(focused)
validateRange(focused.stackTemperature_C, [60, 100], ...
    'focused.stackTemperature_C');
validateRange(focused.anodeFeedPressure_MPa_abs, [0.2, 1], ...
    'focused.anodeFeedPressure_MPa_abs');
validateRange(focused.anodeInletMdot_kg_s, [eps, 1], ...
    'focused.anodeInletMdot_kg_s');
validateRange(focused.anodeOutletPressure_MPa_abs, [0.01, 1], ...
    'focused.anodeOutletPressure_MPa_abs');
validateRange(focused.anodeBoundaryTemperature_C, [-50, 150], ...
    'focused.anodeBoundaryTemperature_C');
validateRange(focused.anodeHydrogenMoleFraction, [0.9, 1], ...
    'focused.anodeHydrogenMoleFraction');
validateRange(focused.anodePipeLength_m, [1e-4, 100], ...
    'focused.anodePipeLength_m');
validateRange(focused.anodePipeDiameter_m, [1e-4, 1], ...
    'focused.anodePipeDiameter_m');
validateRange(focused.anodePipeArea_m2, [1e-8, 1], ...
    'focused.anodePipeArea_m2');
validateRange(focused.anodePipeExtraLength_m, [0, 100], ...
    'focused.anodePipeExtraLength_m');
validateRange(focused.anodePipeRoughness_m, [0, 0.01], ...
    'focused.anodePipeRoughness_m');
end

function validateRange(value, bounds, name)
validateattributes(value, {'numeric'}, {'scalar', 'real', 'finite'}, ...
    'RouteA:FocusedBoundaryValue', name);
if value < bounds(1) || value > bounds(2)
    error('RouteA:FocusedBoundaryRange', ...
        '%s must be within [%.6g, %.6g].', name, bounds(1), bounds(2));
end
end
