function tuning = run_routeA_stage1_voltage_pi_tuning(tuningCfg)
% Select the first bounded PI pair that closes the nominal zero-cEGR case.
%
% Candidates are evaluated in explicitly ordered conservative-to-stronger
% sequence. Each candidate uses the formal Voltage initial state, mode 1,
% zero cEGR, OER=3, 600 s, tail [540,600), and MaxStep=5 s. The shared
% water ledger is intentionally disabled here because this is a controller
% selection run, not the formal cEGR matrix.

if nargin < 1 || isempty(tuningCfg)
    tuningCfg = struct();
end
cfg = normalizeTuningConfig(tuningCfg);
records = repmat(emptyRecord(), size(cfg.gainCandidates, 1), 1);
selectedIndex = NaN;

for idx = 1:size(cfg.gainCandidates, 1)
    gains = cfg.gainCandidates(idx, :);
    studyCfg = struct( ...
        'targetVoltage_V', cfg.targetVoltage_V, ...
        'targetAirEquivalentOer', cfg.targetAirEquivalentOer, ...
        'researchDuration_s', 600, ...
        'tailLogicalWindow_s', [540, 600], ...
        'studyMaxStep_s', 5, ...
        'targetRatios', 0, ...
        'piKp_A_V', gains(1), ...
        'piKi_A_V_s', gains(2), ...
        'runWaterLedger', false);
    study = run_routeA_stage1_constant_voltage_cegr_matrix(studyCfg);
    result = study.cases(1);
    records(idx) = collectRecord(gains, result);
    if records(idx).accepted
        selectedIndex = idx;
        break;
    end
end

tuning = struct();
tuning.timestamp = string(datetime('now', 'Format', ...
    'yyyy-MM-dd HH:mm:ss'));
tuning.targetVoltage_V = cfg.targetVoltage_V;
tuning.targetAirEquivalentOer = cfg.targetAirEquivalentOer;
tuning.gainCandidates = cfg.gainCandidates;
tuning.records = records(1:max(1, findLastRecord(records)));
tuning.selectedIndex = selectedIndex;
tuning.passed = isfinite(selectedIndex);
if tuning.passed
    selected = records(selectedIndex);
    tuning.selected = struct( ...
        'Kp_A_V', selected.Kp_A_V, ...
        'Ki_A_V_s', selected.Ki_A_V_s, ...
        'selectionRule', ...
        "first_passing_pair_in_declared_low_to_high_scan_order", ...
        'tailVoltageMeanRelativeError', ...
        selected.voltageTailMeanRelativeError, ...
        'tailVoltageSpan_V', selected.voltageTailSpan_V, ...
        'tailSaturationFraction', selected.saturationTailFraction);
else
    tuning.selected = struct();
end
tuning.summaryTable = buildSummaryTable(tuning.records);
assignin('base', 'routeA_stage1_voltage_pi_tuning', tuning);
displayTuning(tuning);
if ~tuning.passed
    error('RouteA:VoltagePITuningNoCandidate', ...
        'No configured PI pair passed the constant-voltage controller gates.');
end
end

function cfg = normalizeTuningConfig(tuningCfg)
if ~isstruct(tuningCfg) || numel(tuningCfg) ~= 1
    error('RouteA:VoltagePITuningConfig', ...
        'The tuning configuration must be a scalar struct.');
end
cfg = struct( ...
    'targetVoltage_V', 394.9, ...
    'targetAirEquivalentOer', 3, ...
    'gainCandidates', [ ...
        1.00, 0.02; ...
        1.00, 0.05; ...
        1.00, 0.10; ...
        2.00, 0.02; ...
        2.00, 0.05; ...
        3.00, 0.05]);
names = fieldnames(tuningCfg);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(cfg, name)
        error('RouteA:VoltagePITuningConfigField', ...
            'Unsupported tuning configuration field: %s.', name);
    end
    cfg.(name) = tuningCfg.(name);
end
validateattributes(cfg.targetVoltage_V, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(cfg.targetAirEquivalentOer, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(cfg.gainCandidates, {'numeric'}, ...
    {'2d', 'ncols', 2, 'nonempty', 'positive', 'finite'});
end

function record = collectRecord(gains, result)
record = emptyRecord();
record.Kp_A_V = gains(1);
record.Ki_A_V_s = gains(2);
record.simCompleted = result.simCompleted;
record.voltageControlPassed = result.voltageControlPassed;
record.voltageTailMeanRelativeError = result.voltageTailMeanRelativeError;
record.voltageTailSpan_V = tailSpan(result, 'stackVoltage_V');
record.saturationTailFraction = result.currentSaturationTailFraction;
record.tailVoltage_V = tailMean(result, 'stackVoltage_V');
record.tailCurrent_A = tailMean(result, 'stackCurrent_A');
record.failureCategory = result.failureCategory;
record.accepted = result.simCompleted && result.finiteTail && ...
    result.voltageControlPassed;
end

function record = emptyRecord()
record = struct( ...
    'Kp_A_V', NaN, ...
    'Ki_A_V_s', NaN, ...
    'simCompleted', false, ...
    'voltageControlPassed', false, ...
    'voltageTailMeanRelativeError', Inf, ...
    'voltageTailSpan_V', Inf, ...
    'saturationTailFraction', Inf, ...
    'tailVoltage_V', NaN, ...
    'tailCurrent_A', NaN, ...
    'failureCategory', "", ...
    'accepted', false);
end

function index = findLastRecord(records)
index = find(isfinite([records.Kp_A_V]), 1, 'last');
if isempty(index)
    index = 1;
end
end

function summary = buildSummaryTable(records)
summary = table([records.Kp_A_V].', [records.Ki_A_V_s].', ...
    [records.tailVoltage_V].', [records.tailCurrent_A].', ...
    [records.voltageTailMeanRelativeError].', ...
    [records.voltageTailSpan_V].', [records.saturationTailFraction].', ...
    [records.voltageControlPassed].', string({records.failureCategory}).', ...
    [records.accepted].', 'VariableNames', {'Kp_A_V', 'Ki_A_V_s', ...
    'tailVoltage_V', 'tailCurrent_A', 'tailVoltageMeanRelativeError', ...
    'tailVoltageSpan_V', 'tailSaturationFraction', ...
    'voltageControlPassed', 'failureCategory', 'accepted'});
end

function value = tailMean(result, name)
value = NaN;
if isfield(result, 'tail') && isfield(result.tail, name)
    value = result.tail.(name).mean;
end
end

function value = tailSpan(result, name)
value = Inf;
if isfield(result, 'tail') && isfield(result.tail, name)
    value = result.tail.(name).span;
end
end

function displayTuning(tuning)
fprintf('\nRoute A constant-voltage PI tuning\n');
fprintf('  V_ref=%.6g V | OER=%.6g | tested=%d | selected=%d\n', ...
    tuning.targetVoltage_V, tuning.targetAirEquivalentOer, ...
    numel(tuning.records), tuning.passed);
disp(tuning.summaryTable);
end
