function metadata = routeA_promote_platform_default_initial_state_bundle(modelDir)
% Atomically replace all Electrical Load operating-point variants together.
%
% A structural change below Electrical Load invalidates every saved
% ModelOperatingPoint, including inactive load branches. This promoter only
% accepts three freshly generated mode-1 candidates and never combines one
% new state with older Current, Power, or Voltage states.

if nargin < 1 || strlength(string(modelDir)) == 0
    scriptDir = fileparts(mfilename('fullpath'));
    modelDir = fullfile(scriptDir, '..', '..', '01_模型', ...
        'RouteA_v2_GasMixture_Derived');
end
modelDir = char(modelDir);
[modelDirExists, modelDirAttributes] = fileattrib(modelDir);
if ~modelDirExists || ~modelDirAttributes.directory
    error('RouteA:InitialStateBundlePromotionModelDir', ...
        'The Route A model directory is unavailable: %s.', modelDir);
end
modelDir = modelDirAttributes.Name;

files = struct();
files.current = fullfile(modelDir, ...
    'RouteA_v2_platform_default_initial_state_candidate_mode1_current.mat');
files.power = fullfile(modelDir, ...
    'RouteA_v2_platform_default_initial_state_candidate_mode1_power.mat');
files.voltage = fullfile(modelDir, ...
    'RouteA_v2_platform_default_initial_state_candidate_mode1_voltage.mat');
files.formal = fullfile(modelDir, ...
    'RouteA_v2_platform_default_initial_state.mat');
files.next = fullfile(modelDir, ...
    'RouteA_v2_platform_default_initial_state_next.mat');
files.backup = fullfile(modelDir, ...
    'RouteA_v2_platform_default_initial_state_pre_promotion_backup.mat');

requiredFiles = {files.current, files.power, files.voltage};
if ~builtin('all', cellfun(@isfile, requiredFiles))
    error('RouteA:InitialStateBundlePromotionInput', ...
        'Fresh Current, Power, and Voltage candidates are all required.');
end
if isfile(files.next) || isfile(files.backup)
    error('RouteA:InitialStateBundlePromotionRecoveryRequired', ...
        'Resolve an existing initial-state promotion recovery file first.');
end

current = loadCandidate(files.current, "Current");
power = loadCandidate(files.power, "Power");
voltage = loadCandidate(files.voltage, "Voltage");
validateCommonMetadata(current.metadata, power.metadata, voltage.metadata);
promotionTime = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

routeA_initial_state_current = current.state;
routeA_initial_metadata_current = current.metadata;
routeA_initial_metadata_current.loadInputType = "Current";
routeA_initial_metadata_current.availableLoadInputTypes = ...
    ["Current", "Power", "Voltage"];
routeA_initial_metadata_current.temporary = false;
routeA_initial_metadata_current.promotedAt = promotionTime;
routeA_initial_state_power = power.state;
routeA_initial_metadata_power = power.metadata;
routeA_initial_metadata_power.availableLoadInputTypes = ...
    routeA_initial_metadata_current.availableLoadInputTypes;
routeA_initial_metadata_power.temporary = false;
routeA_initial_metadata_power.promotedAt = promotionTime;
routeA_initial_state_voltage = voltage.state;
routeA_initial_metadata_voltage = voltage.metadata;
routeA_initial_metadata_voltage.availableLoadInputTypes = ...
    routeA_initial_metadata_current.availableLoadInputTypes;
routeA_initial_metadata_voltage.temporary = false;
routeA_initial_metadata_voltage.promotedAt = promotionTime;

save(files.next, 'routeA_initial_state_current', ...
    'routeA_initial_metadata_current', 'routeA_initial_state_power', ...
    'routeA_initial_metadata_power', ...
    'routeA_initial_state_voltage', ...
    'routeA_initial_metadata_voltage', '-v7.3');
validateBundleRoundTrip(files.next);

hadFormal = isfile(files.formal);
if hadFormal
    [movedFormal, formalMessage] = movefile(files.formal, files.backup, 'f');
    if ~movedFormal
        delete(files.next);
        error('RouteA:InitialStateBundlePromotionBackup', ...
            'Could not stage the existing formal file: %s.', formalMessage);
    end
end
[movedNext, nextMessage] = movefile(files.next, files.formal, 'f');
if ~movedNext
    if hadFormal && isfile(files.backup)
        movefile(files.backup, files.formal, 'f');
    end
    error('RouteA:InitialStateBundlePromotionMove', ...
        'Could not promote the initial-state bundle: %s.', nextMessage);
end
if hadFormal && isfile(files.backup)
    metadataArchive = archiveSupersededFormal(files.backup, modelDir);
else
    metadataArchive = "";
end
routeA_initial_metadata_current.supersededFormalArchive = metadataArchive;
routeA_initial_metadata_power.supersededFormalArchive = metadataArchive;
routeA_initial_metadata_voltage.supersededFormalArchive = metadataArchive;
save(files.formal, 'routeA_initial_metadata_current', ...
    'routeA_initial_metadata_power', 'routeA_initial_metadata_voltage', ...
    '-append');
delete(files.current);
delete(files.power);
delete(files.voltage);

metadata = routeA_initial_metadata_current;
metadata.supersededFormalArchive = metadataArchive;
assignin('base', 'routeA_platform_default_initial_metadata', metadata);
fprintf('Promoted Route A Current, Power, and Voltage initial states: %s\n', ...
    files.formal);
end

function archiveFile = archiveSupersededFormal(backupFile, modelDir)
projectRoot = fileparts(fileparts(fileparts(modelDir)));
archiveDir = fullfile(projectRoot, '99_历史归档', ...
    '2026-07-22_Stage1_InitialState_Superseded');
if ~isfolder(archiveDir)
    mkdir(archiveDir);
end
stamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
archiveFile = fullfile(archiveDir, ...
    ['RouteA_v2_platform_default_initial_state_pre_promotion_' stamp '.mat']);
[archived, archiveMessage] = movefile(backupFile, archiveFile, 'f');
if ~archived
    error('RouteA:InitialStateBundlePromotionArchive', ...
        ['The new formal state was promoted, but the superseded formal ', ...
        'state could not be archived: %s. The recovery file remains at %s.'], ...
        archiveMessage, backupFile);
end
end

function candidate = loadCandidate(file, expectedLoadInputType)
loaded = load(file, 'routeA_initial_state', 'routeA_initial_metadata');
if ~isfield(loaded, 'routeA_initial_state') || ...
        ~isfield(loaded, 'routeA_initial_metadata') || ...
        ~isa(loaded.routeA_initial_state, 'Simulink.op.ModelOperatingPoint')
    error('RouteA:InitialStateBundlePromotionState', ...
        'Candidate %s does not contain a valid ModelOperatingPoint.', file);
end
metadata = loaded.routeA_initial_metadata;
required = {'model', 'loadInputType', 'snapshotTimeS', ...
    'cegrTopologyEnabled', 'cegrValveModeId', 'egrReferenceKind', ...
    'cegrValveMaxArea_m2', 'periodicVerification', ...
    'initializationCondition', 'solver', 'physicalSummary', ...
    'commandProfileSchema', 'commandProfileFields', ...
    'commandProfileBaseline', 'baselineElectricalCommand', ...
    'sourceConditionerState', 'modelVersion'};
if ~builtin('all', isfield(metadata, required)) || ...
        string(metadata.loadInputType) ~= expectedLoadInputType || ...
        ~metadata.cegrTopologyEnabled || metadata.cegrValveModeId ~= 1 || ...
        string(metadata.egrReferenceKind) ~= "mode1_zero_target_near_zero"
    error('RouteA:InitialStateBundlePromotionMetadata', ...
        'Candidate %s is not the required %s mode-1 zero-cEGR state.', ...
        file, expectedLoadInputType);
end
if ~isfield(metadata, 'schema') || ...
        ~contains(string(metadata.schema), "_v10_") || ...
        string(metadata.commandProfileSchema) ~= "RouteA_Command_Profile_v10" || ...
        numel(metadata.commandProfileFields) ~= 22 || ...
        ~isnumeric(metadata.commandProfileBaseline) || ...
        ~isequal(size(metadata.commandProfileBaseline), [1, 22]) || ...
        any(~isfinite(metadata.commandProfileBaseline)) || ...
        ~isfield(metadata.periodicVerification, 'passed') || ...
        ~metadata.periodicVerification.passed || ...
        ~isfield(metadata.periodicVerification, 'quietWindowPurgeFree') || ...
        ~metadata.periodicVerification.quietWindowPurgeFree || ...
        ~isfield(metadata.periodicVerification, 'maximumRelativeChange') || ...
        metadata.periodicVerification.maximumRelativeChange > 0.005
    error('RouteA:InitialStateBundlePromotionQuietWindow', ...
        ['Candidate %s lacks a compliant v10 repeated post-purge quiet ', ...
        'window verification.'], file);
end
candidate = struct('state', loaded.routeA_initial_state, ...
    'metadata', metadata);
end

function validateCommonMetadata(step, drive, voltage)
models = [string(step.model), string(drive.model), string(voltage.model)];
if ~builtin('all', models == models(1))
    error('RouteA:InitialStateBundlePromotionModel', ...
        'The three initial-state candidates belong to different models.');
end
areas = [step.cegrValveMaxArea_m2, drive.cegrValveMaxArea_m2, ...
    voltage.cegrValveMaxArea_m2];
if max(abs(areas - areas(1))) > 1e-12 * max(1, abs(areas(1)))
    error('RouteA:InitialStateBundlePromotionParameter', ...
        'The three initial-state candidates use different cEGR valve areas.');
end
conditioners = {step.sourceConditionerState, drive.sourceConditionerState, ...
    voltage.sourceConditionerState};
if ~isequal(conditioners{1}, conditioners{2}) || ...
        ~isequal(conditioners{1}, conditioners{3})
    error('RouteA:InitialStateBundlePromotionSourceConditioner', ...
        'The three candidates use different source-conditioner physical states.');
end
end

function validateBundleRoundTrip(file)
loaded = load(file, 'routeA_initial_state_current', ...
    'routeA_initial_state_power', 'routeA_initial_state_voltage', ...
    'routeA_initial_metadata_current', 'routeA_initial_metadata_power', ...
    'routeA_initial_metadata_voltage');
if ~isa(loaded.routeA_initial_state_current, ...
        'Simulink.op.ModelOperatingPoint') || ...
        ~isa(loaded.routeA_initial_state_power, ...
        'Simulink.op.ModelOperatingPoint') || ...
        ~isa(loaded.routeA_initial_state_voltage, ...
        'Simulink.op.ModelOperatingPoint')
    error('RouteA:InitialStateBundlePromotionWrite', ...
        'The composed initial-state bundle did not round-trip correctly.');
end
expected = ["Current", "Power", "Voltage"];
actual = [string(loaded.routeA_initial_metadata_current.loadInputType), ...
    string(loaded.routeA_initial_metadata_power.loadInputType), ...
    string(loaded.routeA_initial_metadata_voltage.loadInputType)];
if ~builtin('all', actual == expected)
    error('RouteA:InitialStateBundlePromotionMode', ...
        'The composed bundle does not preserve the three load variants.');
end
metadata = {loaded.routeA_initial_metadata_current, ...
    loaded.routeA_initial_metadata_power, ...
    loaded.routeA_initial_metadata_voltage};
isFormal = cellfun(@(item) isfield(item, 'temporary') && ...
    ~item.temporary, metadata);
if ~builtin('all', isFormal)
    error('RouteA:InitialStateBundlePromotionFormalMetadata', ...
        'The promoted bundle still contains a temporary initial state.');
end
end
