%% Route A A9 50 kW platform parameter-governance audit
% Main A9 entry for the current Route A 50 kW platform.
% The audit is intentionally read-back driven: no SLX save, no default
% parameter changes, no external bench workbook/CSV/DQ60 data.

model = 'PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01';
scriptDir = fileparts(mfilename('fullpath'));
modelDir = fullfile(scriptDir, '..', '..', '01_模型', 'RouteA_GasMixture_Derived');
modelFile = fullfile(modelDir, [model '.slx']);
oldDir = pwd;
addpath(scriptDir);
cd(modelDir);
routeA_a9_cleanup = onCleanup(@() restoreFolderAndModel(oldDir, model, modelFile));

if bdIsLoaded(model) && strcmp(get_param(model, 'Dirty'), 'on')
    error('RouteA:A9:DirtyModel', ...
        ['Model %s has unsaved changes. Save or discard them before ', ...
        'running the A9 parameter-governance audit.'], model);
end

resetModelFromDisk(model, modelFile);
refreshModelWorkspace(model);

audit = struct();
audit.model = string(model);
audit.timestamp = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
audit.parameterIsolation = auditParameterIsolation(model, modelDir);
audit.formulaEnvelope = auditFormulaEnvelope(model);
audit.governance = auditParameterGovernance(model);
audit.a8Regression = runA8Regression(model, modelFile);
audit.nominalSteady = runNominal50kWSteady(model, modelFile, ...
    audit.formulaEnvelope.nominal50kW);
audit.maxCegrAreaSanity = runMaxCegrAreaSanity(model, modelFile, ...
    audit.formulaEnvelope.nominal50kW);
audit.a9SecondRound = auditA9SecondRound(audit);
audit.passed = audit.parameterIsolation.passed && ...
    audit.formulaEnvelope.passed && ...
    audit.governance.passed && ...
    audit.a8Regression.passed && ...
    audit.nominalSteady.passed && ...
    audit.nominalSteady.pressureChainOk && ...
    audit.nominalSteady.kpiFiniteOk && ...
    audit.nominalSteady.kpiNonnegativeOk && ...
    audit.maxCegrAreaSanity.passed && ...
    audit.maxCegrAreaSanity.pressureChainOk && ...
    audit.maxCegrAreaSanity.kpiFiniteOk && ...
    audit.a9SecondRound.passed;

assignin('base', 'routeA_a9_parameter_governance_audit', audit);
dispAudit(audit);

function result = auditParameterIsolation(model, modelDir)
mw = get_param(model, 'ModelWorkspace');
parameterFile = fullfile(modelDir, ...
    'PEMFuelCellSystemWithACustomLibraryParameters.m');
txt = string(fileread(parameterFile));

result = struct();
result.parameterFile = string(parameterFile);
result.layer = string(getWorkspaceValue(mw, 'routeA_parameter_layer', ""));
result.externalCaseEnabled = logical(getWorkspaceValue(mw, ...
    'routeA_external_case_enabled', true));
result.defaultScriptReadsTables = contains(txt, "readtable(") || ...
    contains(txt, ".csv") || contains(txt, ".xlsx") || ...
    contains(txt, ".xls");
result.defaultScriptReadsOldBench = contains(txt, ...
    "combined_noegr_cegr_fit_points.csv") || ...
    contains(txt, "simplified_") || contains(txt, "init_testbench_10kw");
result.layerOk = result.layer == "platform_default";
result.externalCaseFlagOk = ~result.externalCaseEnabled;
result.noDefaultFileDataLoad = ~result.defaultScriptReadsTables && ...
    ~result.defaultScriptReadsOldBench;
result.externalCaseGuard = auditExternalCaseGuard(model);
result.passed = result.layerOk && result.externalCaseFlagOk && ...
    result.noDefaultFileDataLoad && result.externalCaseGuard.passed;
end

function result = auditExternalCaseGuard(model)
result = struct();
result.disabledByDefault = false;
result.errorId = "";
result.errorMessage = "";
try
    run('run_routeA_a7_bench_sanity.m');
    result.errorId = "NO_ERROR";
    result.errorMessage = "external_case script did not reject default run";
catch ME
    result.errorId = string(ME.identifier);
    result.errorMessage = firstLine(string(ME.message));
    result.disabledByDefault = result.errorId == "RouteA:ExternalCase:Disabled";
end
resetModelFromDisk(model, [model '.slx']);
refreshModelWorkspace(model);
result.passed = result.disabledByDefault;
end

function result = auditFormulaEnvelope(model)
mw = get_param(model, 'ModelWorkspace');
params = readFormulaParameters(mw);
cases = [ ...
    envelopeCase("low_load_cegr", 0.20, 0.78), ...
    envelopeCase("nominal_50kW", 0.70, 0.65), ...
    envelopeCase("high_power_envelope", 1.20, 0.58)];

for k = 1:numel(cases)
    cases(k) = computeEnvelopeCase(cases(k), params);
end

result = struct();
result.parameters = params;
result.cases = cases;
result.lowLoadCegr = cases(1);
result.nominal50kW = cases(2);
result.highPowerEnvelope = cases(3);
result.nominalPowerOk = cases(2).powerKW >= 45 && cases(2).powerKW <= 60;
result.highPowerMarginOk = cases(3).compressorMargin >= 2;
result.nominalAirMarginOk = cases(2).compressorMargin >= 2;
result.pressureDropFiniteOk = all(isfinite([ ...
    cases.intercoolerDpKPa, cases.cathodeSeparatorDpKPa, ...
    cases.anodeSeparatorDpKPa]));
result.finiteOk = all(isfinite([ ...
    cases.powerKW, cases.h2KgS, cases.o2KgS, cases.waterKgS, ...
    cases.airKgS, cases.heatRejectKW, cases.cathodeVelocityMS, ...
    cases.anodeHydrogenVelocityMS, cases.compressorMargin]));
result.a9SecondRoundThresholds = struct( ...
    'maxNominalAnodeHydrogenVelocityMS', 40, ...
    'minNominalCathodeSeparatorFlowMargin', 1.5, ...
    'minHighPowerCathodeSeparatorFlowMargin', 1.0, ...
    'maxCegrValveToPipeArea', 0.05);
result.nominalAnodeVelocityOk = cases(2).anodeHydrogenVelocityMS < ...
    result.a9SecondRoundThresholds.maxNominalAnodeHydrogenVelocityMS;
result.nominalCathodeSeparatorMarginOk = ...
    cases(2).cathodeSeparatorFlowMargin >= ...
    result.a9SecondRoundThresholds.minNominalCathodeSeparatorFlowMargin;
result.highPowerCathodeSeparatorMarginOk = ...
    cases(3).cathodeSeparatorFlowMargin >= ...
    result.a9SecondRoundThresholds.minHighPowerCathodeSeparatorFlowMargin;
result.cegrMaxValveFractionOk = params.cegrMaxValveToPipeArea <= ...
    result.a9SecondRoundThresholds.maxCegrValveToPipeArea && ...
    params.cegrMaxValveToPipeArea > params.cegrLowValveToPipeArea;
result.warnings = strings(0, 1);
if cases(2).anodeHydrogenVelocityMS > 100
    result.warnings(end + 1, 1) = "anode_tube_velocity_high_at_nominal";
end
if cases(2).cathodeSeparatorFlowMargin < 1.2
    result.warnings(end + 1, 1) = "cathode_separator_nominal_flow_close_to_air_demand";
end
if params.cegrMaxValveToPipeArea > 0.5
    result.warnings(end + 1, 1) = "cegr_max_valve_area_is_broad_upper_bound";
end
result.passed = result.nominalPowerOk && result.highPowerMarginOk && ...
    result.nominalAirMarginOk && result.pressureDropFiniteOk && ...
    result.finiteOk && result.nominalAnodeVelocityOk && ...
    result.nominalCathodeSeparatorMarginOk && ...
    result.highPowerCathodeSeparatorMarginOk && ...
    result.cegrMaxValveFractionOk;
end

function params = readFormulaParameters(mw)
params = struct();
params.stackNumCells = getWorkspaceValue(mw, 'stack_num_cells', NaN);
params.stackAreaCm2 = getWorkspaceValue(mw, 'stack_area', NaN);
params.stackIL = getWorkspaceValue(mw, 'stack_iL', NaN);
params.cathodeTubeD = getWorkspaceValue(mw, 'cathode_tube_D', NaN);
params.anodeTubeD = getWorkspaceValue(mw, 'anode_tube_D', NaN);
params.cegrPipeArea = getWorkspaceValue(mw, 'cegr_pipe_area', NaN);
params.cegrValveAreaClosed = getWorkspaceValue(mw, ...
    'cegr_valve_area_closed', NaN);
params.cegrValveAreaLow = getWorkspaceValue(mw, ...
    'cegr_valve_area_low', NaN);
params.cegrValveMaxArea = getWorkspaceValue(mw, ...
    'cegr_valve_max_area', NaN);
params.cegrValveAreaFracMax = getWorkspaceValue(mw, ...
    'cegr_valve_area_frac_max', NaN);
params.cegrClosedValveToPipeArea = safeDivide(params.cegrValveAreaClosed, ...
    params.cegrPipeArea);
params.cegrLowValveToPipeArea = safeDivide(params.cegrValveAreaLow, ...
    params.cegrPipeArea);
params.cegrMaxValveToPipeArea = safeDivide(params.cegrValveMaxArea, ...
    params.cegrPipeArea);
params.compMdotMap = getWorkspaceValue(mw, 'comp_mdot_corr_TLU', NaN);
params.maxCompressorMdotKgS = max(params.compMdotMap, [], 'all');
params.intercoolerDpNominalMPa = getWorkspaceValue(mw, ...
    'intercooler_dp_nominal', NaN);
params.intercoolerMdotNominalKgS = getWorkspaceValue(mw, ...
    'intercooler_mdot_nominal', NaN);
params.cathodeSeparatorDpNominalMPa = getWorkspaceValue(mw, ...
    'cathode_separator_dp_nominal', NaN);
params.cathodeSeparatorMdotNominalKgS = getWorkspaceValue(mw, ...
    'cathode_separator_mdot_nominal', NaN);
params.anodeSeparatorDpNominalMPa = getWorkspaceValue(mw, ...
    'anode_separator_dp_nominal', NaN);
params.anodeSeparatorMdotNominalKgS = getWorkspaceValue(mw, ...
    'anode_separator_mdot_nominal', NaN);
params.coolantTubeD = getWorkspaceValue(mw, 'coolant_tube_D', NaN);
params.radiatorPrimaryArea = getWorkspaceValue(mw, ...
    'radiator_air_area_primary', NaN);
params.radiatorFinArea = getWorkspaceValue(mw, ...
    'radiator_air_area_fins', NaN);
params.radiatorAirAreaM2 = params.radiatorPrimaryArea + ...
    params.radiatorFinArea;
params.faraday = 96485.33212; % [C/mol]
params.mH2 = 0.00201588; % [kg/mol]
params.mO2 = 0.031998; % [kg/mol]
params.mH2O = 0.01801528; % [kg/mol]
params.airO2MassFraction = 0.232; % [-]
params.airStoich = 2.0; % [-]
params.rhoAir = 1.20; % [kg/m3], 50 kW sizing estimate
params.rhoH2LowPressure = 0.08; % [kg/m3], conservative low-pressure H2
params.electricalEfficiencyForHeat = 0.55; % [-]
params.coolantCp = 4180; % [J/(kg*K)]
params.coolantDeltaT = 10; % [K]
end

function c = envelopeCase(name, currentDensityAcm2, cellVoltageV)
c = struct();
c.name = string(name);
c.currentDensityAcm2 = currentDensityAcm2;
c.cellVoltageV = cellVoltageV;
c.currentA = NaN;
c.powerKW = NaN;
c.h2KgS = NaN;
c.o2KgS = NaN;
c.waterKgS = NaN;
c.airKgS = NaN;
c.heatRejectKW = NaN;
c.coolantRequiredKgS = NaN;
c.cathodeVelocityMS = NaN;
c.anodeHydrogenVelocityMS = NaN;
c.compressorMargin = NaN;
c.intercoolerDpKPa = NaN;
c.cathodeSeparatorDpKPa = NaN;
c.anodeSeparatorDpKPa = NaN;
c.cathodeSeparatorFlowMargin = NaN;
c.anodeSeparatorFlowMargin = NaN;
end

function c = computeEnvelopeCase(c, p)
c.currentA = p.stackAreaCm2 * c.currentDensityAcm2;
c.powerKW = p.stackNumCells * c.currentA * c.cellVoltageV / 1000;
c.h2KgS = p.stackNumCells * c.currentA * p.mH2 / (2 * p.faraday);
c.o2KgS = p.stackNumCells * c.currentA * p.mO2 / (4 * p.faraday);
c.waterKgS = p.stackNumCells * c.currentA * p.mH2O / (2 * p.faraday);
c.airKgS = p.airStoich * c.o2KgS / p.airO2MassFraction;
c.heatRejectKW = c.powerKW * (1 / p.electricalEfficiencyForHeat - 1);
c.coolantRequiredKgS = c.heatRejectKW * 1000 / ...
    (p.coolantCp * p.coolantDeltaT);
c.cathodeVelocityMS = safeDivide(c.airKgS, ...
    p.rhoAir * pi * p.cathodeTubeD^2 / 4);
c.anodeHydrogenVelocityMS = safeDivide(c.h2KgS, ...
    p.rhoH2LowPressure * pi * p.anodeTubeD^2 / 4);
c.compressorMargin = safeDivide(p.maxCompressorMdotKgS, c.airKgS);
c.intercoolerDpKPa = scaledPressureDropKPa( ...
    p.intercoolerDpNominalMPa, c.airKgS, p.intercoolerMdotNominalKgS);
c.cathodeSeparatorDpKPa = scaledPressureDropKPa( ...
    p.cathodeSeparatorDpNominalMPa, c.airKgS, ...
    p.cathodeSeparatorMdotNominalKgS);
c.anodeSeparatorDpKPa = scaledPressureDropKPa( ...
    p.anodeSeparatorDpNominalMPa, c.h2KgS, ...
    p.anodeSeparatorMdotNominalKgS);
c.cathodeSeparatorFlowMargin = safeDivide( ...
    p.cathodeSeparatorMdotNominalKgS, c.airKgS);
c.anodeSeparatorFlowMargin = safeDivide( ...
    p.anodeSeparatorMdotNominalKgS, c.h2KgS);
end

function result = auditParameterGovernance(model)
mw = get_param(model, 'ModelWorkspace');
items = defineGovernanceItems(mw);
validTags = ["保留", "建议调整", "仅占位", "证据不足", "进入profile"];
requiredA8Params = [ ...
    "intercooler_length", ...
    "intercooler_area", ...
    "intercooler_Dh", ...
    "intercooler_dp_nominal", ...
    "intercooler_mdot_nominal", ...
    "separator_condensation_enabled", ...
    "separator_l2_efficiency", ...
    "cathode_separator_D", ...
    "cathode_separator_length", ...
    "cathode_separator_area", ...
    "cathode_separator_dp_nominal", ...
    "cathode_separator_mdot_nominal", ...
    "anode_separator_D", ...
    "anode_separator_length", ...
    "anode_separator_area", ...
    "anode_separator_dp_nominal", ...
    "anode_separator_mdot_nominal", ...
    "routeA_cathode_humidifier_enabled", ...
    "routeA_cathode_humidifier_gain"];

    paramNames = [items.parameter];
result = struct();
result.items = items;
result.validTags = validTags;
result.tagsOk = all(ismember([items.tag], validTags));
result.presentOk = all([items.present]);
result.requiredA8Params = requiredA8Params;
result.classifiedA8Params = intersect(requiredA8Params, unique(paramNames), ...
    'stable');
result.missingA8Classifications = setdiff(requiredA8Params, ...
    unique(paramNames), 'stable');
result.allA8Classified = isempty(result.missingA8Classifications);
result.profileCandidates = governanceParametersWithTag(items, "进入profile");
result.adjustCandidates = governanceParametersWithTag(items, "建议调整");
result.placeholderParameters = governanceParametersWithTag(items, "仅占位");
result.evidenceGapParameters = governanceParametersWithTag(items, "证据不足");
result.passed = result.tagsOk && result.presentOk && result.allA8Classified;
end

function params = governanceParametersWithTag(items, tag)
mask = [items.tag] == string(tag);
if any(mask)
    params = [items(mask).parameter];
else
    params = strings(1, 0);
end
end

function items = defineGovernanceItems(mw)
items = repmat(emptyGovernanceItem(), 0, 1);
items(end + 1) = governanceItem(mw, "电化学性能", "MEA", ...
    "Membrane Electrode Assembly", "stack_num_cells", ...
    "S0 official", "保留", "50 kW platform core");
items(end + 1) = governanceItem(mw, "电化学性能", "MEA", ...
    "Membrane Electrode Assembly", "stack_area", ...
    "S0 official", "保留", "50 kW platform core");
items(end + 1) = governanceItem(mw, "电化学性能", "MEA", ...
    "Membrane Electrode Assembly", "stack_iL", ...
    "S0 official", "保留", "profile optional");
items(end + 1) = governanceItem(mw, "电化学性能", "MEA", ...
    "Membrane Electrode Assembly", "stack_t_membrane", ...
    "S0 official", "进入profile", "future membrane profile only");

items(end + 1) = governanceItem(mw, "供氢与基础回流", "储氢瓶", ...
    "Hydrogen Source/Fuel Tank", "tank_p", ...
    "S0 official", "保留", "short-run platform source");
items(end + 1) = governanceItem(mw, "供氢与基础回流", "储氢瓶", ...
    "Hydrogen Source/Fuel Tank", "tank_V", ...
    "S0 official", "保留", "vehicle profile may retain");
items(end + 1) = governanceItem(mw, "供氢与基础回流", "供氢管路", ...
    "Hydrogen Source/Pipe (FC)", "anode_tube_D", ...
    "A9 50 kW baseline", "保留", "second-round velocity gate passed");
items(end + 1) = governanceItem(mw, "供氢与基础回流", "减压阀", ...
    "Hydrogen Source/Pressure-Reducing Valve/Valve", ...
    "pressure_reducing_valve_area", "mask local", "证据不足", ...
    "explicit platform parameter candidate");
items(end + 1) = governanceItem(mw, "供氢与基础回流", "阳极水分离接口", ...
    "AnodeWaterSeparator_FC", "anode_separator_D", ...
    "A8 L2", "仅占位", "no active liquid-water removal");
items(end + 1) = governanceItem(mw, "供氢与基础回流", "阳极水分离接口", ...
    "AnodeWaterSeparator_FC", "anode_separator_area", ...
    "A8 L2", "仅占位", "flow-resistance interface");
items(end + 1) = governanceItem(mw, "供氢与基础回流", "阳极水分离接口", ...
    "AnodeWaterSeparator_FC", "anode_separator_length", ...
    "A8 L2", "仅占位", "layout placeholder");
items(end + 1) = governanceItem(mw, "供氢与基础回流", "阳极水分离接口", ...
    "AnodeWaterSeparator_FC", "anode_separator_dp_nominal", ...
    "A8 L2", "保留", "small pressure-drop interface");
items(end + 1) = governanceItem(mw, "供氢与基础回流", "阳极水分离接口", ...
    "AnodeWaterSeparator_FC", "anode_separator_mdot_nominal", ...
    "A8 L2", "保留", "above nominal H2 consumption");

items(end + 1) = governanceItem(mw, "供氧与空压机", "空压机map", ...
    "Oxygen Source/Compressor Map", "comp_mdot_corr_TLU", ...
    "S0 official", "进入profile", "broad for 50 kW but retained");
items(end + 1) = governanceItem(mw, "供氧与空压机", "阴极主管", ...
    "Cathode Humidifier/Pipe (FC)", "cathode_tube_D", ...
    "S0 official", "保留", "50 mm platform duct");
items(end + 1) = governanceItem(mw, "供氧与空压机", "中冷L2接口", ...
    "Intercooler_L2_Interface", "intercooler_Dh", ...
    "A8 L2", "保留", "same as cathode duct");
items(end + 1) = governanceItem(mw, "供氧与空压机", "中冷L2接口", ...
    "Intercooler_L2_Interface", "intercooler_area", ...
    "A8 L2", "保留", "same as cathode duct");
items(end + 1) = governanceItem(mw, "供氧与空压机", "中冷L2接口", ...
    "Intercooler_L2_Interface", "intercooler_length", ...
    "A8 L2", "仅占位", "layout placeholder");
items(end + 1) = governanceItem(mw, "供氧与空压机", "中冷L2接口", ...
    "Intercooler_L2_Interface", "intercooler_dp_nominal", ...
    "A8 L2", "保留", "1 kPa at 0.1 kg/s");
items(end + 1) = governanceItem(mw, "供氧与空压机", "中冷L2接口", ...
    "Intercooler_L2_Interface", "intercooler_mdot_nominal", ...
    "A8 L2", "保留", "covers high-power envelope");
items(end + 1) = governanceItem(mw, "供氧与空压机", "阴极加湿旁路", ...
    "CathodeHumidifierBypass", "routeA_cathode_humidifier_enabled", ...
    "A8 config", "保留", "default platform keeps humidifier active");
items(end + 1) = governanceItem(mw, "供氧与空压机", "阴极加湿旁路", ...
    "CathodeHumidifierBypass/Gain", "routeA_cathode_humidifier_gain", ...
    "A8 config", "保留", "A10 can bypass without deleting path");

items(end + 1) = governanceItem(mw, "冷却与热管理", "冷却管路", ...
    "Cooling System/Fuel Cell Coolant Channels", "coolant_tube_D", ...
    "S0 official", "保留", "50 mm coolant tube");
items(end + 1) = governanceItem(mw, "冷却与热管理", "散热器", ...
    "Cooling System/Radiator", "radiator_air_area_primary", ...
    "S0 official", "证据不足", "needs thermal steady verification");
items(end + 1) = governanceItem(mw, "冷却与热管理", "散热器", ...
    "Cooling System/Radiator", "radiator_air_area_fins", ...
    "S0 official", "证据不足", "needs thermal steady verification");

items(end + 1) = governanceItem(mw, "CEGR与水管理", "出口容腔", ...
    "CathodeOutletChamber", "cathode_outlet_chamber_V", ...
    "A6/A8 platform", "保留", "finite outlet inventory");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "cEGR管路", ...
    "EGRPipe", "cegr_pipe_D", ...
    "A6/A8 platform", "保留", "same as cathode duct for stability");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "cEGR管路", ...
    "EGRPipe", "cegr_pipe_length", ...
    "A6/A8 platform", "进入profile", "layout-dependent");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "cEGR阀", ...
    "EGRValveRestriction", "cegr_valve_area_closed", ...
    "A6 smoke", "保留", "no-EGR closed-valve case");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "cEGR阀", ...
    "EGRValveRestriction", "cegr_valve_area_low", ...
    "A6 smoke", "仅占位", "low-EGR smoke, not valve calibration");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "cEGR阀", ...
    "EGRValveRestriction", "cegr_valve_max_area", ...
    "A9 50 kW baseline", "保留", "0.02 pipe-area upper sanity bound");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "阴极水分离接口", ...
    "CathodeWaterSeparator_FC", "cathode_separator_D", ...
    "A8 L2", "保留", "same as cEGR duct");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "阴极水分离接口", ...
    "CathodeWaterSeparator_FC", "cathode_separator_area", ...
    "A8 L2", "保留", "same as cEGR duct");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "阴极水分离接口", ...
    "CathodeWaterSeparator_FC", "cathode_separator_length", ...
    "A8 L2", "仅占位", "layout placeholder");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "阴极水分离接口", ...
    "CathodeWaterSeparator_FC", "cathode_separator_dp_nominal", ...
    "A8 L2", "保留", "0.5 kPa nominal pressure drop");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "阴极水分离接口", ...
    "CathodeWaterSeparator_FC", "cathode_separator_mdot_nominal", ...
    "A9 50 kW baseline", "保留", "covers nominal and high-power air demand");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "水量KPI观察器", ...
    "SeparatorOrCondensation", "separator_condensation_enabled", ...
    "A8 KPI", "保留", "observer enable flag");
items(end + 1) = governanceItem(mw, "CEGR与水管理", "水量KPI观察器", ...
    "SeparatorOrCondensation", "separator_l2_efficiency", ...
    "A8 KPI", "仅占位", "does not remove liquid water");
end

function item = emptyGovernanceItem()
item = struct( ...
    'subsystem', "", ...
    'device', "", ...
    'module', "", ...
    'parameter', "", ...
    'present', false, ...
    'value', [], ...
    'source', "", ...
    'tag', "", ...
    'a9Action', "");
end

function item = governanceItem(mw, subsystem, device, module, parameter, ...
    source, tag, a9Action)
item = emptyGovernanceItem();
item.subsystem = string(subsystem);
item.device = string(device);
item.module = string(module);
item.parameter = string(parameter);
item.source = string(source);
item.tag = string(tag);
item.a9Action = string(a9Action);
try
    item.value = mw.getVariable(char(parameter));
    item.present = true;
catch
    if item.tag == "证据不足"
        item.value = [];
        item.present = true;
    end
end
end

function result = runA8Regression(model, modelFile)
result = struct();
result.passed = false;
result.errorId = "";
result.errorMessage = "";
result.summary = "not_run";
try
    run('run_routeA_a8_device_chain_audit.m');
    if evalin('base', 'exist(''routeA_a8_device_chain_audit'', ''var'')')
        a8 = evalin('base', 'routeA_a8_device_chain_audit');
        result.passed = logical(a8.passed);
        result.smokePassed = logical(a8.smokePassed);
        result.summary = sprintf('a8_passed=%d smoke_passed=%d', ...
            result.passed, result.smokePassed);
    else
        result.errorId = "RouteA:A9:A8AuditMissing";
        result.errorMessage = "A8 audit did not publish routeA_a8_device_chain_audit";
    end
catch ME
    result.errorId = string(ME.identifier);
    result.errorMessage = firstLine(string(ME.message));
end
resetModelFromDisk(model, modelFile);
refreshModelWorkspace(model);
end

function result = runNominal50kWSteady(model, modelFile, nominalEnvelope)
result = runSteadyCase(model, modelFile, nominalEnvelope, ...
    "nominal_50kW_steady", "cegr_valve_area_closed");
end

function result = runMaxCegrAreaSanity(model, modelFile, nominalEnvelope)
result = runSteadyCase(model, modelFile, nominalEnvelope, ...
    "max_cegr_area_sanity", "cegr_valve_max_area");
end

function result = runSteadyCase(model, modelFile, nominalEnvelope, ...
    caseName, restrictionArea)
result = emptySteadyResult();
result.name = string(caseName);
result.targetPowerKW = nominalEnvelope.powerKW;
result.theoreticalHeatRejectKW = nominalEnvelope.heatRejectKW;
result.targetCurrentA = nominalEnvelope.currentA;
result.targetCurrentDensityAcm2 = nominalEnvelope.currentDensityAcm2;
result.restrictionArea = string(restrictionArea);
try
    resetModelFromDisk(model, modelFile);
    refreshModelWorkspace(model);
    paths = routeA_block_paths(model);
    markAuditSignals(paths);
    simIn = Simulink.SimulationInput(model);
    simIn = simIn.setModelParameter( ...
        'StopTime', '30', ...
        'SignalLogging', 'on', ...
        'SignalLoggingName', 'logsout', ...
        'ReturnWorkspaceOutputs', 'on', ...
        'SimscapeLogType', 'all');
    simIn = simIn.setVariable('drive_cycle_time', [0; 5; 30], ...
        'Workspace', model);
    simIn = simIn.setVariable('drive_cycle_power', ...
        [0; nominalEnvelope.powerKW; nominalEnvelope.powerKW], ...
        'Workspace', model);
    simIn = simIn.setVariable('routeA_cathode_humidifier_gain', 1);
    simIn = simIn.setBlockParameter(paths.egrValve, ...
        'restriction_area', char(restrictionArea));
    simOut = sim(simIn);
    result.passed = true;
    result = collectSteadyResult(simOut, result, model);
    result.pressureChainOk = checkPressureChain(result);
    result.kpiFiniteOk = all(isfinite([result.egrRatioCompIn, ...
        result.egrSplitRatioOut, result.rhCaIn, result.rhCaOut, ...
        result.mWaterSep, result.targetPowerKW, ...
        result.theoreticalHeatRejectKW]));
    result.kpiNonnegativeOk = all([result.egrRatioCompIn, ...
        result.egrSplitRatioOut, result.rhCaIn, result.rhCaOut, ...
        result.mWaterSep, result.targetPowerKW, ...
        result.theoreticalHeatRejectKW] >= 0);
catch ME
    result.passed = false;
    result.errorId = string(ME.identifier);
    result.errorMessage = firstLine(string(ME.message));
end
resetModelFromDisk(model, modelFile);
end

function result = emptySteadyResult()
result = struct( ...
    'name', "", ...
    'restrictionArea', "", ...
    'passed', false, ...
    'errorId', "", ...
    'errorMessage', "", ...
    'targetPowerKW', NaN, ...
    'targetCurrentA', NaN, ...
    'targetCurrentDensityAcm2', NaN, ...
    'actualPowerKW', NaN, ...
    'powerDissipatedKW', NaN, ...
    'theoreticalHeatRejectKW', NaN, ...
    'egrMdot', NaN, ...
    'exhaustMdot', NaN, ...
    'compInletMdot', NaN, ...
    'egrRatioCompIn', NaN, ...
    'egrSplitRatioOut', NaN, ...
    'pOutlet', NaN, ...
    'pEgrValveUp', NaN, ...
    'pEgrValveDown', NaN, ...
    'pCompInlet', NaN, ...
    'rhCaIn', NaN, ...
    'rhCaOut', NaN, ...
    'mWaterSep', NaN, ...
    'pressureChainOk', false, ...
    'kpiFiniteOk', false, ...
    'kpiNonnegativeOk', false);
end

function result = auditA9SecondRound(audit)
fe = audit.formulaEnvelope;
result = struct();
result.nominalAnodeVelocityMS = fe.nominal50kW.anodeHydrogenVelocityMS;
result.nominalCathodeSeparatorFlowMargin = ...
    fe.nominal50kW.cathodeSeparatorFlowMargin;
result.highPowerCathodeSeparatorFlowMargin = ...
    fe.highPowerEnvelope.cathodeSeparatorFlowMargin;
result.cegrMaxValveToPipeArea = fe.parameters.cegrMaxValveToPipeArea;
result.cegrLowValveToPipeArea = fe.parameters.cegrLowValveToPipeArea;
result.nominalAnodeVelocityOk = fe.nominalAnodeVelocityOk;
result.nominalCathodeSeparatorMarginOk = ...
    fe.nominalCathodeSeparatorMarginOk;
result.highPowerCathodeSeparatorMarginOk = ...
    fe.highPowerCathodeSeparatorMarginOk;
result.cegrMaxValveFractionOk = fe.cegrMaxValveFractionOk;
result.maxCegrAreaSanityOk = audit.maxCegrAreaSanity.passed && ...
    audit.maxCegrAreaSanity.pressureChainOk && ...
    audit.maxCegrAreaSanity.kpiFiniteOk;
result.passed = result.nominalAnodeVelocityOk && ...
    result.nominalCathodeSeparatorMarginOk && ...
    result.highPowerCathodeSeparatorMarginOk && ...
    result.cegrMaxValveFractionOk && result.maxCegrAreaSanityOk;
end

function result = collectSteadyResult(simOut, result, model)
logsout = simOut.logsout;
result.egrMdot = scalarLastOrNaN(logsout, "routeA_cegr_mdot");
result.exhaustMdot = scalarLastOrNaN(logsout, "routeA_exhaust_mdot");
if ~isfinite(result.exhaustMdot)
    result.exhaustMdot = scalarLastFromSimOutOrNaN(simOut, ...
        "routeA_exhaust_mdot_ts");
end
result.compInletMdot = scalarLastOrNaN(logsout, "routeA_mdot_comp_inlet");
result.egrRatioCompIn = safeDivide(result.egrMdot, result.compInletMdot);
outletTotalMdot = max(result.egrMdot, 0) + max(result.exhaustMdot, 0);
result.egrSplitRatioOut = safeDivide(max(result.egrMdot, 0), ...
    outletTotalMdot);
result.pOutlet = scalarLastOrNaN(logsout, "routeA_p_outlet");
result.pEgrValveUp = scalarLastOrNaN(logsout, "routeA_p_egr_valve_up");
result.pEgrValveDown = scalarLastOrNaN(logsout, "routeA_p_egr_valve_down");
result.pCompInlet = scalarLastOrNaN(logsout, "routeA_p_comp_inlet");
result.rhCaIn = scalarLastOrNaN(logsout, "routeA_RH_ca_in");
if ~isfinite(result.rhCaIn)
    result.rhCaIn = scalarLastFromSimOutOrNaN(simOut, ...
        "routeA_RH_ca_in_ts");
end
result.rhCaOut = scalarLastOrNaN(logsout, "routeA_RH_ca_out");
if ~isfinite(result.rhCaOut)
    result.rhCaOut = scalarLastFromSimOutOrNaN(simOut, ...
        "routeA_RH_ca_out_ts");
end
result.mWaterSep = scalarLastOrNaN(logsout, "routeA_m_water_sep");
if ~isfinite(result.mWaterSep)
    result.mWaterSep = scalarLastFromSimOutOrNaN(simOut, ...
        "routeA_m_water_sep_ts");
end
[result.actualPowerKW, result.powerDissipatedKW] = ...
    collectSimscapePower(simOut, model);
end

function [powerKW, heatKW] = collectSimscapePower(simOut, model)
powerKW = NaN;
heatKW = NaN;
try
    simlog = simOut.get(['simlog_' model]);
    mea = routeA_simscape_log_mea(simlog);
    powerData = mea.power_elec.series.values('kW');
    powerKW = powerData(end);
catch
end
try
    simlog = simOut.get(['simlog_' model]);
    mea = routeA_simscape_log_mea(simlog);
    heatData = mea.power_dissipated.series.values('kW');
    heatKW = heatData(end);
catch
end
end

function ok = checkPressureChain(result)
tol = 10;
ok = isfinite(result.pOutlet) && isfinite(result.pEgrValveUp) && ...
    isfinite(result.pEgrValveDown) && isfinite(result.pCompInlet) && ...
    result.pOutlet + tol >= result.pEgrValveUp && ...
    result.pEgrValveUp + tol >= result.pEgrValveDown && ...
    result.pEgrValveDown + tol >= result.pCompInlet;
end

function dpKPa = scaledPressureDropKPa(dpNominalMPa, mdotKgS, mdotNominalKgS)
dpKPa = NaN;
if isfinite(dpNominalMPa) && isfinite(mdotKgS) && ...
        isfinite(mdotNominalKgS) && mdotNominalKgS > 0
    dpKPa = dpNominalMPa * 1000 * (mdotKgS / mdotNominalKgS)^2;
end
end

function value = getWorkspaceValue(modelWorkspace, name, fallback)
value = fallback;
try
    value = modelWorkspace.getVariable(name);
catch
end
end

function value = scalarLastOrNaN(logsout, signalName)
value = lastLoggedValueOrNaN(logsout, signalName);
if isempty(value)
    value = NaN;
else
    value = value(1);
end
end

function value = scalarLastFromSimOutOrNaN(simOut, variableName)
value = NaN;
try
    signal = simOut.get(char(variableName));
catch
    return;
end
if isempty(signal)
    return;
end
try
    data = signal.Data;
    value = data(end);
catch
    try
        value = signal(end);
    catch
        value = NaN;
    end
end
end

function value = lastLoggedValueOrNaN(logsout, signalName)
value = NaN;
signalElement = findLoggedElement(logsout, signalName);
if isempty(signalElement)
    return;
end
signal = signalElement.Values;
data = signal.Data;
nTime = numel(signal.Time);
if isvector(data)
    value = data(end);
elseif size(data, 1) == nTime
    value = squeeze(data(end, :));
elseif size(data, ndims(data)) == nTime
    reshaped = reshape(data, [], nTime);
    value = reshaped(:, end).';
else
    value = squeeze(data(end, :));
end
value = value(:).';
end

function signalElement = findLoggedElement(logsout, signalName)
signalElement = [];
for idx = 1:logsout.numElements
    candidate = logsout.get(idx);
    if string(candidate.Name) == signalName
        signalElement = candidate;
        return;
    end
end
end

function out = safeDivide(num, den)
if isfinite(num) && isfinite(den) && abs(den) > eps
    out = num / den;
else
    out = NaN;
end
end

function nameLineFromBlockOut(blockPath, signalName)
if getSimulinkBlockHandle(blockPath) == -1
    return;
end
ph = get_param(blockPath, 'PortHandles');
if isempty(ph.Outport)
    return;
end
lineHandle = get_param(ph.Outport(1), 'Line');
if lineHandle ~= -1
    set_param(lineHandle, 'Name', signalName);
end
end

function markAuditSignals(paths)
nameLineFromBlockOut(paths.compressorFlowConverter, ...
    'routeA_mdot_comp_inlet');
nameLineFromBlockOut(paths.exhaustMassFlowConverter, ...
    'routeA_exhaust_mdot');
nameLineFromBlockOut(paths.cathodeHumidifierConverter, ...
    'routeA_RH_ca_in');
nameLineFromBlockOut(paths.outletRHConverter, ...
    'routeA_RH_ca_out');
nameLineFromBlockOut(paths.separatorObserver, ...
    'routeA_m_water_sep');
end

function txt = firstLine(txt)
parts = splitlines(txt);
txt = parts(1);
end

function resetModelFromDisk(model, modelFile)
if bdIsLoaded(model)
    close_system(model, 0);
end
load_system(modelFile);
end

function refreshModelWorkspace(model)
modelWorkspace = get_param(model, 'ModelWorkspace');
if strcmp(modelWorkspace.DataSource, 'MATLAB File')
    modelWorkspace.reload;
end
end

function restoreFolderAndModel(oldDir, model, modelFile)
cd(oldDir);
if bdIsLoaded(model)
    close_system(model, 0);
end
if exist(modelFile, 'file')
    load_system(modelFile);
end
end

function dispAudit(audit)
fprintf('\nRoute A A9 parameter-governance audit\n');
fprintf('  model=%s\n', audit.model);
fprintf('  timestamp=%s\n', audit.timestamp);
fprintf('\nParameter isolation\n');
fprintf('  layer=%s external_case_enabled=%d default_data_load=%d old_bench_dependency=%d guard=%d passed=%d\n', ...
    audit.parameterIsolation.layer, ...
    audit.parameterIsolation.externalCaseEnabled, ...
    audit.parameterIsolation.defaultScriptReadsTables, ...
    audit.parameterIsolation.defaultScriptReadsOldBench, ...
    audit.parameterIsolation.externalCaseGuard.passed, ...
    audit.parameterIsolation.passed);

fprintf('\nFormula envelope\n');
for k = 1:numel(audit.formulaEnvelope.cases)
    c = audit.formulaEnvelope.cases(k);
    fprintf('  %s j=%.3g A/cm2 power=%.3g kW air=%.4g kg/s H2=%.4g kg/s water=%.4g kg/s heat=%.3g kW comp_margin=%.3g\n', ...
        c.name, c.currentDensityAcm2, c.powerKW, c.airKgS, ...
        c.h2KgS, c.waterKgS, c.heatRejectKW, c.compressorMargin);
    fprintf('    velocity cathode=%.3g m/s anode_H2=%.3g m/s dp_ic=%.3g kPa dp_cath_sep=%.3g kPa dp_an_sep=%.3g kPa\n', ...
        c.cathodeVelocityMS, c.anodeHydrogenVelocityMS, ...
        c.intercoolerDpKPa, c.cathodeSeparatorDpKPa, ...
        c.anodeSeparatorDpKPa);
end
fprintf('  passed=%d warnings=%s\n', audit.formulaEnvelope.passed, ...
    strjoin(audit.formulaEnvelope.warnings.', ', '));

fprintf('\nGovernance coverage\n');
fprintf('  items=%d present_ok=%d tags_ok=%d a8_classified=%d passed=%d\n', ...
    numel(audit.governance.items), audit.governance.presentOk, ...
    audit.governance.tagsOk, audit.governance.allA8Classified, ...
    audit.governance.passed);
fprintf('  adjust_candidates=%s\n', ...
    strjoin(audit.governance.adjustCandidates, ', '));
fprintf('  profile_candidates=%s\n', ...
    strjoin(audit.governance.profileCandidates, ', '));
fprintf('  placeholders=%s\n', ...
    strjoin(audit.governance.placeholderParameters, ', '));

fprintf('\nA8 regression\n');
fprintf('  passed=%d summary=%s error=%s %s\n', ...
    audit.a8Regression.passed, audit.a8Regression.summary, ...
    audit.a8Regression.errorId, audit.a8Regression.errorMessage);

fprintf('\nNominal 50 kW steady\n');
r = audit.nominalSteady;
fprintf('  passed=%d target_power=%.3g kW actual_power=%.3g kW heat_est=%.3g kW heat_sim=%.3g kW\n', ...
    r.passed, r.targetPowerKW, r.actualPowerKW, ...
    r.theoreticalHeatRejectKW, r.powerDissipatedKW);
fprintf('  pressure=%d kpiFinite=%d kpiNonnegative=%d ratio=%.5g split=%.5g RH_in=%.5g RH_out=%.5g water=%.5g\n', ...
    r.pressureChainOk, r.kpiFiniteOk, r.kpiNonnegativeOk, ...
    r.egrRatioCompIn, r.egrSplitRatioOut, r.rhCaIn, r.rhCaOut, ...
    r.mWaterSep);
if ~r.passed
    fprintf('  error=%s %s\n', r.errorId, r.errorMessage);
end

fprintf('\nMax cEGR area sanity\n');
r = audit.maxCegrAreaSanity;
fprintf('  passed=%d restriction=%s target_power=%.3g kW actual_power=%.3g kW\n', ...
    r.passed, r.restrictionArea, r.targetPowerKW, r.actualPowerKW);
fprintf('  pressure=%d kpiFinite=%d ratio=%.5g split=%.5g RH_in=%.5g RH_out=%.5g water=%.5g\n', ...
    r.pressureChainOk, r.kpiFiniteOk, r.egrRatioCompIn, ...
    r.egrSplitRatioOut, r.rhCaIn, r.rhCaOut, r.mWaterSep);
if ~r.passed
    fprintf('  error=%s %s\n', r.errorId, r.errorMessage);
end

fprintf('\nA9 second-round gates\n');
fprintf('  passed=%d anode_v=%.5g margin_nom=%.5g margin_high=%.5g cegr_max_frac=%.5g max_cegr_sanity=%d\n', ...
    audit.a9SecondRound.passed, ...
    audit.a9SecondRound.nominalAnodeVelocityMS, ...
    audit.a9SecondRound.nominalCathodeSeparatorFlowMargin, ...
    audit.a9SecondRound.highPowerCathodeSeparatorFlowMargin, ...
    audit.a9SecondRound.cegrMaxValveToPipeArea, ...
    audit.a9SecondRound.maxCegrAreaSanityOk);

fprintf('\nA9 result\n');
fprintf('  passed=%d\n', audit.passed);
end
