function registry = routeA_observation_registry(paths)
% Return the Route A observation and audit-signal registry.
%
% Signal names are kept separate from display names and physical meaning.
% This prevents a UI label or a derived KPI from being mistaken for a plant
% measurement that the model does not actually publish.

if nargin < 1 || isempty(paths)
    paths = routeA_project_paths();
end

entries = repmat(entryTemplate(), 0, 1);

add("stack.current", "Stack current", "electrical", ...
    "routeA_stack_current_A", "A", "logsout", "y", true, "scalar", ...
    "Stack_Core", "Electrical boundary and KPI", "verified");
add("stack.voltage", "Stack voltage", "electrical", ...
    "routeA_stack_voltage_V", "V", "logsout", "y", true, "scalar", ...
    "Stack_Core", "Electrical boundary and KPI", "verified");
add("stack.power", "Stack power", "electrical", ...
    "routeA_stack_power_kW", "kW", "logsout", "y", false, "unknown", ...
    "Stack_Core", "Electrical KPI; V*I fallback remains available", "optional");
add("stack.temperature", "Stack temperature", "thermal", ...
    "routeA_stack_temperature_C", "degC", "logsout", "y", true, "scalar", ...
    "Thermal_Management_BOP", "Thermal response", "verified");

add("cathode.compressorInletMassFlow", "Compressor inlet mass flow", "cathode", ...
    "routeA_mdot_comp_inlet", "kg/s", "logsout", "y", true, "scalar", ...
    "Cathode_Air_cEGR_BOP/Oxygen Source", "Air supply KPI", "verified");
add("cathode.compressorInletPressure", "Compressor inlet pressure", "cathode", ...
    "routeA_p_comp_inlet", "Pa", "logsout", "y", true, "scalar", ...
    "Cathode_Air_cEGR_BOP/Oxygen Source", "Air supply KPI", "verified");
add("cathode.compressorInletTemperature", "Compressor inlet temperature", "cathode", ...
    "routeA_T_comp_inlet", "deltaK", "logsout", "y", true, "scalar", ...
    "Cathode_Air_cEGR_BOP/Oxygen Source", "Air supply KPI", "verified");
add("cathode.inletSpeciesMassFlow", "Cathode inlet species mass flow", "cathode", ...
    "routeA_mdot_species_ca_in_ts", "kg/s", "SimulationOutput", "z", true, "N-by-4", ...
    "Stack_Core/Cathode Gas Channels", "Species and mass closure", "verified");
add("cathode.inletComposition", "Cathode inlet composition", "cathode", ...
    "routeA_yi_comp_inlet", "-", "logsout", "y", true, "N-by-4", ...
    "Cathode_Air_cEGR_BOP", "Gas composition and cEGR audit", "verified");
add("cathode.outletComposition", "Cathode outlet composition", "cathode", ...
    "routeA_yi_outlet", "-", "logsout", "y", true, "N-by-4", ...
    "Cathode_Exhaust_Backpressure_Water", "Gas composition and closure", "verified");
add("cathode.inletRelativeHumidity", "Cathode inlet RH", "cathode", ...
    "routeA_RH_ca_in_ts", "-", "SimulationOutput", "y", true, "N-by-4", ...
    "Cathode_Air_cEGR_BOP", "Water management", "verified");
add("cathode.outletRelativeHumidity", "Cathode outlet RH", "cathode", ...
    "routeA_RH_ca_out_ts", "-", "SimulationOutput", "y", true, "N-by-4", ...
    "Cathode_Exhaust_Backpressure_Water", "Water management", "verified");
add("cathode.outletPressure", "Cathode outlet pressure", "cathode", ...
    "routeA_p_outlet", "Pa", "logsout", "y", true, "scalar", ...
    "Cathode_Exhaust_Backpressure_Water", "Backpressure KPI", "verified");
add("cathode.outletTemperature", "Cathode outlet temperature", "cathode", ...
    "routeA_T_outlet", "deltaK", "logsout", "y", true, "scalar", ...
    "Cathode_Exhaust_Backpressure_Water", "Cathode thermal and RH state", "verified");
add("cathode.exhaustMassFlow", "Cathode exhaust mass flow", "cathode", ...
    "routeA_exhaust_mdot_ts", "kg/s", "SimulationOutput", "z", true, "scalar", ...
    "System_Control_Observability/RouteA_ExhaustMdot_Diagnostics", ...
    "Gas closure and water ledger", "optional");
add("cathode.waterSeparationRate", "Water separation rate", "water", ...
    "routeA_m_water_sep_ts", "kg/s", "SimulationOutput", "z", true, "scalar", ...
    "System_Control_Observability/WaterSep_ToWorkspace", ...
    "Water ledger", "optional");

add("cegr.actualRatio", "Actual cEGR ratio", "cegr", ...
    "routeA_egr_ratio_comp_in", "-", "logsout", "y", true, "scalar", ...
    "Cathode_Exhaust_Backpressure_Water", "cEGR tracking and KPI", "verified");
add("cegr.controlError", "cEGR control error", "cegr", ...
    "routeA_egr_control_error", "-", "logsout", "y", true, "scalar", ...
    "System_Control_Observability/FCU_BoP_Control", "cEGR tracking and saturation", "verified");
add("cegr.massFlow", "cEGR mass flow", "cegr", ...
    "EGR_mdot_log", "kg/s", "logsout", "y", true, "scalar", ...
    "Cathode_Exhaust_Backpressure_Water", "cEGR mass closure", "verified");
add("cegr.valveUpstreamPressure", "cEGR valve upstream pressure", "cegr", ...
    "routeA_p_egr_valve_up", "Pa", "logsout", "y", true, "scalar", ...
    "Cathode_Air_cEGR_BOP/EGRValveUpPTSensor", "Valve capacity diagnosis", "verified");
add("cegr.valveDownstreamPressure", "cEGR valve downstream pressure", "cegr", ...
    "routeA_p_egr_valve_down", "Pa", "logsout", "y", true, "scalar", ...
    "Cathode_Air_cEGR_BOP/EGRValveDownPTSensor", "Valve capacity diagnosis", "verified");
add("cegr.valveAreaCommand", "cEGR valve area command", "cegr", ...
    "routeA_egr_valve_area_cmd", "m^2", "logsout", "y", false, "scalar", ...
    "System_Control_Observability/FCU_BoP_Control", "Valve command and saturation", "optional");

% Documented but unresolved signals remain visible as explicit open items.
add("anode.inletPressure", "Anode inlet pressure", "anode", ...
    "", "MPa", "unresolved", "y", false, "scalar", ...
    "Anode_Hydrogen_BOP", "Anode result expansion", "unresolved");
add("anode.outletPressure", "Anode outlet pressure", "anode", ...
    "", "MPa", "unresolved", "y", false, "scalar", ...
    "Anode_Hydrogen_BOP", "Anode result expansion", "unresolved");
add("anode.purgeState", "Anode purge state", "anode", ...
    "", "-", "unresolved", "y", false, "scalar", ...
    "Anode_Hydrogen_BOP/Anode Exhaust", "Anode result expansion", "unresolved");
add("thermal.coolantResponse", "Coolant-side response", "thermal", ...
    "", "model", "unresolved", "y", false, "unknown", ...
    "Thermal_Management_BOP/Cooling System", "Thermal result expansion", "unresolved");

registry = struct();
registry.schemaVersion = "RouteA_Observation_Registry_v01";
registry.model = string(paths.modelName);
registry.entries = entries;
registry.count = numel(entries);
registry.requiredCount = sum(arrayfun(@(x) x.required, entries));
registry.generatedAt = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
registry.notes = [ ...
    "logsout signal names are authoritative only after output read-back."; ...
    "Unresolved entries are not allowed to become UI controls or verified KPIs." ];

    function add(canonicalName, displayName, domain, signalName, unit, ...
            sourceType, yOrZ, required, shape, producerPath, auditUse, status)
        entry = entryTemplate();
        entry.canonicalName = string(canonicalName);
        entry.displayName = string(displayName);
        entry.domain = string(domain);
        entry.signalName = string(signalName);
        entry.unit = string(unit);
        entry.sourceType = string(sourceType);
        entry.yOrZ = string(yOrZ);
        entry.required = logical(required);
        entry.shape = string(shape);
        entry.producerPath = string(producerPath);
        entry.auditUse = string(auditUse);
        entry.status = string(status);
        entries(end + 1) = entry;
    end
end

function entry = entryTemplate()
entry = struct( ...
    'canonicalName', "", ...
    'displayName', "", ...
    'domain', "", ...
    'signalName', "", ...
    'unit', "", ...
    'sourceType', "", ...
    'yOrZ', "", ...
    'required', false, ...
    'shape', "", ...
    'producerPath', "", ...
    'auditUse', "", ...
    'status', "");
end
