function [in, context] = routeA_prepare_electrical_boundary_input( ...
    model, modelDir, caseCfg, studyCfg)
% Assemble one Route A electrical-boundary case into SimulationInput.
%
% The caller owns the case definition. This function owns initial-state
% selection, logical-to-model time translation, model variables, solver
% settings, air/cEGR controls, and mode-specific electrical inputs.

if nargin < 4 || isempty(studyCfg)
    studyCfg = struct();
end
validateattributes(model, {'char', 'string'}, {'scalartext'});
if ~isstruct(caseCfg) || numel(caseCfg) ~= 1
    error('RouteA:ElectricalBoundaryCase', ...
        'caseCfg must be a scalar struct.');
end
study = studyDefaults(studyCfg, modelDir);
boundary = getBoundary(caseCfg);
type = string(boundary.type);
if ~any(type == ["Current", "Power", "Voltage"])
    error('RouteA:ElectricalBoundaryType', ...
        'Electrical boundary type must be Current, Power, or Voltage.');
end

in = Simulink.SimulationInput(char(model));
[in, initialMetadata, initialStateSelection] = ...
    routeA_attach_platform_default_initial_state( ...
    in, char(model), modelDir, study.initialStateFile, type, ...
    study.hotStartPolicy, caseCfg);
paths = routeA_block_paths(char(model));
baseline = commandBaseline(initialMetadata);
sourceValue = sourceCommandValue(initialMetadata, type);
startupValue = startupCommandValue(sourceValue, type, study);
boundaryOptions = struct( ...
    'duration_s', study.researchDuration_s, ...
    'commandStartOffset_s', study.commandStartOffset_s, ...
    'startupRampDuration_s', study.startupRampDuration_s, ...
    'initialValue', startupValue, ...
    'label', "electrical_" + lower(type));
boundaryProfile = routeA_normalize_electrical_profile( ...
    boundary.profile, type, boundaryOptions);

cegrSpec = getCegrProfile(caseCfg, baseline);
cegrOptions = struct( ...
    'duration_s', study.researchDuration_s, ...
    'commandStartOffset_s', study.commandStartOffset_s, ...
    'initialValue', baseline.cegr_ratio, ...
    'startupRampDuration_s', study.startupRampDuration_s, ...
    'label', "cegr_ratio");
cegrProfile = routeA_normalize_electrical_profile( ...
    cegrSpec, "CEGR", cegrOptions);

air = getAirConfig(caseCfg, baseline);
cathode = getCathodeControls(caseCfg, baseline);
anode = getAnodeControls(caseCfg, baseline);
thermal = getThermalControls(caseCfg, baseline);
commandProfile = assembleCommandProfile( ...
    baseline, air, cathode, anode, thermal, cegrSpec, study);

if initialStateSelection.useOperatingPoint
    researchStart = initialMetadata.snapshotTimeS;
else
    researchStart = 0;
end
modelStop = researchStart + study.researchDuration_s;
tailWindow = researchStart + study.tailLogicalWindow_s;
boundaryModelTime = researchStart + boundaryProfile.time_s;
cegrModelTime = researchStart + cegrProfile.time_s;
commandModelTime = researchStart + commandProfile.time_s;

in = in.setBlockParameter(paths.electricalLoad, 'input_type', char(type));
in = in.setModelParameter( ...
    'StartTime', '0', ...
    'StopTime', sprintf('%.16g', modelStop), ...
    'Solver', char(study.solver), ...
    'SolverType', 'Variable-step', ...
    'RelTol', sprintf('%.16g', study.relativeTolerance), ...
    'AbsTol', sprintf('%.16g', study.absoluteTolerance), ...
    'MaxStep', sprintf('%.16g', study.studyMaxStep_s), ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SimscapeLogType', 'all', ...
    'OperatingPointContentsChecksumMismatchMsg', 'error', ...
    'SaveFinalState', 'on', ...
    'FinalStateName', 'routeA_research_operating_point', ...
    'SaveOperatingPoint', 'on');

in = in.setVariable('routeA_air_control_mode_id', air.modeId, ...
    'Workspace', char(model));
in = in.setVariable('routeA_egr_control_mode_id', 1, ...
    'Workspace', char(model));
in = in.setVariable('routeA_cegr_enabled', true, 'Workspace', char(model));
in = in.setVariable('routeA_cegr_valve_mode_id', 1, ...
    'Workspace', char(model));
in = in.setVariable('routeA_egr_target_input_mode_id', 1, ...
    'Workspace', char(model));
in = in.setVariable('routeA_command_profile', ...
    [commandModelTime, commandProfile.value], 'Workspace', char(model));

switch type
    case "Current"
        in = in.setVariable('drive_cycle_time', boundaryModelTime, ...
            'Workspace', char(model));
        in = in.setVariable('drive_cycle_current', boundaryProfile.value, ...
            'Workspace', char(model));
    case "Power"
        in = in.setVariable('drive_cycle_time', boundaryModelTime, ...
            'Workspace', char(model));
        in = in.setVariable('drive_cycle_power', boundaryProfile.value, ...
            'Workspace', char(model));
    case "Voltage"
        in = in.setVariable('drive_cycle_time', boundaryModelTime, ...
            'Workspace', char(model));
        in = in.setVariable('drive_cycle_voltage', boundaryProfile.value, ...
            'Workspace', char(model));
        controller = getControllerConfig(caseCfg);
        in = in.setVariable('routeA_voltage_pi_Kp', controller.Kp_A_V, ...
            'Workspace', char(model));
        in = in.setVariable('routeA_voltage_pi_Ki', controller.Ki_A_V_s, ...
            'Workspace', char(model));
        in = in.setVariable('routeA_voltage_current_min_A', ...
            controller.currentMin_A, 'Workspace', char(model));
        in = in.setVariable('routeA_voltage_current_max_A', ...
            controller.currentMax_A, 'Workspace', char(model));
end

mw = get_param(char(model), 'ModelWorkspace');
context = struct();
context.model = string(model);
context.modelDir = string(modelDir);
context.caseCfg = caseCfg;
context.boundaryType = type;
context.boundaryProfile = boundaryProfile;
context.cegrProfile = cegrProfile;
context.boundaryModelTime_s = boundaryModelTime;
context.cegrModelTime_s = cegrModelTime;
context.commandModelTime_s = commandModelTime;
context.commandProfile = commandProfile;
context.initialStateMetadata = initialMetadata;
context.initialStateSelection = initialStateSelection;
context.initialStateMode = initialStateSelection.mode;
context.hotStartPolicy = initialStateSelection.policy;
context.initialStateFile = string(study.initialStateFile);
context.researchStartTime_s = researchStart;
context.researchDuration_s = study.researchDuration_s;
context.modelStopTime_s = modelStop;
context.tailLogicalWindow_s = study.tailLogicalWindow_s;
context.tailWindow_s = tailWindow;
context.calculationType = study.calculationType;
context.logicalStartTime_s = 0;
context.modelTimeOrigin_s = researchStart;
context.steadyRelativeVariationLimit = ...
    study.steadyRelativeVariationLimit;
context.steadyWindowDuration_s = study.steadyWindowDuration_s;
context.solver = struct('name', study.solver, ...
    'startTime_s', 0, ...
    'relativeTolerance', study.relativeTolerance, ...
    'absoluteTolerance', study.absoluteTolerance, ...
    'maxStep_s', study.studyMaxStep_s);
context.studyMaxStep_s = study.studyMaxStep_s;
context.commandStartOffset_s = study.commandStartOffset_s;
context.startupRampDuration_s = study.startupRampDuration_s;
context.startupValue = startupValue;
context.air = air;
context.cathode = cathode;
context.anode = anode;
context.thermal = thermal;
context.stackCells = mw.getVariable('stack_num_cells');
context.cegrValveMaxArea_m2 = mw.getVariable('cegr_valve_max_area');
context.compressorRpmLookupBounds = compressorBounds(mw);
context.faradayConstant_C_mol = 96485.33212;
context.molarMass_kg_mol = [0.0280134, 0.0319988, 0.00201588, 0.01801528];
context.gas = struct( ...
    'n2Index', 1, 'o2Index', 2, 'h2oIndex', 4, ...
    'absoluteResidualTolerance_kg_s', 5e-4, ...
    'relativeResidualTolerance', 0.05);
context.controller = getControllerConfig(caseCfg);
end

function study = studyDefaults(user, modelDir)
study = struct( ...
    'initialStateFile', fullfile(modelDir, ...
        'RouteA_platform_default_initial_state.mat'), ...
    'calculationType', "steady", ...
    'researchDuration_s', 600, ...
    'tailLogicalWindow_s', [540, 600], ...
    'steadyWindowDuration_s', 60, ...
    'steadyRelativeVariationLimit', 0.005, ...
    'solver', "VariableStepAuto", ...
    'relativeTolerance', 1e-3, ...
    'absoluteTolerance', 1e-3, ...
    'studyMaxStep_s', 5, ...
    'commandStartOffset_s', 0.5, ...
    'hotStartPolicy', "auto");
study.startupRampDuration_s = 60;
study.voltageNoLoadMargin_V = 20;
hasExplicitMaxStep = isfield(user, 'studyMaxStep_s');
names = fieldnames(user);
for idx = 1:numel(names)
    if ~isfield(study, names{idx})
        error('RouteA:ElectricalBoundaryStudyField', ...
            'Unsupported study configuration field: %s.', names{idx});
    end
    study.(names{idx}) = user.(names{idx});
end
validateattributes(study.researchDuration_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
study.calculationType = lower(string(study.calculationType));
if ~isscalar(study.calculationType) || ...
        ~any(study.calculationType == ["steady", "transient"])
    error('RouteA:ElectricalBoundaryCalculationType', ...
        'calculationType must be steady or transient.');
end
study.hotStartPolicy = lower(string(study.hotStartPolicy));
if ~isscalar(study.hotStartPolicy) || ...
        ~any(study.hotStartPolicy == ["auto", "hot", "cold"])
    error('RouteA:HotStartPolicy', ...
        'hotStartPolicy must be auto, hot, or cold.');
end
if study.calculationType == "transient" && ~hasExplicitMaxStep
    study.studyMaxStep_s = 0.1;
end
study.solver = string(study.solver);
if ~isscalar(study.solver) || study.solver ~= "VariableStepAuto"
    error('RouteA:ElectricalBoundarySolver', ...
        'Route A currently supports the VariableStepAuto solver only.');
end
validateattributes(study.relativeTolerance, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.absoluteTolerance, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.tailLogicalWindow_s, {'numeric'}, ...
    {'vector', 'numel', 2, 'nonnegative', 'finite'});
study.tailLogicalWindow_s = study.tailLogicalWindow_s(:).';
if study.tailLogicalWindow_s(2) > study.researchDuration_s || ...
        study.tailLogicalWindow_s(2) <= study.tailLogicalWindow_s(1)
    error('RouteA:ElectricalBoundaryTailWindow', ...
        'The logical tail window is outside the research duration.');
end
validateattributes(study.studyMaxStep_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.steadyWindowDuration_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.steadyRelativeVariationLimit, {'numeric'}, ...
    {'scalar', 'positive', 'finite', '<=', 1});
if study.calculationType == "steady" && ...
        diff(study.tailLogicalWindow_s) + eps < study.steadyWindowDuration_s
    error('RouteA:ElectricalBoundarySteadyWindow', ...
        'The steady tail window must cover steadyWindowDuration_s.');
end
validateattributes(study.commandStartOffset_s, {'numeric'}, ...
    {'scalar', 'nonnegative', 'finite'});
validateattributes(study.startupRampDuration_s, {'numeric'}, ...
    {'scalar', 'nonnegative', 'finite'});
validateattributes(study.voltageNoLoadMargin_V, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
if study.commandStartOffset_s + study.startupRampDuration_s >= ...
        study.researchDuration_s
    error('RouteA:ElectricalBoundaryStartupRamp', ...
        'The startup ramp must finish before the study ends.');
end
end

function boundary = getBoundary(caseCfg)
if ~isfield(caseCfg, 'boundary') || ~isstruct(caseCfg.boundary)
    error('RouteA:ElectricalBoundaryMissing', ...
        'Each case must define boundary.type and boundary.profile.');
end
boundary = caseCfg.boundary;
if ~isfield(boundary, 'type')
    error('RouteA:ElectricalBoundaryMissingType', ...
        'Each boundary must define type.');
end
if ~isfield(boundary, 'profile')
    if isfield(boundary, 'value')
        boundary.profile = boundary.value;
    else
        error('RouteA:ElectricalBoundaryMissingProfile', ...
            'Each boundary must define profile.');
    end
end
end

function value = getCegrProfile(caseCfg, baseline)
if ~isfield(caseCfg, 'cegr') || isempty(caseCfg.cegr)
    value = baseline.cegr_ratio;
    return;
end
cegr = caseCfg.cegr;
if isnumeric(cegr)
    value = cegr;
elseif isstruct(cegr) && isfield(cegr, 'profile')
    value = cegr.profile;
elseif isstruct(cegr) && isfield(cegr, 'targetRatio')
    value = cegr.targetRatio;
else
    value = cegr;
end
end

function value = sourceCommandValue(metadata, type)
if ~isfield(metadata, 'baselineElectricalCommand') || ...
        ~isstruct(metadata.baselineElectricalCommand)
    error('RouteA:ElectricalBoundaryInitialMetadata', ...
        'Initial-state metadata lacks baselineElectricalCommand.');
end
field = lower(char(type));
if ~isfield(metadata.baselineElectricalCommand, field)
    error('RouteA:ElectricalBoundaryInitialMetadata', ...
        'Initial-state metadata does not define the %s baseline command.', ...
        type);
end
value = metadata.baselineElectricalCommand.(field);
validateattributes(value, {'numeric'}, {'scalar', 'real', 'finite'});
end

function value = startupCommandValue(sourceValue, ~, ~)
% The MOP baseline command is held at logical t=0 for every I/P/V mode.
value = sourceValue;
validateattributes(value, {'numeric'}, {'scalar', 'real', 'finite'});
end

function air = getAirConfig(caseCfg, baseline)
air = struct('modeId', 2, ...
    'targetOer', baseline.air_target_oer, ...
    'targetMdot_kg_s', baseline.air_target_mdot_kg_s, ...
    'directCommand', baseline.air_direct_command);
air = mergeKnownFields(air, getOptionalStruct(caseCfg, 'air'), ...
    'RouteA:AirControlField');
validateattributes(air.modeId, {'numeric'}, {'scalar', 'integer', '>=', 1, '<=', 3});
end

function cathode = getCathodeControls(caseCfg, baseline)
cathode = struct( ...
    'sourcePressure_MPa_abs', baseline.cathode_source_pressure_MPa_abs, ...
    'sourceTemperature_C', baseline.cathode_source_temperature_C, ...
    'freshAirO2MoleFraction', baseline.cathode_source_o2_mole_fraction, ...
    'freshAirWaterMoleFraction', baseline.cathode_source_h2o_mole_fraction, ...
    'outletPressure_MPa_abs', baseline.cathode_outlet_pressure_MPa_abs, ...
    'humidifierRelativeHumidity', baseline.cathode_humidifier_rh, ...
    'humidifierEnabled', baseline.cathode_humidifier_gain);
cathode = mergeKnownFields(cathode, ...
    getOptionalStruct(caseCfg, 'cathode'), ...
    'RouteA:CathodeControlField');
end

function anode = getAnodeControls(caseCfg, baseline)
anode = struct( ...
    'tankPressure_MPa_abs', baseline.anode_source_pressure_MPa_abs, ...
    'sourceTemperature_C', baseline.anode_source_temperature_C, ...
    'hydrogenMoleFraction', baseline.anode_source_h2_mole_fraction, ...
    'inletPressure_MPa_abs', baseline.anode_inlet_pressure_MPa_abs, ...
    'humidifierRelativeHumidity', baseline.anode_humidifier_rh, ...
    'recirculationBaseCommand', baseline.anode_recirculation_base, ...
    'recirculationCurrentGain_A_inv', ...
        baseline.anode_recirculation_current_gain_A_inv, ...
    'purgeEnabled', baseline.anode_purge_enable, ...
    'purgeOnN2MoleFraction', baseline.anode_purge_on_n2_mole_fraction, ...
    'purgeOffN2MoleFraction', baseline.anode_purge_off_n2_mole_fraction);
anode = mergeKnownFields(anode, getOptionalStruct(caseCfg, 'anode'), ...
    'RouteA:AnodeControlField');
end

function thermal = getThermalControls(caseCfg, baseline)
thermal = struct('stackTemperatureSet_C', ...
    baseline.stack_temperature_set_C);
user = getOptionalStruct(caseCfg, 'thermal');
thermal = mergeKnownFields(thermal, user, 'RouteA:ThermalControlField');
end

function baseline = commandBaseline(metadata)
required = {'commandProfileSchema', 'commandProfileFields', ...
    'commandProfileBaseline'};
if ~builtin('all', isfield(metadata, required)) || ...
        ~contains(string(metadata.commandProfileSchema), "_v10")
    error('RouteA:InitialStateCommandProfileMetadata', ...
        ['The selected initial state lacks the v10 runtime-command ', ...
        'baseline metadata. Generate and promote the v10 bundle first.']);
end
fields = string(metadata.commandProfileFields(:).');
values = metadata.commandProfileBaseline;
if ~isnumeric(values) || ~isvector(values) || ...
        numel(fields) ~= 22 || numel(values) ~= numel(fields) || ...
        any(~isfinite(values(:)))
    error('RouteA:InitialStateCommandProfileMetadata', ...
        'The v10 runtime-command baseline has an invalid 22-field schema.');
end
expected = [ ...
    "cathode_source_pressure_MPa_abs", ...
    "cathode_source_temperature_C", ...
    "cathode_source_o2_mole_fraction", ...
    "cathode_source_h2o_mole_fraction", ...
    "air_target_mdot_kg_s", "air_target_oer", "air_direct_command", ...
    "cathode_outlet_pressure_MPa_abs", "cathode_humidifier_rh", ...
    "cathode_humidifier_gain", "cegr_ratio", ...
    "anode_source_pressure_MPa_abs", ...
    "anode_source_temperature_C", "anode_source_h2_mole_fraction", ...
    "anode_inlet_pressure_MPa_abs", "anode_humidifier_rh", ...
    "anode_recirculation_base", ...
    "anode_recirculation_current_gain_A_inv", "anode_purge_enable", ...
    "anode_purge_on_n2_mole_fraction", ...
    "anode_purge_off_n2_mole_fraction", "stack_temperature_set_C"];
if ~builtin('all', fields == expected)
    error('RouteA:InitialStateCommandProfileSchema', ...
        'The v10 runtime-command field order is not the Route A schema.');
end
baseline = cell2struct(num2cell(values(:).'), cellstr(fields), 2);
end

function profile = assembleCommandProfile( ...
    baseline, air, cathode, anode, thermal, cegrSpec, study)
specs = { ...
    'cathode_source_pressure_MPa_abs', 'CathodeSourcePressure', ...
        cathode.sourcePressure_MPa_abs, false; ...
    'cathode_source_temperature_C', 'CathodeSourceTemperature', ...
        cathode.sourceTemperature_C, false; ...
    'cathode_source_o2_mole_fraction', 'CathodeSourceO2', ...
        cathode.freshAirO2MoleFraction, false; ...
    'cathode_source_h2o_mole_fraction', 'CathodeSourceH2O', ...
        cathode.freshAirWaterMoleFraction, false; ...
    'air_target_mdot_kg_s', 'AirTargetMdot', air.targetMdot_kg_s, false; ...
    'air_target_oer', 'AirTargetOer', air.targetOer, false; ...
    'air_direct_command', 'AirDirectCommand', air.directCommand, false; ...
    'cathode_outlet_pressure_MPa_abs', 'CathodeOutletPressure', ...
        cathode.outletPressure_MPa_abs, false; ...
    'cathode_humidifier_rh', 'CathodeHumidifierRH', ...
        cathode.humidifierRelativeHumidity, false; ...
    'cathode_humidifier_gain', 'CathodeHumidifierGain', ...
        cathode.humidifierEnabled, false; ...
    'cegr_ratio', 'CEGR', cegrSpec, false; ...
    'anode_source_pressure_MPa_abs', 'AnodeSourcePressure', ...
        anode.tankPressure_MPa_abs, false; ...
    'anode_source_temperature_C', 'AnodeSourceTemperature', ...
        anode.sourceTemperature_C, false; ...
    'anode_source_h2_mole_fraction', 'AnodeSourceH2', ...
        anode.hydrogenMoleFraction, false; ...
    'anode_inlet_pressure_MPa_abs', 'AnodeInletPressure', ...
        anode.inletPressure_MPa_abs, false; ...
    'anode_humidifier_rh', 'AnodeHumidifierRH', ...
        anode.humidifierRelativeHumidity, false; ...
    'anode_recirculation_base', 'AnodeRecirculationBase', ...
        anode.recirculationBaseCommand, false; ...
    'anode_recirculation_current_gain_A_inv', 'AnodeRecirculationGain', ...
        anode.recirculationCurrentGain_A_inv, false; ...
    'anode_purge_enable', 'AnodePurgeEnable', anode.purgeEnabled, true; ...
    'anode_purge_on_n2_mole_fraction', 'AnodePurgeOnN2', ...
        anode.purgeOnN2MoleFraction, false; ...
    'anode_purge_off_n2_mole_fraction', 'AnodePurgeOffN2', ...
        anode.purgeOffN2MoleFraction, false; ...
    'stack_temperature_set_C', 'StackTemperature', ...
        thermal.stackTemperatureSet_C, false};
count = size(specs, 1);
profiles = cell(count, 1);
time = zeros(0, 1);
for idx = 1:count
    field = specs{idx, 1};
    options = struct( ...
        'duration_s', study.researchDuration_s, ...
        'commandStartOffset_s', study.commandStartOffset_s, ...
        'startupRampDuration_s', study.startupRampDuration_s, ...
        'initialValue', baseline.(field), 'label', string(field));
    if specs{idx, 4}
        options.startupRampDuration_s = 0;
    end
    profiles{idx} = routeA_normalize_electrical_profile( ...
        specs{idx, 3}, specs{idx, 2}, options);
    time = unique([time; profiles{idx}.time_s], 'sorted');
end
value = zeros(numel(time), count);
for idx = 1:count
    value(:, idx) = interp1(profiles{idx}.time_s, profiles{idx}.value, ...
        time, 'linear');
end
validateCommandProfileMatrix(time, value);
profile = struct('schema', "RouteA_Command_Profile_v10", ...
    'fields', string(specs(:, 1)).', 'time_s', time, 'value', value, ...
    'workspaceValue', [time, value], 'individual', {profiles});
end

function validateCommandProfileMatrix(time, value)
if any(~isfinite(time)) || any(~isfinite(value(:))) || any(diff(time) <= 0)
    error('RouteA:CommandProfileFinite', ...
        'The unified runtime-command profile is not finite and ordered.');
end
if any(value(:, 3) + value(:, 4) > 1 + 1e-12)
    error('RouteA:CathodeSourceComposition', ...
        'Cathode O2 and H2O command fractions must sum to no more than one.');
end
if any(value(:, 12) <= value(:, 15))
    error('RouteA:AnodePressureOrder', ...
        'Anode source pressure must exceed the inlet-pressure command.');
end
if any(value(:, 20) <= value(:, 21))
    error('RouteA:AnodePurgeThresholdOrder', ...
        'Anode purge-on threshold must exceed the purge-off threshold.');
end
end

function result = mergeKnownFields(defaults, user, errorId)
result = defaults;
names = fieldnames(user);
for idx = 1:numel(names)
    if ~isfield(result, names{idx})
        error(errorId, 'Unsupported control field: %s.', names{idx});
    end
    result.(names{idx}) = user.(names{idx});
end
end

function controller = getControllerConfig(caseCfg)
controller = struct('Kp_A_V', 1, 'Ki_A_V_s', 0.05, ...
    'currentMin_A', 0, 'currentMax_A', 392);
controller = mergeKnownFields(controller, ...
    getOptionalStruct(caseCfg, 'controller'), ...
    'RouteA:VoltageControlField');
validateattributes(controller.Kp_A_V, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(controller.Ki_A_V_s, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(controller.currentMin_A, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(controller.currentMax_A, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', controller.currentMin_A});
end

function value = getOptionalStruct(parent, fieldName)
if ~isfield(parent, fieldName) || isempty(parent.(fieldName))
    value = struct();
elseif isstruct(parent.(fieldName)) && isscalar(parent.(fieldName))
    value = parent.(fieldName);
else
    error('RouteA:ElectricalBoundaryControlType', ...
        '%s must be a scalar struct.', fieldName);
end
end

function bounds = compressorBounds(mw)
table = mw.getVariable('comp_rpm_TLU');
bounds = [min(table), max(table)];
end
