function [in, metadata, selection] = ...
    routeA_attach_platform_default_initial_state( ...
    in, model, modelDir, initialStateFile, loadInputType, hotStartPolicy, caseCfg)
% Select and attach the validated platform_default operating point without
% mutating the model.
%
% The default auto policy uses the physical hot-start state for all runtime
% command changes. Pressure, temperature, composition, flow, cEGR,
% recirculation, purge, thermal, and electrical targets are not
% compatibility locks: the runner applies them through RouteA_Command_Profile
% after logical t=0. Only topology, species dimensions, and key physical
% source-conditioner parameters are compatibility gates. An incompatible
% state is always rejected; cold start is an explicit caller decision.
% It changes SimulationInput only, so each case can run independently in
% serial or through parsim. Candidate creation is centralized in
% routeA_generate_platform_default_initial_state.

if nargin < 4 || isempty(initialStateFile) || ...
        strlength(string(initialStateFile)) == 0
    initialStateFile = fullfile(modelDir, ...
        'RouteA_platform_default_initial_state.mat');
end
if nargin < 5 || isempty(loadInputType) || ...
        strlength(string(loadInputType)) == 0
    loadInputType = "Current";
end
if nargin < 6 || isempty(hotStartPolicy)
    hotStartPolicy = "hot";
end
if nargin < 7 || isempty(caseCfg)
    caseCfg = struct();
end
loadInputType = string(loadInputType);
if ~isscalar(loadInputType) || ...
        ~any(loadInputType == ["Current", "Power", "Voltage"])
    error('RouteA:InitialStateLoadInputType', ...
        'loadInputType must be Current, Power, or Voltage.');
end
hotStartPolicy = canonicalHotStartPolicy(hotStartPolicy);
if ~isfile(initialStateFile)
    error('RouteA:MissingPlatformDefaultInitialState', ...
        ['The required platform_default initial state is missing: %s. ', ...
        'Run routeA_generate_platform_default_initial_state first.'], ...
        initialStateFile);
end
loaded = load(initialStateFile);
[initialState, metadata] = selectLoadVariant(loaded, loadInputType);
if ~isfield(metadata, 'schema') || ...
        ~contains(string(metadata.schema), "_v10_")
    error('RouteA:InitialStateChecksumRefreshRequired', ...
        ['The selected initial state is historical or not validated for ', ...
        'the current model configuration. Generate and promote a fresh ', ...
        'v10 I/P/V bundle.']);
end
if ~isa(initialState, 'Simulink.op.ModelOperatingPoint')
    error('RouteA:InitialStateClassMismatch', ...
        'The platform_default initial state must be a ModelOperatingPoint.');
end
validateLowCurrentQuietReference(metadata, loadInputType);
if ~isfield(metadata, 'model') || string(metadata.model) ~= string(model)
    error('RouteA:InitialStateModelMismatch', ...
        'The saved platform_default state belongs to another model.');
end
if ~isfield(metadata, 'cegrTopologyEnabled') || ...
        ~metadata.cegrTopologyEnabled
    error('RouteA:InitialStateTopologyMismatch', ...
        ['The saved state is not for the CEGR-enabled zero-recirculation ', ...
        'topology required by Route A dynamic studies.']);
end
requiredModeFields = {'cegrValveModeId', 'egrReferenceKind'};
if ~builtin('all', isfield(metadata, requiredModeFields)) || ...
        metadata.cegrValveModeId ~= 1 || ...
        string(metadata.egrReferenceKind) ~= "mode1_zero_target_near_zero"
    error('RouteA:InitialStateModeMismatch', ...
        ['The saved state is not a mode-1 zero-target near-zero cEGR ', ...
        'platform_default operating point.']);
end
if ~bdIsLoaded(model)
    error('RouteA:ModelNotLoaded', ...
        'Load the Route A model before attaching its initial state.');
end
validateV10PhysicalMetadata(metadata, model);
if ~isfield(metadata, 'cegrValveMaxArea_m2')
    error('RouteA:InitialStateParameterMetadata', ...
        ['The platform_default initial state does not record ', ...
        'cegrValveMaxArea_m2. Regenerate the formal initial state.']);
end
stateValveArea_m2 = metadata.cegrValveMaxArea_m2;
mw = get_param(model, 'ModelWorkspace');
currentValveArea_m2 = mw.getVariable('cegr_valve_max_area');
validateattributes(stateValveArea_m2, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(currentValveArea_m2, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
if abs(stateValveArea_m2 - currentValveArea_m2) > ...
        1e-12 * max(1, abs(currentValveArea_m2))
    error('RouteA:InitialStateParameterMismatch', ...
        ['The platform_default initial state and model workspace disagree ', ...
        'on cegr_valve_max_area. Regenerate the formal initial state.']);
end

selection = selectHotStartMode(hotStartPolicy, caseCfg);

paths = routeA_block_paths(model);
% The ModelOperatingPoint was created with the mode-1 cEGR topology. Keep
% that compile-time selection on the input; the runner later owns its target.
in = in.setVariable('routeA_cegr_enabled', true, 'Workspace', model);
in = in.setVariable('routeA_cegr_valve_mode_id', 1, 'Workspace', model);
in = in.setBlockParameter(paths.electricalLoad, 'input_type', ...
    char(loadInputType));
if loadInputType == "Current"
    in = in.setBlockParameter(paths.currentCommand, 'VariableName', ...
        '[drive_cycle_time, drive_cycle_current]');
end
if selection.useOperatingPoint
    % SimulationInput.InitialState is the single authoritative hot-start
    % declaration. Setting LoadInitialState=on as well is rejected by sim().
    in = in.setInitialState(initialState);
else
    in = in.setModelParameter('LoadInitialState', 'off');
end
end

function policy = canonicalHotStartPolicy(value)
policy = lower(string(value));
if ~isscalar(policy) || ~any(policy == ["auto", "hot", "cold"])
    error('RouteA:HotStartPolicy', ...
        'hotStartPolicy must be auto, hot, or cold.');
end
end

function selection = selectHotStartMode(policy, caseCfg)
selection = struct('policy', policy, 'mode', "hot", ...
    'useOperatingPoint', true, 'reason', "physical_structure_compatible", ...
    'mismatches', strings(1, 0));
if policy == "cold"
    selection.mode = "cold";
    selection.useOperatingPoint = false;
    selection.reason = "policy_cold";
    return;
end
% caseCfg intentionally has no influence here. Its runtime controls are
% profile targets, never initial-state compatibility criteria.
if ~isstruct(caseCfg) || ~isscalar(caseCfg)
    error('RouteA:InitialStateCaseConfig', ...
        'caseCfg must be a scalar struct when provided.');
end
end

function validateV10PhysicalMetadata(metadata, model)
required = {'commandProfileSchema', 'commandProfileFields', ...
    'commandProfileBaseline', 'baselineElectricalCommand', ...
    'sourceConditionerState', 'modelVersion'};
if ~builtin('all', isfield(metadata, required))
    error('RouteA:InitialStateV10Metadata', ...
        'The v10 initial state lacks unified-command or physical metadata.');
end
if string(metadata.commandProfileSchema) ~= "RouteA_Command_Profile_v10"
    error('RouteA:InitialStateCommandSchema', ...
        'The initial state does not use the RouteA_Command_Profile_v10 schema.');
end
expectedFields = routeA_command_profile_schema().names.';
if ~isequal(string(metadata.commandProfileFields(:)).', expectedFields) || ...
        ~isnumeric(metadata.commandProfileBaseline) || ...
        ~isequal(size(metadata.commandProfileBaseline), [1, numel(expectedFields)]) || ...
        any(~isfinite(metadata.commandProfileBaseline))
    error('RouteA:InitialStateCommandProfileMetadata', ...
        'The v10 initial state has an invalid command-profile baseline.');
end
if ~isstruct(metadata.baselineElectricalCommand) || ...
        ~builtin('all', isfield(metadata.baselineElectricalCommand, ...
        {'current', 'power', 'voltage'}))
    error('RouteA:InitialStateElectricalBaselineMetadata', ...
        'The v10 initial state lacks Current/Power/Voltage baseline commands.');
end
validateSourceConditionerState(metadata.sourceConditionerState, model);
end

function validateSourceConditionerState(state, model)
if ~isstruct(state) || ~isscalar(state) || ...
        ~isfield(state, 'schema') || ...
        string(state.schema) ~= "RouteA_Source_Conditioner_v10" || ...
        ~builtin('all', isfield(state, {'cathode', 'anode'}))
    error('RouteA:InitialStateSourceConditionerMetadata', ...
        'The v10 initial state lacks source-conditioner physical metadata.');
end
mw = get_param(model, 'ModelWorkspace');
validateSourceSide(state.cathode, model, ["N2", "O2", "H2O"], ...
    'Cathode_Source_Conditioner', ...
    mw.getVariable('routeA_cathode_source_conditioner_volume_L'), ...
    mw.getVariable('routeA_cathode_source_conditioner_nominal_flow_kg_s'));
validateSourceSide(state.anode, model, ["H2", "N2"], ...
    'Anode_Source_Conditioner', ...
    mw.getVariable('routeA_anode_source_conditioner_volume_L'), ...
    mw.getVariable('routeA_anode_source_conditioner_nominal_flow_kg_s'));
end

function validateSourceSide(side, model, expectedSpecies, expectedBlock, volume_L, flow_kg_s)
required = {'blockName', 'species', 'chamberVolume_L', 'nominalFlow_kg_s'};
if ~isstruct(side) || ~isscalar(side) || ...
        ~builtin('all', isfield(side, required)) || ...
        string(side.blockName) ~= expectedBlock || ...
        ~isequal(string(side.species(:)).', expectedSpecies)
    error('RouteA:InitialStateSourceConditionerTopology', ...
        'The saved source-conditioner topology or species dimension is incompatible.');
end
matches = find_system(model, 'FollowLinks', 'on', 'LookUnderMasks', 'all', ...
    'Name', expectedBlock);
if numel(matches) ~= 1
    error('RouteA:InitialStateSourceConditionerTopology', ...
        'The active model lacks the required %s subsystem.', expectedBlock);
end
saved = [side.chamberVolume_L, side.nominalFlow_kg_s];
current = [volume_L, flow_kg_s];
if ~isnumeric(saved) || ~isequal(size(saved), [1, 2]) || ...
        any(~isfinite(saved)) || any(saved <= 0) || ...
        any(abs(saved - current) > 1e-12 * max(1, abs(current)))
    error('RouteA:InitialStateSourceConditionerParameter', ...
        'The saved source-conditioner physical parameters are incompatible.');
end
end

function validateLowCurrentQuietReference(metadata, loadInputType)
required = {'currentDensity_A_cm2', 'normalOperationPhase', ...
    'periodicVerification', 'solver'};
if ~builtin('all', isfield(metadata, required))
    error('RouteA:InitialStateReferenceMetadata', ...
        ['The %s initial state lacks the low-current steady reference ', ...
        'metadata required by the Route A calculation contract.'], ...
        loadInputType);
end
if metadata.currentDensity_A_cm2 > 0.1 + eps
    error('RouteA:InitialStateReferenceLoad', ...
        ['The %s initial state is not a low-current reference: ', ...
        'current density %.6g A/cm^2 exceeds 0.1 A/cm^2.'], ...
        loadInputType, metadata.currentDensity_A_cm2);
end
periodic = metadata.periodicVerification;
periodicRequired = {'passed', 'quietWindowPurgeFree', ...
    'maximumRelativeChange', 'relativeVariationLimit', ...
    'quietWindowDuration_s'};
if ~isstruct(periodic) || ~isscalar(periodic) || ...
        ~builtin('all', isfield(periodic, periodicRequired))
    error('RouteA:InitialStateQuietReferenceMetadata', ...
        'The %s initial state lacks post-purge quiet-window verification.', ...
        loadInputType);
end
if ~periodic.passed || ~periodic.quietWindowPurgeFree || ...
        periodic.relativeVariationLimit > 0.005 + eps || ...
        periodic.maximumRelativeChange > periodic.relativeVariationLimit || ...
        periodic.quietWindowDuration_s <= 0
    error('RouteA:InitialStateQuietReferenceGate', ...
        ['The %s initial state did not pass the post-purge quiet-window ', ...
        'steady reference gate.'], loadInputType);
end
if ~isfield(metadata.solver, 'initialConditionStartTime_s') || ...
        metadata.solver.initialConditionStartTime_s ~= 0
    error('RouteA:InitialStateSolverStart', ...
        'The %s initial-state solver reference must start at 0 s.', ...
        loadInputType);
end
end

function [initialState, metadata] = selectLoadVariant(loaded, loadInputType)
if loadInputType == "Current"
    stateField = 'routeA_initial_state_current';
    metadataField = 'routeA_initial_metadata_current';
elseif loadInputType == "Power"
    stateField = 'routeA_initial_state_power';
    metadataField = 'routeA_initial_metadata_power';
else
    stateField = 'routeA_initial_state_voltage';
    metadataField = 'routeA_initial_metadata_voltage';
end
if isfield(loaded, stateField) && isfield(loaded, metadataField)
    initialState = loaded.(stateField);
    metadata = loaded.(metadataField);
elseif isfield(loaded, 'routeA_initial_state') && ...
        isfield(loaded, 'routeA_initial_metadata')
    % Generators write a single generic pair before the atomic bundle
    % promotion. Generic candidates must declare their exact load branch.
    initialState = loaded.routeA_initial_state;
    metadata = loaded.routeA_initial_metadata;
    if ~isfield(metadata, 'loadInputType') || ...
            string(metadata.loadInputType) ~= loadInputType
        error('RouteA:PlatformDefaultLoadVariantMetadata', ...
            'The selected operating point is not marked as %s compatible.', ...
            loadInputType);
    end
else
    error('RouteA:MissingPlatformDefaultLoadVariant', ...
        ['The platform_default initial-state file does not contain the ', ...
        'required %s operating point.'], loadInputType);
end
if ~isfield(metadata, 'loadInputType') || ...
        string(metadata.loadInputType) ~= loadInputType
    error('RouteA:PlatformDefaultLoadVariantMetadata', ...
        'The selected operating point is not marked as %s compatible.', ...
        loadInputType);
end
end
