function routeA_mark_observability_signals(model)
% Mark the existing Route A observability lines for one simulation run.

paths = routeA_block_paths(model);
markSignalFromBlockOutput(paths.fcu, 1, 'routeA_egr_valve_area_cmd');
markSignalFromBlockOutput(paths.fcu, 3, 'routeA_egr_control_error');
markSignalFromBlockOutput(paths.fcu, 4, 'routeA_egr_ratio_comp_in');
markSignalFromBlockOutput(paths.egrValveUpPConverter, 1, ...
    'routeA_p_egr_valve_up');
markSignalFromBlockOutput(paths.egrValveDownPConverter, 1, ...
    'routeA_p_egr_valve_down');
markSignalFromBlockOutput(paths.compressorFlowConverter, 1, ...
    'routeA_mdot_comp_inlet');
markSignalFromBlockOutput(paths.compressorInletPressureConverter, 1, ...
    'routeA_p_comp_inlet');
markSignalFromBlockOutput(paths.compressorInletTemperatureConverter, 1, ...
    'routeA_T_comp_inlet');
markSignalFromBlockOutput(paths.compressorInletCompositionConverter, 1, ...
    'routeA_yi_comp_inlet');
markSignalFromBlockOutput(paths.compressorCommandSwitch, 1, ...
    'routeA_compressor_cmd');
markSignalFromBlockOutput(paths.compressorRpmCommand, 1, ...
    'routeA_compressor_rpm');
markSignalFromBlockOutput(paths.airMdotSetSwitch, 1, ...
    'routeA_air_mdot_set');
markSignalFromBlockOutput(paths.airControlError, 1, ...
    'routeA_air_control_error');
markSignalFromBlockOutput(paths.egrMassFlowConverter, 1, ...
    'routeA_egr_mdot');
markSignalFromBlockOutput(paths.exhaustMassFlowConverter, 1, ...
    'routeA_exhaust_mdot');
markSignalFromBlockOutput(paths.outletPConverter, 1, ...
    'routeA_p_outlet');
markSignalFromBlockOutput(paths.outletTConverter, 1, ...
    'routeA_T_outlet');
markSignalFromBlockOutput(paths.outletYiConverter, 1, ...
    'routeA_yi_outlet');
markSignalFromBlockOutput(paths.measurements, 1, ...
    'routeA_stack_current_A');
markSignalFromBlockOutput(paths.measurements, 2, ...
    'routeA_stack_voltage_V');
markSignalFromBlockOutput(paths.measurements, 3, ...
    'routeA_stack_power_kW');
markSignalFromBlockOutput(paths.measurements, 4, ...
    'routeA_stack_temperature_C');

if string(get_param(paths.electricalLoad, 'input_type')) == "Voltage"
    markSignalFromBlockOutput(paths.voltageReference, 1, ...
        'routeA_voltage_ref_V');
    markSignalFromBlockOutput(paths.voltageError, 1, ...
        'routeA_voltage_control_error_V');
    markSignalFromBlockOutput(paths.voltagePI, 1, ...
        'routeA_voltage_current_cmd_limited_A');
    markSignalFromBlockOutput(paths.voltageRawPID, 1, ...
        'routeA_voltage_current_cmd_raw_A');
    markSignalFromBlockOutput(paths.voltageCurrentDynamics, 1, ...
        'routeA_voltage_current_cmd_A');
    markSignalFromBlockOutput(paths.voltageSaturationStatus, 1, ...
        'routeA_voltage_current_saturated');
end
end

function markSignalFromBlockOutput(blockPath, portNumber, signalName)
if getSimulinkBlockHandle(blockPath) == -1
    error('RouteA:MissingSignalSource', ...
        'Signal source block is unavailable: %s.', blockPath);
end
portHandles = get_param(blockPath, 'PortHandles');
if numel(portHandles.Outport) < portNumber
    error('RouteA:MissingSignalPort', ...
        'Signal source port is unavailable: %s.', blockPath);
end
portHandle = portHandles.Outport(portNumber);
lineHandle = get_param(portHandle, 'Line');
if lineHandle == -1
    error('RouteA:UnconnectedSignal', ...
        'Signal source port is unconnected: %s.', blockPath);
end
set_param(lineHandle, 'Name', signalName);
set_param(portHandle, 'DataLogging', 'on');
set_param(portHandle, 'DataLoggingNameMode', 'Custom', ...
    'DataLoggingName', signalName);
end
