function metadata = routeA_promote_platform_default_voltage_initial_state(modelDir)
% Add a validated Voltage operating point to the formal state file.

if nargin < 1 || strlength(string(modelDir)) == 0
    scriptDir = fileparts(mfilename('fullpath'));
    modelDir = fullfile(scriptDir, '..', '..', '01_模型', ...
        'RouteA_GasMixture_Derived');
end
candidateFile = fullfile(modelDir, ...
    'RouteA_platform_default_initial_state_candidate_mode1_voltage.mat');
formalFile = fullfile(modelDir, ...
    'RouteA_platform_default_initial_state.mat');
nextFile = fullfile(modelDir, ...
    'RouteA_platform_default_initial_state_next.mat');
backupFile = fullfile(modelDir, ...
    'RouteA_platform_default_initial_state_pre_promotion_backup.mat');

if ~isfile(candidateFile) || ~isfile(formalFile)
    error('RouteA:VoltageInitialStatePromotionInput', ...
        'Both formal states and the Voltage candidate are required.');
end
if isfile(nextFile) || isfile(backupFile)
    error('RouteA:VoltageInitialStatePromotionRecoveryRequired', ...
        'Resolve an existing promotion recovery file before continuing.');
end

formal = load(formalFile, 'routeA_initial_state', ...
    'routeA_initial_metadata', 'routeA_initial_state_drive_cycle', ...
    'routeA_initial_metadata_drive_cycle');
candidate = load(candidateFile, 'routeA_initial_state', ...
    'routeA_initial_metadata');
validateState(formal, "Step", 'routeA_initial_state', ...
    'routeA_initial_metadata');
validateState(formal, "Drive cycle", 'routeA_initial_state_drive_cycle', ...
    'routeA_initial_metadata_drive_cycle');
validateState(candidate, "Voltage", 'routeA_initial_state', ...
    'routeA_initial_metadata');

stepMetadata = formal.routeA_initial_metadata;
driveMetadata = formal.routeA_initial_metadata_drive_cycle;
voltageMetadata = candidate.routeA_initial_metadata;
promotionTime = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
areas = [stepMetadata.cegrValveMaxArea_m2, ...
    driveMetadata.cegrValveMaxArea_m2, voltageMetadata.cegrValveMaxArea_m2];
if max(abs(areas - areas(1))) > 1e-12 * max(1, abs(areas(1)))
    error('RouteA:VoltageInitialStatePromotionParameterMismatch', ...
        'The Step, Drive cycle, and Voltage states use different valve areas.');
end

routeA_initial_state = formal.routeA_initial_state;
routeA_initial_metadata = stepMetadata;
routeA_initial_metadata.loadInputType = "Step";
routeA_initial_metadata.availableLoadInputTypes = ...
    ["Step", "Drive cycle", "Voltage"];
routeA_initial_metadata.temporary = false;
routeA_initial_metadata.promotedAt = promotionTime;
routeA_initial_state_drive_cycle = formal.routeA_initial_state_drive_cycle;
routeA_initial_metadata_drive_cycle = driveMetadata;
routeA_initial_metadata_drive_cycle.availableLoadInputTypes = ...
    routeA_initial_metadata.availableLoadInputTypes;
routeA_initial_metadata_drive_cycle.temporary = false;
routeA_initial_metadata_drive_cycle.promotedAt = promotionTime;
routeA_initial_state_voltage = candidate.routeA_initial_state;
routeA_initial_metadata_voltage = voltageMetadata;
routeA_initial_metadata_voltage.availableLoadInputTypes = ...
    routeA_initial_metadata.availableLoadInputTypes;
routeA_initial_metadata_voltage.temporary = false;
routeA_initial_metadata_voltage.promotedAt = promotionTime;
save(nextFile, 'routeA_initial_state', 'routeA_initial_metadata', ...
    'routeA_initial_state_drive_cycle', ...
    'routeA_initial_metadata_drive_cycle', ...
    'routeA_initial_state_voltage', ...
    'routeA_initial_metadata_voltage', '-v7.3');

roundTrip = load(nextFile, 'routeA_initial_state', ...
    'routeA_initial_state_drive_cycle', 'routeA_initial_state_voltage');
if ~isa(roundTrip.routeA_initial_state, 'Simulink.op.ModelOperatingPoint') || ...
        ~isa(roundTrip.routeA_initial_state_drive_cycle, ...
        'Simulink.op.ModelOperatingPoint') || ...
        ~isa(roundTrip.routeA_initial_state_voltage, ...
        'Simulink.op.ModelOperatingPoint')
    error('RouteA:VoltageInitialStatePromotionWrite', ...
        'The composed formal state file did not round-trip correctly.');
end

[movedFormal, formalMessage] = movefile(formalFile, backupFile, 'f');
if ~movedFormal
    delete(nextFile);
    error('RouteA:VoltageInitialStatePromotionBackup', ...
        'Could not stage the existing formal state: %s.', formalMessage);
end
[movedNext, nextMessage] = movefile(nextFile, formalFile, 'f');
if ~movedNext
    movefile(backupFile, formalFile, 'f');
    error('RouteA:VoltageInitialStatePromotionMove', ...
        'Could not promote the composed formal state: %s.', nextMessage);
end
delete(backupFile);
delete(candidateFile);

metadata = routeA_initial_metadata;
assignin('base', 'routeA_platform_default_initial_metadata', metadata);
fprintf('Added the Voltage operating point to: %s\n', formalFile);
end

function validateState(loaded, expectedLoadInputType, stateField, metadataField)
required = {stateField, metadataField};
if ~builtin('all', isfield(loaded, required)) || ...
        ~isa(loaded.(stateField), 'Simulink.op.ModelOperatingPoint')
    error('RouteA:VoltageInitialStatePromotionState', ...
        'A required operating point is unavailable or invalid.');
end
metadata = loaded.(metadataField);
requiredMetadata = {'cegrTopologyEnabled', 'cegrValveModeId', ...
    'egrReferenceKind', 'cegrValveMaxArea_m2'};
if ~builtin('all', isfield(metadata, requiredMetadata)) || ...
        ~metadata.cegrTopologyEnabled || metadata.cegrValveModeId ~= 1 || ...
        string(metadata.egrReferenceKind) ~= "mode1_zero_target_near_zero"
    error('RouteA:VoltageInitialStatePromotionMode', ...
        'An operating point is not a validated mode-1 zero-cEGR state.');
end
if expectedLoadInputType ~= "Step" && ...
        (~isfield(metadata, 'loadInputType') || ...
        string(metadata.loadInputType) ~= expectedLoadInputType)
    error('RouteA:VoltageInitialStatePromotionLoadVariant', ...
        'The candidate is not a %s operating point.', expectedLoadInputType);
end
end
