function registry = routeA_parameter_registry(paths)
% Return the Route A parameter registry for platform and study inputs.
%
% Active entries describe parameters that the current SimulationInput chain
% can set. Platform leaves are also inventoried, but remain closed to the UI
% until their range, model mapping, compile behavior, and response are known.

if nargin < 1 || isempty(paths)
    paths = routeA_project_paths();
end

params = routeA_platform_default_parameters();
entries = repmat(entryTemplate(), 0, 1);

% Study and runtime controls.
add("electrical.mode", "Electrical boundary mode", "electrical", "-", ...
    "Current", [], [], "simCase.controls.electrical", "", ...
    "input_type", "", "study", "no", "validated", "low", ...
    "Select exactly one Current, Power, or Voltage boundary.", "active");
add("electrical.current.profile", "Current command", "electrical", "A", ...
    params.controls.current_default_ref_A.value, 0, 392, ...
    "platform_default", "drive_cycle_current", "", "", "runtime", "no", ...
    "validated", "low", "Current-mode FromWorkspace data column.", "active");
add("electrical.power.profile", "Power command", "electrical", "kW", ...
    params.controls.power_default_ref_kW.value, 0, 150, ...
    "platform_default", "drive_cycle_power", "", "", "runtime", "no", ...
    "validated", "low", "Power-mode FromWorkspace data column.", "active");
add("electrical.voltage.profile", "Voltage command", "electrical", "V", ...
    params.controls.voltage_default_ref_V.value, 0, 500, ...
    "platform_default", "drive_cycle_voltage", "", "", "runtime", "no", ...
    "validated", "low", "Voltage-mode reference data column.", "active");
add("electrical.voltageController.Kp_A_V", "Voltage PI Kp", "electrical", "A/V", ...
    params.controls.voltage_pi_Kp.value, 0, Inf, "platform_default", ...
    "routeA_voltage_pi_Kp", "", "", "controller", "compile", ...
    "validated", "medium", "Voltage controller proportional gain.", "active");
add("electrical.voltageController.Ki_A_V_s", "Voltage PI Ki", "electrical", "A/V/s", ...
    params.controls.voltage_pi_Ki.value, 0, Inf, "platform_default", ...
    "routeA_voltage_pi_Ki", "", "", "controller", "compile", ...
    "validated", "medium", "Voltage controller integral gain.", "active");
add("electrical.voltageController.currentMin_A", "Voltage current lower limit", ...
    "electrical", "A", params.controls.voltage_current_min_A.value, 0, 392, ...
    "platform_default", "routeA_voltage_current_min_A", "", "", "controller", ...
    "compile", "validated", "medium", "Voltage controller lower saturation.", "active");
add("electrical.voltageController.currentMax_A", "Voltage current upper limit", ...
    "electrical", "A", params.controls.voltage_current_max_A.value, 0, 392, ...
    "platform_default", "routeA_voltage_current_max_A", "", "", "controller", ...
    "compile", "validated", "medium", "Voltage controller upper saturation.", "active");

add("cathode.airControlMode", "Air control mode", "cathode", "-", ...
    params.controls.air_control_mode.value, 1, 3, "platform_default", ...
    "routeA_air_control_mode_id", "", "", "controller", "compile", ...
    "validated", "medium", "1=mass flow, 2=OER, 3=direct command.", "active");
add("cathode.targetOer", "Target OER", "cathode", "-", ...
    params.controls.target_oer.value, 1.5, 5, "platform_default", ...
    "routeA_command_profile", "", "air_target_oer", "runtime", "no", ...
    "validated", "medium", "Fresh-air oxygen excess ratio target.", "active");
add("cathode.targetMdot_kg_s", "Target cathode mass flow", "cathode", "kg/s", ...
    params.controls.target_mdot_kg_s.value, 0, Inf, "platform_default", ...
    "routeA_command_profile", "", "air_target_mdot_kg_s", "runtime", "no", ...
    "validated", "medium", "Fresh-air mass-flow target.", "active");
add("cathode.outletPressure_MPa_abs", "Cathode outlet pressure", "cathode", ...
    "MPa(abs)", params.controls.backpressure_MPa_abs.value, 0.1, 0.3, ...
    "platform_default", "routeA_command_profile", "", ...
    "cathode_outlet_pressure_MPa_abs", "runtime", "no", "validated", "medium", ...
    "Cathode exhaust backpressure setpoint.", "active");
add("cathode.humidifierRH", "Cathode humidifier RH", "cathode", "-", ...
    params.cathode.humidifier.default_rh.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "cathode_humidifier_rh", "runtime", "no", ...
    "validated", "medium", "Cathode humidifier relative humidity command.", "active");
add("cathode.o2MoleFraction", "Cathode inlet O2 fraction", "cathode", "-", ...
    params.environment.o2_mole_fraction.value, 0.15, 0.21, "platform_default", ...
    "env_yO2", "", "", "compile", "compile", "validated", "medium", ...
    "Air Intake reservoir compile-time O2 composition.", "active");
add("cathode.h2oMoleFraction", "Cathode inlet H2O fraction", "cathode", "-", ...
    params.environment.h2o_mole_fraction.value, 0, 0.04, "platform_default", ...
    "env_yH20", "", "", "compile", "compile", "validated", "high", ...
    "Legacy model variable name env_yH20 is retained as an explicit mapping.", "active");

add("cegr.enabled", "cEGR enabled", "cegr", "-", ...
    params.controls.cegr_enabled.value, false, true, "platform_default", ...
    "routeA_cegr_enabled", "", "", "compile", "compile", "validated", "medium", ...
    "Keep the cEGR topology and select the valve operating mode.", "active");
add("cegr.targetRatio", "cEGR target ratio", "cegr", "-", ...
    params.controls.cegr_target_ratio.value, 0, 0.5, "platform_default", ...
    "routeA_command_profile", "", "cegr_ratio", "runtime", "no", ...
    "validated", "high", "Target cEGR ratio for the closed-loop mode.", "active");
add("cegr.valveMode", "cEGR valve mode", "cegr", "-", ...
    params.controls.cegr_valve_mode.value, 1, 2, "platform_default", ...
    "routeA_cegr_valve_mode_id", "", "", "compile", "compile", ...
    "validated", "high", "1=area mode, 2=pressure mode.", "active");
add("cegr.controlMode", "cEGR control mode", "cegr", "-", ...
    params.controls.cegr_control_mode.value, 1, 1, "platform_default", ...
    "routeA_egr_control_mode_id", "", "", "compile", "compile", ...
    "validated", "medium", "Current Route A cEGR controller mode.", "active");
add("cegr.targetInputMode", "cEGR target input mode", "cegr", "-", 1, 1, 1, ...
    "platform_default", "routeA_egr_target_input_mode_id", "", "", "compile", ...
    "compile", "validated", "medium", "Current Route A cEGR target input mode.", "active");

add("solver.stopTime_s", "Simulation stop time", "solver", "s", ...
    params.numerics.stopTime_s.value, 0, Inf, "platform_default", "", "", "", ...
    "study", "no", "validated", "low", "Simulation stop time.", "active");
add("solver.relTol", "Relative tolerance", "solver", "-", ...
    params.numerics.relTol.value, eps, 1, "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Variable-step solver relative tolerance.", "active");
add("solver.absTol", "Absolute tolerance", "solver", "-", ...
    params.numerics.absTol.value, eps, Inf, "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Variable-step solver absolute tolerance.", "active");
add("solver.maxStep_s", "Maximum solver step", "solver", "s", ...
    params.numerics.maxStep_s.value, 0, Inf, "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Maximum solver step size.", "active");

% Inventory every platform-default leaf that is not yet an active input.
entries = appendPlatformLeaves(entries, params, '');

registry = struct();
registry.schemaVersion = "RouteA_Parameter_Registry_v01";
registry.model = string(paths.modelName);
registry.sourceFunction = "routeA_platform_default_parameters";
registry.entries = entries;
registry.count = numel(entries);
registry.activeCount = sum(arrayfun(@(x) x.status == "active", entries));
registry.inventoryCount = sum(arrayfun(@(x) x.status == "inventory", entries));
registry.generatedAt = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

    function add(canonicalName, displayName, domain, unit, defaultValue, ...
            minimum, maximum, source, modelWorkspaceVariable, blockParameter, ...
            profileField, tunableClass, requiresCompile, validationLevel, ...
            riskLevel, description, status)
        entry = entryTemplate();
        entry.canonicalName = string(canonicalName);
        entry.displayName = string(displayName);
        entry.domain = string(domain);
        entry.unit = string(unit);
        entry.defaultValue = defaultValue;
        entry.minimum = minimum;
        entry.maximum = maximum;
        entry.source = string(source);
        entry.modelWorkspaceVariable = string(modelWorkspaceVariable);
        entry.blockParameter = string(blockParameter);
        entry.profileField = string(profileField);
        entry.tunableClass = string(tunableClass);
        entry.requiresCompile = string(requiresCompile);
        entry.validationLevel = string(validationLevel);
        entry.riskLevel = string(riskLevel);
        entry.description = string(description);
        entry.status = string(status);
        entries(end + 1) = entry;
    end
end

function entries = appendPlatformLeaves(entries, value, prefix)
if isstruct(value) && isscalar(value) && ...
        isfield(value, 'value') && isfield(value, 'unit') && ...
        isfield(value, 'source') && isfield(value, 'description')
    entry = entryTemplate();
    entry.canonicalName = "platform." + string(prefix);
    entry.displayName = entry.canonicalName;
    entry.domain = firstToken(prefix);
    entry.unit = string(value.unit);
    entry.defaultValue = value.value;
    entry.minimum = [];
    entry.maximum = [];
    entry.source = "routeA_platform_default_parameters." + string(prefix);
    entry.modelWorkspaceVariable = "";
    entry.blockParameter = "";
    entry.profileField = "";
    entry.tunableClass = "inventory";
    entry.requiresCompile = "unknown";
    entry.validationLevel = "inventory";
    entry.riskLevel = "unknown";
    entry.description = string(value.description);
    entry.status = "inventory";
    entries(end + 1) = entry;
    return;
end

if ~isstruct(value) || ~isscalar(value)
    return;
end
names = fieldnames(value);
for idx = 1:numel(names)
    field = names{idx};
    if isempty(prefix)
        childPrefix = field;
    else
        childPrefix = [prefix '.' field];
    end
    entries = appendPlatformLeaves(entries, value.(field), childPrefix);
end
end

function token = firstToken(value)
parts = split(string(value), '.');
token = parts(1);
end

function entry = entryTemplate()
entry = struct( ...
    'canonicalName', "", ...
    'displayName', "", ...
    'domain', "", ...
    'unit', "", ...
    'defaultValue', [], ...
    'minimum', [], ...
    'maximum', [], ...
    'source', "", ...
    'modelWorkspaceVariable', "", ...
    'blockParameter', "", ...
    'profileField', "", ...
    'tunableClass', "", ...
    'requiresCompile', "", ...
    'validationLevel', "", ...
    'riskLevel', "", ...
    'description', "", ...
    'status', "");
end
