function params = routeA_platform_default_parameters()
% Return the Route A platform default parameter tree.
%
% All parameters are organized by equipment domain with source metadata.
% This is the single authoritative entry point for all platform parameters.
%
% Output:
%   params.stack      - Stack/MEA geometry and material properties
%   params.cathode    - Cathode supply path parameters
%   params.cegr       - cEGR path parameters
%   params.anode      - Anode supply path parameters
%   params.thermal    - Thermal management parameters
%   params.controls   - Default control settings
%   params.numerics   - Default solver settings
%   params.environment- Default environmental conditions
%
% Each leaf value is a struct with .value, .unit, .source, .description.
%
% Usage:
%   params = routeA_platform_default_parameters();
%   stack_area = params.stack.area_cm2.value;
%
% See also: routeA_simCase_template

%% Stack / MEA
params.stack.num_cells = p(400, '-', 'official_gas_mixture_example', ...
    'Number of cells in stack');
params.stack.area_cm2 = p(280, 'cm^2', 'official_gas_mixture_example', ...
    'Active area per cell');
params.stack.iL_A_cm2 = p(1.4, 'A/cm^2', 'official_gas_mixture_example', ...
    'Limiting current density');
params.stack.io_A_cm2 = p(1e-4, 'A/cm^2', 'official_gas_mixture_example', ...
    'Exchange current density');
params.stack.alpha = p(0.7, '-', 'official_gas_mixture_example', ...
    'Charge transfer coefficient');
params.stack.t_gdl_um = p(250, 'um', 'official_gas_mixture_example', ...
    'GDL thickness');
params.stack.t_membrane_um = p(125, 'um', 'official_gas_mixture_example', ...
    'Membrane thickness');
params.stack.num_channels = p(8, '-', 'official_gas_mixture_example', ...
    'Number of flow channels per cell');
params.stack.w_channels = p(1, 'mm', 'official_gas_mixture_example', ...
    'Channel width');
params.stack.mea_cp = p(870, 'J/(kg*K)', 'official_gas_mixture_example', ...
    'MEA specific heat capacity');
params.stack.mea_rho = p(1800, 'kg/m^3', 'official_gas_mixture_example', ...
    'MEA density');

%% Cathode supply path
% Compressor / blower
params.cathode.compressor.rpm_TLU = p([0, 1800, 3600], 'rpm', ...
    'official_gas_mixture_example', 'Compressor speed breakpoints');
params.cathode.compressor.p_ratio_TLU = p([1; 1.25; 1.5; 1.75; 2], '-', ...
    'official_gas_mixture_example', 'Pressure ratio breakpoints');
params.cathode.compressor.mdot_corr_TLU = p(...
    [0 0.2 0.4; 0 0.15 0.3; 0 0.1 0.2; 0 0.05 0.1; 0 0 0], 'kg/s', ...
    'official_gas_mixture_example', 'Corrected mass flow table');

% Intercooler
params.cathode.intercooler.Dh_m = p(0.05, 'm', 'official_gas_mixture_example', ...
    'Hydraulic diameter');
params.cathode.intercooler.length_m = p(0.25, 'm', 'official_gas_mixture_example', ...
    'Flow length');
params.cathode.intercooler.area_m2 = p(0.0019635, 'm^2', ...
    'official_gas_mixture_example', 'Flow area');
params.cathode.intercooler.mdot_nominal_kg_s = p(0.1, 'kg/s', ...
    'official_gas_mixture_example', 'Nominal mass flow');
params.cathode.intercooler.dp_nominal_MPa = p(0.001, 'MPa', ...
    'official_gas_mixture_example', 'Nominal pressure drop');
params.cathode.intercooler.T0_C = p(20, 'degC', ...
    'official_gas_mixture_example', 'Initial temperature');

% Compressor inlet mixer
params.cathode.mixer.volume_L = p(0.1, 'L', ...
    'routeA_derived', 'Compressor inlet mixer volume');

% Cathode outlet chamber
params.cathode.outlet_chamber.volume_L = p(0.2, 'L', ...
    'routeA_derived', 'Cathode outlet chamber volume');

% Backpressure
params.cathode.backpressure.default_MPa_abs = p(0.1613, 'MPa(abs)', ...
    'routeA_derived', 'Default backpressure setpoint');

% Humidifier
params.cathode.humidifier.default_rh = p(0.9, '-', ...
    'official_gas_mixture_example', 'Default relative humidity setpoint');
params.cathode.humidifier.enabled = p(1, '-', ...
    'routeA_derived', 'Humidifier enabled (1) or bypassed (0)');

% Separator
params.cathode.separator.D_m = p(0.05, 'm', 'official_gas_mixture_example', ...
    'Separator diameter');
params.cathode.separator.length_m = p(0.15, 'm', 'official_gas_mixture_example', ...
    'Separator length');
params.cathode.separator.mdot_nominal_kg_s = p(0.1, 'kg/s', ...
    'official_gas_mixture_example', 'Nominal separator flow');
params.cathode.separator.dp_nominal_MPa = p(0.0005, 'MPa', ...
    'official_gas_mixture_example', 'Nominal separator pressure drop');

%% cEGR path
params.cegr.valve_max_area_m2 = p(1.9635e-4, 'm^2', ...
    'routeA_derived', 'EGR valve maximum opening area');
params.cegr.valve_open_min_area_m2 = p(1e-10, 'm^2', ...
    'routeA_derived', 'EGR valve minimum opening area');
params.cegr.pipe.length_m = p(0.5, 'm', 'routeA_derived', 'EGR pipe length');
params.cegr.pipe.D_m = p(0.05, 'm', 'routeA_derived', 'EGR pipe diameter');
params.cegr.pipe.area_m2 = p(0.0019635, 'm^2', 'routeA_derived', ...
    'EGR pipe flow area');
params.cegr.pipe.roughness_m = p(1.5e-5, 'm', 'routeA_derived', ...
    'EGR pipe surface roughness');
params.cegr.actuator_tau_s = p(0.5, 's', 'routeA_derived', ...
    'EGR valve actuator time constant');
params.cegr.control.Kp_area = p(1.9635e-4, 'm^2', 'routeA_derived', ...
    'EGR ratio PI proportional gain');
params.cegr.control.Ki_area = p(3.927e-5, 'm^2', 'routeA_derived', ...
    'EGR ratio PI integral gain');

%% Anode supply path
params.anode.tank.p_MPa = p(70, 'MPa', 'official_gas_mixture_example', ...
    'Hydrogen tank pressure');
params.anode.tank.V_L = p(120, 'L', 'official_gas_mixture_example', ...
    'Hydrogen tank volume');
params.anode.tank.T_C = p(20, 'degC', 'official_gas_mixture_example', ...
    'Hydrogen tank temperature');
params.anode.tank.yH2 = p(0.9997, '-', 'routeA_derived', ...
    'Hydrogen mole fraction in tank');
params.anode.default_pressure_MPa_abs = p(0.1613, 'MPa(abs)', ...
    'routeA_derived', 'Default anode inlet pressure setpoint');
params.anode.humidifier.default_rh = p(1.0, '-', ...
    'official_gas_mixture_example', 'Default anode humidifier RH setpoint');
params.anode.recirculation.base_command = p(0.2, '-', ...
    'routeA_derived', 'Anode recirculation base command');
params.anode.recirculation.current_gain_A_inv = p(0.00204, '1/A', ...
    'routeA_derived', 'Anode recirculation current gain');
params.anode.purge.enabled = p(1, '-', 'routeA_derived', ...
    'Anode purge enabled');
params.anode.purge.on_n2_mole_fraction = p(0.5, '-', ...
    'routeA_derived', 'Purge opens when N2 fraction exceeds this');
params.anode.purge.off_n2_mole_fraction = p(0.1, '-', ...
    'routeA_derived', 'Purge closes when N2 fraction falls below this');
params.anode.separator.D_m = p(0.02, 'm', 'official_gas_mixture_example', ...
    'Anode separator diameter');
params.anode.separator.length_m = p(0.12, 'm', 'official_gas_mixture_example', ...
    'Anode separator length');

%% Thermal management
params.thermal.stack_temperature_set_C = p(80, 'degC', ...
    'routeA_derived', 'Stack coolant outlet temperature setpoint');
params.thermal.coolant.num_layers = p(20, '-', ...
    'official_gas_mixture_example', 'Number of coolant layers');
params.thermal.coolant.num_passes = p(12, '-', ...
    'official_gas_mixture_example', 'Number of coolant passes');
params.thermal.coolant.tube_D_m = p(0.05, 'm', ...
    'official_gas_mixture_example', 'Coolant tube diameter');
params.thermal.radiator.H_m = p(0.5, 'm', 'official_gas_mixture_example', ...
    'Radiator height');
params.thermal.radiator.L_m = p(1, 'm', 'official_gas_mixture_example', ...
    'Radiator length');
params.thermal.radiator.N_fins = p(12000, '-', ...
    'official_gas_mixture_example', 'Number of radiator fins');
params.thermal.radiator.N_tubes = p(25, '-', ...
    'official_gas_mixture_example', 'Number of radiator tubes');

%% Default control settings
params.controls.air_control_mode = p(2, '-', 'routeA_derived', ...
    'Air control mode: 1=mdot, 2=OER, 3=direct');
params.controls.target_oer = p(3.0, '-', 'routeA_derived', ...
    'Default target OER');
params.controls.target_mdot_kg_s = p(0.045, 'kg/s', 'routeA_derived', ...
    'Default target mass flow rate');
params.controls.backpressure_MPa_abs = p(0.1613, 'MPa(abs)', ...
    'routeA_derived', 'Default backpressure');
params.controls.voltage_pi_Kp = p(1, 'A/V', 'routeA_derived', ...
    'Voltage PI proportional gain');
params.controls.voltage_pi_Ki = p(0.05, 'A/V/s', 'routeA_derived', ...
    'Voltage PI integral gain');
params.controls.voltage_current_min_A = p(0, 'A', 'routeA_derived', ...
    'Voltage PI current lower limit');
params.controls.voltage_current_max_A = p(392, 'A', 'routeA_derived', ...
    'Voltage PI current upper limit');
params.controls.cegr_enabled = p(false, '-', 'routeA_derived', ...
    'cEGR feature enabled');
params.controls.cegr_valve_mode = p(1, '-', 'routeA_derived', ...
    'cEGR valve mode: 1=area, 2=pressure');
params.controls.cegr_control_mode = p(1, '-', 'routeA_derived', ...
    'cEGR control mode');
params.controls.cegr_target_ratio = p(0, '-', 'routeA_derived', ...
    'Default cEGR target ratio');
params.controls.cegr_direct_area_m2 = p(3.927e-6, 'm^2', ...
    'routeA_derived', 'cEGR direct valve area command');
params.controls.anode_purge_enable = p(1, '-', 'routeA_derived', ...
    'Anode purge enabled by default');
params.controls.anode_purge_on_n2 = p(0.5, '-', 'routeA_derived', ...
    'Purge-on N2 threshold');
params.controls.anode_purge_off_n2 = p(0.1, '-', 'routeA_derived', ...
    'Purge-off N2 threshold');
params.controls.anode_recirc_base = p(0.2, '-', 'routeA_derived', ...
    'Anode recirculation base command');
params.controls.anode_recirc_gain_A_inv = p(0.00204, '1/A', ...
    'routeA_derived', 'Anode recirculation current gain');

% Cathode source boundary (fresh-air supply conditions)
params.controls.cathode_source_pressure_MPa_abs = p(0.15, 'MPa(abs)', ...
    'routeA_derived', 'Cathode fresh-air source pressure');
params.controls.cathode_source_temperature_C = p(20, 'degC', ...
    'routeA_derived', 'Cathode fresh-air source temperature');

% Anode source boundary (hydrogen supply conditions)
params.controls.anode_source_pressure_MPa_abs = p(0.3, 'MPa(abs)', ...
    'routeA_derived', 'Anode hydrogen source pressure');
params.controls.anode_source_temperature_C = p(20, 'degC', ...
    'routeA_derived', 'Anode hydrogen source temperature');

% Air direct command (mode 3 only)
params.controls.air_direct_command = p(0.5, '-', 'routeA_derived', ...
    'Air direct command (mode 3)');

%% Default solver settings
params.numerics.solver = p('VariableStepAuto', '-', 'routeA_derived', ...
    'Simulink solver');
params.numerics.relTol = p(1e-3, '-', 'routeA_derived', ...
    'Relative tolerance');
params.numerics.absTol = p(1e-3, '-', 'routeA_derived', ...
    'Absolute tolerance');
params.numerics.maxStep_s = p(5, 's', 'routeA_derived', ...
    'Maximum step size');
params.numerics.stopTime_s = p(600, 's', 'routeA_derived', ...
    'Default simulation stop time');

%% Default environmental conditions
params.environment.ambient_p_MPa_abs = p(0.101325, 'MPa(abs)', ...
    'physical_constant', 'Standard atmospheric pressure');
params.environment.ambient_T_C = p(20, 'degC', 'routeA_derived', ...
    'Default ambient temperature');
params.environment.ambient_RH = p(0.5, '-', 'routeA_derived', ...
    'Default ambient relative humidity');
params.environment.o2_mole_fraction = p(0.21, '-', ...
    'physical_constant', 'Atmospheric O2 mole fraction');
params.environment.h2o_mole_fraction = p(0.0115436, '-', ...
    'routeA_derived', 'Default H2O mole fraction at 20C, 50% RH');

end

%% -----------------------------------------------------------------------
function s = p(value, unit, source, description)
% Build a parameter leaf with metadata.
s = struct('value', value, 'unit', unit, ...
    'source', source, 'description', description);
end