function [in, metadata] = routeA_attach_platform_default_initial_state( ...
    in, model, modelDir)
% Attach the validated platform_default operating point to a simulation.

initialStateFile = fullfile(modelDir, ...
    'RouteA_platform_default_initial_state.mat');
if ~isfile(initialStateFile)
    error('RouteA:MissingPlatformDefaultInitialState', ...
        ['The required platform_default initial state is missing: %s. ', ...
        'Run routeA_generate_platform_default_initial_state first.'], ...
        initialStateFile);
end
loaded = load(initialStateFile, 'routeA_initial_state', ...
    'routeA_initial_metadata');
if ~isfield(loaded, 'routeA_initial_state') || ...
        ~isfield(loaded, 'routeA_initial_metadata')
    error('RouteA:InvalidPlatformDefaultInitialState', ...
        'The initial-state file does not contain the required variables.');
end
metadata = loaded.routeA_initial_metadata;
if ~isfield(metadata, 'model') || string(metadata.model) ~= string(model)
    error('RouteA:InitialStateModelMismatch', ...
        'The saved platform_default state belongs to another model.');
end
if ~isfield(metadata, 'cegrTopologyEnabled') || ...
        ~metadata.cegrTopologyEnabled
    error('RouteA:InitialStateTopologyMismatch', ...
        ['The saved state is not for the CEGR-enabled zero-recirculation ', ...
        'topology required by Route A dynamic studies.']);
end
if ~bdIsLoaded(model)
    error('RouteA:ModelNotLoaded', ...
        'Load the Route A model before attaching its initial state.');
end
mw = get_param(model, 'ModelWorkspace');
mw.assignin('routeA_cegr_enabled', true);
mw.assignin('routeA_cegr_valve_mode_id', 0);
stackAreaCm2 = mw.getVariable('stack_area');
initialCurrentA = 1e-6 * mw.getVariable('stack_iL') * stackAreaCm2;
loadPath = Simulink.ID.getFullName([model ':368']);
stepPath = Simulink.ID.getFullName([model ':878']);
set_param(loadPath, 'input_type', 'Step');
set_param(stepPath, ...
    'Time', '0.5', ...
    'Before', sprintf('%.16g', initialCurrentA), ...
    'After', sprintf('%.16g', metadata.targetCurrentA));
set_param(model, 'SimulationCommand', 'update');
in = in.setInitialState(loaded.routeA_initial_state);
end
