function [in, context] = routeA_prepare_electrical_boundary_input( ...
    model, modelDir, caseCfg, studyCfg)
% Assemble one Route A electrical-boundary case into SimulationInput.
%
% The active Route A runner is deliberately cold-start-only. Retired v10
% operating-point assets are audit artifacts only; this assembly path does
% not load them and does not require them at runtime.
%
% The caller owns the case definition. This function owns initial-state
% selection, logical-to-model time translation, model variables, solver
% settings, air/cEGR controls, and mode-specific electrical inputs.

if nargin < 4 || isempty(studyCfg)
    studyCfg = struct();
end
validateattributes(model, {'char', 'string'}, {'scalartext'});
if ~isstruct(caseCfg) || numel(caseCfg) ~= 1
    error('RouteA:ElectricalBoundaryCase', ...
        'caseCfg must be a scalar struct.');
end
study = studyDefaults(studyCfg, modelDir);
boundary = getBoundary(caseCfg);
type = string(boundary.type);
if ~any(type == ["Current", "Power", "Voltage"])
    error('RouteA:ElectricalBoundaryType', ...
        'Electrical boundary type must be Current, Power, or Voltage.');
end

in = Simulink.SimulationInput(char(model));
[baseline, baselineValues] = commandBaseline(char(model));
initialMetadata = coldStartMetadata(char(model), char(modelDir), ...
    baselineValues, type, study);
initialStateSelection = coldStartSelection();
paths = routeA_block_paths(char(model));
startupValue = coldStartupCommand(type);
boundaryOptions = struct( ...
    'duration_s', study.researchDuration_s, ...
    'commandStartOffset_s', study.commandStartOffset_s, ...
    'startupRampDuration_s', study.startupRampDuration_s, ...
    'initialValue', startupValue, ...
    'label', "electrical_" + lower(type));
boundaryProfile = routeA_normalize_electrical_profile( ...
    boundary.profile, type, boundaryOptions);

cegrSpec = getCegrProfile(caseCfg, baseline);
cegrOptions = struct( ...
    'duration_s', study.researchDuration_s, ...
    'commandStartOffset_s', study.commandStartOffset_s, ...
    'initialValue', baseline.cegr_ratio, ...
    'startupRampDuration_s', study.startupRampDuration_s, ...
    'label', "cegr_ratio");
cegrProfile = routeA_normalize_electrical_profile( ...
    cegrSpec, "CEGR", cegrOptions);

air = getAirConfig(caseCfg, baseline);
cathode = getCathodeControls(caseCfg, baseline);
anode = getAnodeControls(caseCfg, baseline);
thermal = getThermalControls(caseCfg, baseline);

% Build controls struct in simCase format, then assemble command profile
controls = buildControlsStruct(air, cathode, anode, thermal, cegrSpec);
commandProfile = routeA_assemble_command_profile(controls, study);

researchStart = 0;
modelStop = researchStart + study.researchDuration_s;
tailWindow = researchStart + study.tailLogicalWindow_s;
boundaryModelTime = researchStart + boundaryProfile.time_s;
cegrModelTime = researchStart + cegrProfile.time_s;
commandModelTime = researchStart + commandProfile.time_s;

in = in.setBlockParameter(paths.electricalLoad, 'input_type', char(type));
in = in.setModelParameter( ...
    'StartTime', '0', ...
    'StopTime', sprintf('%.16g', modelStop), ...
    'Solver', char(study.solver), ...
    'SolverType', 'Variable-step', ...
    'RelTol', sprintf('%.16g', study.relativeTolerance), ...
    'AbsTol', sprintf('%.16g', study.absoluteTolerance), ...
    'MaxStep', sprintf('%.16g', study.studyMaxStep_s), ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SimscapeLogType', 'all', ...
    'LoadInitialState', 'off');

in = in.setVariable('routeA_air_control_mode_id', air.modeId, ...
    'Workspace', char(model));
in = in.setVariable('routeA_egr_control_mode_id', 1, ...
    'Workspace', char(model));
in = in.setVariable('routeA_cegr_enabled', true, 'Workspace', char(model));
in = in.setVariable('routeA_cegr_valve_mode_id', 1, ...
    'Workspace', char(model));
in = in.setVariable('routeA_egr_target_input_mode_id', 1, ...
    'Workspace', char(model));
in = in.setVariable('routeA_command_profile', ...
    [commandModelTime, commandProfile.workspaceValue(:, 2:end)], 'Workspace', char(model));
mw = get_param(char(model), 'ModelWorkspace');
modelO2 = mw.getVariable('env_yO2');
modelH2O = mw.getVariable('env_yH20');
if ~isequal(modelO2, cathode.freshAirO2MoleFraction)
    in = in.setVariable('env_yO2', cathode.freshAirO2MoleFraction, ...
        'Workspace', char(model));
end
if ~isequal(modelH2O, cathode.freshAirWaterMoleFraction)
    in = in.setVariable('env_yH20', cathode.freshAirWaterMoleFraction, ...
        'Workspace', char(model));
end

switch type
    case "Current"
        in = in.setVariable('drive_cycle_time', boundaryModelTime, ...
            'Workspace', char(model));
        in = in.setVariable('drive_cycle_current', boundaryProfile.value, ...
            'Workspace', char(model));
    case "Power"
        in = in.setVariable('drive_cycle_time', boundaryModelTime, ...
            'Workspace', char(model));
        in = in.setVariable('drive_cycle_power', boundaryProfile.value, ...
            'Workspace', char(model));
    case "Voltage"
        in = in.setVariable('drive_cycle_time', boundaryModelTime, ...
            'Workspace', char(model));
        in = in.setVariable('drive_cycle_voltage', boundaryProfile.value, ...
            'Workspace', char(model));
        controller = getControllerConfig(caseCfg);
        in = in.setVariable('routeA_voltage_pi_Kp', controller.Kp_A_V, ...
            'Workspace', char(model));
        in = in.setVariable('routeA_voltage_pi_Ki', controller.Ki_A_V_s, ...
            'Workspace', char(model));
        in = in.setVariable('routeA_voltage_current_min_A', ...
            controller.currentMin_A, 'Workspace', char(model));
        in = in.setVariable('routeA_voltage_current_max_A', ...
            controller.currentMax_A, 'Workspace', char(model));
end

context = struct();
context.model = string(model);
context.modelDir = string(modelDir);
context.caseCfg = caseCfg;
context.boundaryType = type;
context.boundaryProfile = boundaryProfile;
context.cegrProfile = cegrProfile;
context.boundaryModelTime_s = boundaryModelTime;
context.cegrModelTime_s = cegrModelTime;
context.commandModelTime_s = commandModelTime;
context.commandProfile = commandProfile;
context.initialStateMetadata = initialMetadata;
context.initialStateSelection = initialStateSelection;
context.initialStateMode = initialStateSelection.mode;
context.initializationPolicy = initialStateSelection.policy;
context.researchStartTime_s = researchStart;
context.researchDuration_s = study.researchDuration_s;
context.modelStopTime_s = modelStop;
context.tailLogicalWindow_s = study.tailLogicalWindow_s;
context.tailWindow_s = tailWindow;
context.calculationType = study.calculationType;
context.logicalStartTime_s = 0;
context.modelTimeOrigin_s = researchStart;
context.steadyRelativeVariationLimit = ...
    study.steadyRelativeVariationLimit;
context.engineeringSteadyRelativeVariationLimit = ...
    study.engineeringSteadyRelativeVariationLimit;
context.steadyWindowDuration_s = study.steadyWindowDuration_s;
context.solver = struct('name', study.solver, ...
    'startTime_s', 0, ...
    'relativeTolerance', study.relativeTolerance, ...
    'absoluteTolerance', study.absoluteTolerance, ...
    'maxStep_s', study.studyMaxStep_s);
context.studyMaxStep_s = study.studyMaxStep_s;
context.commandStartOffset_s = study.commandStartOffset_s;
context.startupRampDuration_s = study.startupRampDuration_s;
context.startupValue = startupValue;
context.air = air;
context.cathode = cathode;
context.anode = anode;
context.thermal = thermal;
context.stackCells = mw.getVariable('stack_num_cells');
context.cegrValveMaxArea_m2 = mw.getVariable('cegr_valve_max_area');
context.compressorRpmLookupBounds = compressorBounds(mw);
context.faradayConstant_C_mol = 96485.33212;
context.molarMass_kg_mol = [0.0280134, 0.0319988, 0.00201588, 0.01801528];
context.gas = struct( ...
    'n2Index', 1, 'o2Index', 2, 'h2oIndex', 4, ...
    'absoluteResidualTolerance_kg_s', 5e-4, ...
    'relativeResidualTolerance', 0.05);
context.controller = getControllerConfig(caseCfg);
end

function study = studyDefaults(user, ~)
study = struct( ...
    'calculationType', "steady", ...
    'researchDuration_s', 600, ...
    'tailLogicalWindow_s', [540, 600], ...
    'steadyWindowDuration_s', 60, ...
    'steadyRelativeVariationLimit', 0.005, ...
    'engineeringSteadyRelativeVariationLimit', 0.01, ...
    'solver', "VariableStepAuto", ...
    'relativeTolerance', 1e-3, ...
    'absoluteTolerance', 1e-3, ...
    'studyMaxStep_s', 5, ...
    'commandStartOffset_s', 0.5);
study.startupRampDuration_s = 60;
study.voltageNoLoadMargin_V = 20;
hasExplicitMaxStep = isfield(user, 'studyMaxStep_s');
names = fieldnames(user);
for idx = 1:numel(names)
    if ~isfield(study, names{idx})
        error('RouteA:ElectricalBoundaryStudyField', ...
            'Unsupported study configuration field: %s.', names{idx});
    end
    study.(names{idx}) = user.(names{idx});
end
study = validateStudy(study, hasExplicitMaxStep);
end

function study = validateStudy(study, hasExplicitMaxStep)
validateattributes(study.researchDuration_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
study.calculationType = lower(string(study.calculationType));
if ~isscalar(study.calculationType) || ...
        ~any(study.calculationType == ["steady", "transient"])
    error('RouteA:ElectricalBoundaryCalculationType', ...
        'calculationType must be steady or transient.');
end
if study.calculationType == "transient" && ~hasExplicitMaxStep
    study.studyMaxStep_s = 0.1;
end
study.solver = string(study.solver);
if ~isscalar(study.solver) || study.solver ~= "VariableStepAuto"
    error('RouteA:ElectricalBoundarySolver', ...
        'Route A currently supports the VariableStepAuto solver only.');
end
validateattributes(study.relativeTolerance, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.absoluteTolerance, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.tailLogicalWindow_s, {'numeric'}, ...
    {'vector', 'numel', 2, 'nonnegative', 'finite'});
study.tailLogicalWindow_s = study.tailLogicalWindow_s(:).';
if study.tailLogicalWindow_s(2) > study.researchDuration_s || ...
        study.tailLogicalWindow_s(2) <= study.tailLogicalWindow_s(1)
    error('RouteA:ElectricalBoundaryTailWindow', ...
        'The logical tail window is outside the research duration.');
end
validateattributes(study.studyMaxStep_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.steadyWindowDuration_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(study.steadyRelativeVariationLimit, {'numeric'}, ...
    {'scalar', 'positive', 'finite', '<=', 1});
validateattributes(study.engineeringSteadyRelativeVariationLimit, {'numeric'}, ...
    {'scalar', 'positive', 'finite', '<=', 1});
if study.engineeringSteadyRelativeVariationLimit < ...
        study.steadyRelativeVariationLimit
    error('RouteA:ElectricalBoundarySteadyLimits', ...
        ['engineeringSteadyRelativeVariationLimit must be greater than or ', ...
        'equal to steadyRelativeVariationLimit.']);
end
if study.calculationType == "steady" && ...
        diff(study.tailLogicalWindow_s) + eps < study.steadyWindowDuration_s
    error('RouteA:ElectricalBoundarySteadyWindow', ...
        'The steady tail window must cover steadyWindowDuration_s.');
end
validateattributes(study.commandStartOffset_s, {'numeric'}, ...
    {'scalar', 'nonnegative', 'finite'});
validateattributes(study.startupRampDuration_s, {'numeric'}, ...
    {'scalar', 'nonnegative', 'finite'});
validateattributes(study.voltageNoLoadMargin_V, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
if study.commandStartOffset_s + study.startupRampDuration_s >= ...
        study.researchDuration_s
    error('RouteA:ElectricalBoundaryStartupRamp', ...
        'The startup ramp must finish before the study ends.');
end
end

function selection = coldStartSelection()
selection = struct( ...
    'policy', "cold_start_only", ...
    'mode', "cold", ...
    'operatingPointLoaded', false, ...
    'reason', "cold_start_only", ...
    'mismatches', strings(1, 0));
end

function value = coldStartupCommand(type)
params = routeA_platform_default_parameters();
switch string(type)
    case {"Current", "Power"}
        value = 0;
    case "Voltage"
        value = params.controls.voltage_startup_ref_V.value;
    otherwise
        error('RouteA:ElectricalBoundaryType', ...
            'Unsupported electrical boundary type: %s.', type);
end
end

function metadata = coldStartMetadata(model, modelDir, baselineValues, type, study)
mw = get_param(model, 'ModelWorkspace');
modelFile = fullfile(modelDir, [model '.slx']);
info = dir(modelFile);
if numel(info) ~= 1
    error('RouteA:ColdStartModelVersion', ...
        'Could not resolve the active Route A model file.');
end
schema = routeA_command_profile_schema();
params = routeA_platform_default_parameters();
metadata = struct( ...
    'schema', "RouteA_cold_start_metadata_v01", ...
    'model', string(model), ...
    'generatedAt', string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')), ...
    'temporary', false, ...
    'loadInputType', string(type), ...
    'snapshotTimeS', 0, ...
    'normalOperationPhase', "cold_start", ...
    'currentDensity_A_cm2', NaN, ...
    'targetCurrentA', NaN, ...
    'periodicVerification', coldPeriodicVerification(), ...
    'physicalSummary', coldPhysicalSummary(), ...
    'initializationCondition', struct( ...
        'electricalInputType', string(type), ...
        'solverStartTime_s', 0, ...
        'targetPowerCommand_kW', NaN, ...
        'targetVoltageCommand_V', NaN, ...
        'targetCurrentCommand_A', NaN), ...
    'commandProfileSchema', schema.version, ...
    'commandProfileFields', schema.names, ...
    'commandProfileBaseline', reshape(double(baselineValues), 1, []), ...
    'baselineElectricalCommand', struct( ...
        'current', params.controls.current_startup_A.value, ...
        'power', params.controls.power_startup_kW.value, ...
        'voltage', params.controls.voltage_startup_ref_V.value), ...
    'supplyBoundaryState', coldSupplyBoundaryState(model), ...
    'modelVersion', struct('fileName', string(info.name), ...
        'bytes', info.bytes, 'modified', string(info.date)), ...
    'topologyHash', coldTopologyHash(model), ...
    'parameterLayer', string(mw.getVariable('routeA_parameter_layer')), ...
    'externalCaseEnabled', logical(mw.getVariable('routeA_external_case_enabled')), ...
    'cegrTopologyEnabled', true, ...
    'cegrValveModeId', 1, ...
    'egrReferenceKind', "cold_start", ...
    'cegrValveMaxArea_m2', mw.getVariable('cegr_valve_max_area'), ...
    'solver', struct('name', study.solver, ...
        'relativeTolerance', study.relativeTolerance, ...
        'absoluteTolerance', study.absoluteTolerance, ...
        'maxStep_s', study.studyMaxStep_s, ...
        'initialConditionStartTime_s', 0));
end

function value = coldTopologyHash(model)
checksum = Simulink.BlockDiagram.getChecksum(model);
value = strjoin(string(dec2hex(uint32(checksum), 8)), '-');
end

function state = coldSupplyBoundaryState(model)
paths = routeA_block_paths(model);
state = struct( ...
    'schema', "RouteA_Supply_Boundary_v01", ...
    'model', string(model), ...
    'cathode', struct('blockName', "Air Intake", ...
        'path', string(paths.airIntake), ...
        'species', ["N2", "O2", "H2", "H2O"], ...
        'compositionVariables', struct('o2', "env_yO2", 'h2o', "env_yH20")), ...
    'anode', struct('blockName', "Hydrogen Source", ...
        'path', string(paths.hydrogenSource), ...
        'species', ["N2", "O2", "H2", "H2O"], ...
        'compositionVariables', struct('h2', "tank_yH2")));
end

function value = coldPeriodicVerification()
value = struct('passed', false, 'quietWindowPurgeFree', false, ...
    'maximumRelativeChange', NaN, 'relativeVariationLimit', NaN, ...
    'quietWindowDuration_s', NaN, 'status', "not_applicable_cold_start");
end

function value = coldPhysicalSummary()
value = struct('stackCurrent_A', NaN, 'stackVoltage_V', NaN, ...
    'stackPower_kW', NaN, 'stackTemperature_C', NaN);
end

function controls = buildControlsStruct(air, cathode, anode, thermal, cegrSpec)
% Build a simCase.controls-format struct from the individual routeA config structs.
controls = struct();
controls.cathode = struct( ...
    'airControlMode', air.modeId, ...
    'targetOer', air.targetOer, ...
    'targetMdot_kg_s', air.targetMdot_kg_s, ...
    'directCommand', air.directCommand, ...
    'sourcePressure_MPa_abs', cathode.sourcePressure_MPa_abs, ...
    'sourceTemperature_C', cathode.sourceTemperature_C, ...
    'o2MoleFraction', cathode.freshAirO2MoleFraction, ...
    'h2oMoleFraction', cathode.freshAirWaterMoleFraction, ...
    'outletPressure_MPa_abs', cathode.outletPressure_MPa_abs, ...
    'humidifierRH', cathode.humidifierRelativeHumidity, ...
    'humidifierEnabled', cathode.humidifierEnabled);
controls.cegr = struct('targetRatio', cegrSpec);
controls.anode = struct( ...
    'sourcePressure_MPa_abs', anode.tankPressure_MPa_abs, ...
    'sourceTemperature_C', anode.sourceTemperature_C, ...
    'h2MoleFraction', anode.hydrogenMoleFraction, ...
    'inletPressure_MPa_abs', anode.inletPressure_MPa_abs, ...
    'humidifierRH', anode.humidifierRelativeHumidity, ...
    'recirculationBaseCommand', anode.recirculationBaseCommand, ...
    'recirculationCurrentGain_A_inv', anode.recirculationCurrentGain_A_inv, ...
    'purgeEnabled', anode.purgeEnabled, ...
    'purgeOnN2MoleFraction', anode.purgeOnN2MoleFraction, ...
    'purgeOffN2MoleFraction', anode.purgeOffN2MoleFraction);
controls.thermal = struct( ...
    'stackTemperatureSet_C', thermal.stackTemperatureSet_C);
end

function boundary = getBoundary(caseCfg)
if ~isfield(caseCfg, 'boundary') || ~isstruct(caseCfg.boundary)
    error('RouteA:ElectricalBoundaryMissing', ...
        'Each case must define boundary.type and boundary.profile.');
end
boundary = caseCfg.boundary;
if ~isfield(boundary, 'type')
    error('RouteA:ElectricalBoundaryMissingType', ...
        'Each boundary must define type.');
end
if ~isfield(boundary, 'profile')
    if isfield(boundary, 'value')
        boundary.profile = boundary.value;
    else
        error('RouteA:ElectricalBoundaryMissingProfile', ...
            'Each boundary must define profile.');
    end
end
end

function value = getCegrProfile(caseCfg, baseline)
if ~isfield(caseCfg, 'cegr') || isempty(caseCfg.cegr)
    value = baseline.cegr_ratio;
    return;
end
cegr = caseCfg.cegr;
if isnumeric(cegr)
    value = cegr;
elseif isstruct(cegr) && isfield(cegr, 'profile')
    value = cegr.profile;
elseif isstruct(cegr) && isfield(cegr, 'time_s') && ...
        isfield(cegr, 'value')
    value = cegr;
elseif isstruct(cegr) && isfield(cegr, 'targetRatio')
    value = cegr.targetRatio;
else
    value = cegr;
end
end

function air = getAirConfig(caseCfg, baseline)
air = struct('modeId', 2, ...
    'targetOer', baseline.air_target_oer, ...
    'targetMdot_kg_s', baseline.air_target_mdot_kg_s, ...
    'directCommand', baseline.air_direct_command);
air = mergeKnownFields(air, getOptionalStruct(caseCfg, 'air'), ...
    'RouteA:AirControlField');
validateattributes(air.modeId, {'numeric'}, {'scalar', 'integer', '>=', 1, '<=', 3});
end

function cathode = getCathodeControls(caseCfg, baseline)
cathode = struct( ...
    'sourcePressure_MPa_abs', baseline.cathode_source_pressure_MPa_abs, ...
    'sourceTemperature_C', baseline.cathode_source_temperature_C, ...
    'freshAirO2MoleFraction', baseline.cathode_source_o2_mole_fraction, ...
    'freshAirWaterMoleFraction', baseline.cathode_source_h2o_mole_fraction, ...
    'outletPressure_MPa_abs', baseline.cathode_outlet_pressure_MPa_abs, ...
    'humidifierRelativeHumidity', baseline.cathode_humidifier_rh, ...
    'humidifierEnabled', baseline.cathode_humidifier_gain);
cathode = mergeKnownFields(cathode, ...
    getOptionalStruct(caseCfg, 'cathode'), ...
    'RouteA:CathodeControlField');
end

function anode = getAnodeControls(caseCfg, baseline)
anode = struct( ...
    'tankPressure_MPa_abs', baseline.anode_source_pressure_MPa_abs, ...
    'sourceTemperature_C', baseline.anode_source_temperature_C, ...
    'hydrogenMoleFraction', baseline.anode_source_h2_mole_fraction, ...
    'inletPressure_MPa_abs', baseline.anode_inlet_pressure_MPa_abs, ...
    'humidifierRelativeHumidity', baseline.anode_humidifier_rh, ...
    'recirculationBaseCommand', baseline.anode_recirculation_base, ...
    'recirculationCurrentGain_A_inv', ...
        baseline.anode_recirculation_current_gain_A_inv, ...
    'purgeEnabled', baseline.anode_purge_enable, ...
    'purgeOnN2MoleFraction', baseline.anode_purge_on_n2_mole_fraction, ...
    'purgeOffN2MoleFraction', baseline.anode_purge_off_n2_mole_fraction);
anode = mergeKnownFields(anode, getOptionalStruct(caseCfg, 'anode'), ...
    'RouteA:AnodeControlField');
end

function thermal = getThermalControls(caseCfg, baseline)
thermal = struct('stackTemperatureSet_C', ...
    baseline.stack_temperature_set_C);
user = getOptionalStruct(caseCfg, 'thermal');
thermal = mergeKnownFields(thermal, user, 'RouteA:ThermalControlField');
end

function [baseline, values] = commandBaseline(model)
mw = get_param(model, 'ModelWorkspace');
fields = string(mw.getVariable('routeA_command_profile_fields'));
values = mw.getVariable('routeA_command_profile_baseline');
schema = routeA_command_profile_schema();
expected = schema.names(:);
if ~isvector(fields) || numel(fields) ~= schema.count || ...
        ~builtin('all', fields(:) == expected)
    error('RouteA:CommandProfileBaselineSchema', ...
        'The model workspace command-profile field order is not the active Route A schema.');
end
if ~isnumeric(values) || ~isvector(values) || ...
        numel(values) ~= schema.count || any(~isfinite(values(:)))
    error('RouteA:CommandProfileBaselineValues', ...
        'The model workspace command-profile baseline has an invalid schema.');
end
values = reshape(double(values), 1, []);
fieldNames = reshape(fields, 1, []);
baseline = cell2struct(num2cell(values), cellstr(fieldNames), 2);
end

function result = mergeKnownFields(defaults, user, errorId)
result = defaults;
names = fieldnames(user);
for idx = 1:numel(names)
    if ~isfield(result, names{idx})
        error(errorId, 'Unsupported control field: %s.', names{idx});
    end
    result.(names{idx}) = user.(names{idx});
end
end

function controller = getControllerConfig(caseCfg)
% PI controller defaults derived from platform parameter file (single source).
pCtrl = routeA_platform_default_parameters().controls;
controller = struct('Kp_A_V', pCtrl.voltage_pi_Kp.value, ...
    'Ki_A_V_s', pCtrl.voltage_pi_Ki.value, ...
    'currentMin_A', pCtrl.voltage_current_min_A.value, ...
    'currentMax_A', pCtrl.voltage_current_max_A.value);
controller = mergeKnownFields(controller, ...
    getOptionalStruct(caseCfg, 'controller'), ...
    'RouteA:VoltageControlField');
validateattributes(controller.Kp_A_V, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(controller.Ki_A_V_s, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(controller.currentMin_A, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(controller.currentMax_A, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', controller.currentMin_A});
end

function value = getOptionalStruct(parent, fieldName)
if ~isfield(parent, fieldName) || isempty(parent.(fieldName))
    value = struct();
elseif isstruct(parent.(fieldName)) && isscalar(parent.(fieldName))
    value = parent.(fieldName);
else
    error('RouteA:ElectricalBoundaryControlType', ...
        '%s must be a scalar struct.', fieldName);
end
end

function bounds = compressorBounds(mw)
table = mw.getVariable('comp_rpm_TLU');
bounds = [min(table), max(table)];
end
