function registry = routeA_parameter_registry(paths)
% Return the Route A parameter registry for platform and study inputs.
%
% Active entries describe parameters that the current SimulationInput chain
% can set. Platform leaves are also inventoried, but remain closed to the UI
% until their range, model mapping, compile behavior, and response are known.

if nargin < 1 || isempty(paths)
    paths = routeA_project_paths();
end

params = routeA_platform_default_parameters();
entries = repmat(entryTemplate(), 0, 1);

% Study and runtime controls.
add("electrical.mode", "Electrical boundary mode", "electrical", "-", ...
    "Current", [], [], "simCase.controls.electrical", "", ...
    "input_type", "", "study", "no", "validated", "low", ...
    "Select exactly one Current, Power, or Voltage boundary.", "active");
add("electrical.current.profile", "Current command", "electrical", "A", ...
    params.controls.current_default_ref_A.value, 0, 392, ...
    "platform_default", "drive_cycle_current", "", "", "runtime", "no", ...
    "validated", "low", "Current-mode FromWorkspace data column.", "active");
add("electrical.power.profile", "Power command", "electrical", "kW", ...
    params.controls.power_default_ref_kW.value, 0, 150, ...
    "platform_default", "drive_cycle_power", "", "", "runtime", "no", ...
    "validated", "low", "Power-mode FromWorkspace data column.", "active");
add("electrical.voltage.profile", "Voltage command", "electrical", "V", ...
    params.controls.voltage_default_ref_V.value, 0, 500, ...
    "platform_default", "drive_cycle_voltage", "", "", "runtime", "no", ...
    "validated", "low", "Voltage-mode reference data column.", "active");
add("electrical.voltageController.Kp_A_V", "Voltage PI Kp", "electrical", "A/V", ...
    params.controls.voltage_pi_Kp.value, 0, Inf, "platform_default", ...
    "routeA_voltage_pi_Kp", "", "", "controller", "compile", ...
    "validated", "medium", "Voltage controller proportional gain.", "active");
add("electrical.voltageController.Ki_A_V_s", "Voltage PI Ki", "electrical", "A/V/s", ...
    params.controls.voltage_pi_Ki.value, 0, Inf, "platform_default", ...
    "routeA_voltage_pi_Ki", "", "", "controller", "compile", ...
    "validated", "medium", "Voltage controller integral gain.", "active");
add("electrical.voltageController.currentMin_A", "Voltage current lower limit", ...
    "electrical", "A", params.controls.voltage_current_min_A.value, 0, 392, ...
    "platform_default", "routeA_voltage_current_min_A", "", "", "controller", ...
    "compile", "validated", "medium", "Voltage controller lower saturation.", "active");
add("electrical.voltageController.currentMax_A", "Voltage current upper limit", ...
    "electrical", "A", params.controls.voltage_current_max_A.value, 0, 392, ...
    "platform_default", "routeA_voltage_current_max_A", "", "", "controller", ...
    "compile", "validated", "medium", "Voltage controller upper saturation.", "active");

add("cathode.airControlMode", "Air control mode", "cathode", "-", ...
    params.controls.air_control_mode.value, 1, 3, "platform_default", ...
    "routeA_air_control_mode_id", "", "", "controller", "compile", ...
    "validated", "medium", "1=mass flow, 2=OER, 3=direct command.", "active");
add("cathode.targetOer", "Target OER", "cathode", "-", ...
    params.controls.target_oer.value, 1.5, 5, "platform_default", ...
    "routeA_command_profile", "", "air_target_oer", "runtime", "no", ...
    "validated", "medium", "Fresh-air oxygen excess ratio target.", "active");
add("cathode.targetMdot_kg_s", "Target cathode mass flow", "cathode", "kg/s", ...
    params.controls.target_mdot_kg_s.value, 0, Inf, "platform_default", ...
    "routeA_command_profile", "", "air_target_mdot_kg_s", "runtime", "no", ...
    "validated", "medium", "Fresh-air mass-flow target.", "active");
add("cathode.directCommand", "Direct air command", "cathode", "-", ...
    params.controls.air_direct_command.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "air_direct_command", "runtime", "no", ...
    "validated", "medium", ...
    "Normalized compressor execution command in [0,1]; mode 3 bypasses OER/target-flow conversion and flow PI but still drives the compressor map.", "active");
add("cathode.sourcePressure_MPa_abs", "Cathode source pressure", "cathode", ...
    "MPa(abs)", params.controls.cathode_source_pressure_MPa_abs.value, ...
    0.1, 0.5, "platform_default", "routeA_command_profile", "", ...
    "cathode_source_pressure_MPa_abs", "runtime", "no", "validated", "medium", ...
    "Fresh-air source pressure boundary.", "active");
add("cathode.sourceTemperature_C", "Cathode source temperature", "cathode", ...
    "degC", params.controls.cathode_source_temperature_C.value, 10, 60, ...
    "platform_default", "routeA_command_profile", "", ...
    "cathode_source_temperature_C", "runtime", "no", "validated", "medium", ...
    "Fresh-air source temperature boundary.", "active");
add("cathode.outletPressure_MPa_abs", "Cathode outlet pressure", "cathode", ...
    "MPa(abs)", params.controls.backpressure_MPa_abs.value, 0.1, 0.3, ...
    "platform_default", "routeA_command_profile", "", ...
    "cathode_outlet_pressure_MPa_abs", "runtime", "no", "validated", "medium", ...
    "Cathode exhaust backpressure setpoint.", "active");
add("cathode.humidifierRH", "Cathode humidifier RH", "cathode", "-", ...
    params.cathode.humidifier.default_rh.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "cathode_humidifier_rh", "runtime", "no", ...
    "validated", "medium", ...
    "RH at humidifier outlet / cathode inlet; temperature reference is the current T_stack path.", "active");
add("cathode.humidifierEnabled", "Cathode humidifier enabled", "cathode", "-", ...
    params.cathode.humidifier.enabled.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "cathode_humidifier_gain", "runtime", "no", ...
    "validated", "medium", "0=bypass, 1=humidifier enabled.", "active");
add("cathode.o2MoleFraction", "Cathode inlet O2 fraction", "cathode", "-", ...
    params.environment.o2_mole_fraction.value, 0.15, 0.21, "platform_default", ...
    "env_yO2", "", "", "compile", "compile", "validated", "medium", ...
    "Air Intake reservoir compile-time O2 composition.", "active");
add("cathode.h2oMoleFraction", "Cathode inlet H2O fraction", "cathode", "-", ...
    params.environment.h2o_mole_fraction.value, 0.005, 0.04, "platform_default", ...
    "env_yH20", "", "", "compile", "compile", "validated", "high", ...
    "Legacy model variable name env_yH20 is retained as an explicit mapping.", "active");

add("cegr.enabled", "cEGR enabled", "cegr", "-", ...
    params.controls.cegr_enabled.value, false, true, "platform_default", ...
    "routeA_cegr_enabled", "", "", "compile", "compile", "validated", "medium", ...
    "Keep the cEGR topology and select the valve operating mode.", "active");
add("cegr.targetRatio", "cEGR target ratio", "cegr", "-", ...
    params.controls.cegr_target_ratio.value, 0, 0.5, "platform_default", ...
    "routeA_command_profile", "", "cegr_ratio", "runtime", "no", ...
    "validated", "high", "Target cEGR ratio for the closed-loop mode.", "active");
add("cegr.valveMode", "cEGR valve mode", "cegr", "-", ...
    params.controls.cegr_valve_mode.value, 1, 2, "platform_default", ...
    "routeA_cegr_valve_mode_id", "", "", "compile", "compile", ...
    "validated", "high", "1=area mode, 2=pressure mode.", "active");
add("cegr.controlMode", "cEGR control mode", "cegr", "-", ...
    params.controls.cegr_control_mode.value, 1, 1, "platform_default", ...
    "routeA_egr_control_mode_id", "", "", "compile", "compile", ...
    "validated", "medium", "Current Route A cEGR controller mode.", "active");
add("cegr.targetInputMode", "cEGR target input mode", "cegr", "-", 1, 1, 1, ...
    "platform_default", "routeA_egr_target_input_mode_id", "", "", "compile", ...
    "compile", "validated", "medium", "Current Route A cEGR target input mode.", "active");
add("cegr.controller.Kp_area", "cEGR PI Kp", "cegr", "m^2", ...
    params.cegr.control.Kp_area.value, eps, Inf, "platform_default", ...
    "routeA_egr_control_Kp_area", "", "", "controller", "compile", ...
    "validated", "medium", "cEGR target-ratio controller proportional gain.", "active");
add("cegr.controller.Ki_area", "cEGR PI Ki", "cegr", "m^2/s", ...
    params.cegr.control.Ki_area.value, eps, Inf, "platform_default", ...
    "routeA_egr_control_Ki_area", "", "", "controller", "compile", ...
    "validated", "medium", "cEGR target-ratio controller integral gain.", "active");
add("cegr.actuatorTau_s", "cEGR actuator time constant", "cegr", "s", ...
    params.cegr.actuator_tau_s.value, eps, Inf, "platform_default", ...
    "routeA_egr_valve_actuator_tau", "", "", "actuator", "compile", ...
    "validated", "medium", "cEGR valve actuator first-order time constant.", "active");

% Anode controls are now exposed in the advanced panel. The command-profile
% fields already exist in the active runner; H2 composition additionally
% updates the compile-time model-workspace variable tank_yH2.
add("anode.sourcePressure_MPa_abs", "Anode source pressure", "anode", ...
    "MPa(abs)", params.controls.anode_source_pressure_MPa_abs.value, ...
    0.2, 0.5, "platform_default", "routeA_command_profile", "", ...
    "anode_source_pressure_MPa_abs", "runtime", "no", "validated", "medium", ...
    "Hydrogen source pressure command.", "active");
add("anode.sourceTemperature_C", "Anode source temperature", "anode", ...
    "degC", params.controls.anode_source_temperature_C.value, 10, 60, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_source_temperature_C", "runtime", "no", "validated", "medium", ...
    "Hydrogen source temperature command.", "active");
add("anode.h2MoleFraction", "Anode H2 mole fraction", "anode", "-", ...
    params.anode.tank.yH2.value, 0.9, 1.0, "platform_default", "tank_yH2", ...
    "", "anode_source_h2_mole_fraction", "compile", "compile", "validated", ...
    "high", "Hydrogen tank composition; applied before simulation.", "active");
add("anode.inletPressure_MPa_abs", "Anode inlet pressure", "anode", ...
    "MPa(abs)", params.anode.default_pressure_MPa_abs.value, 0.1, 0.3, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_inlet_pressure_MPa_abs", "runtime", "no", "validated", "medium", ...
    "Anode inlet pressure setpoint.", "active");
add("anode.humidifierRH", "Anode humidifier RH", "anode", "-", ...
    params.anode.humidifier.default_rh.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "anode_humidifier_rh", "runtime", "no", ...
    "validated", "medium", "Anode inlet relative humidity command.", "active");
add("anode.recirculationBaseCommand", "Anode recirculation base", ...
    "anode", "-", params.anode.recirculation.base_command.value, 0, 1, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_recirculation_base", "runtime", "no", "validated", "medium", ...
    "Anode recirculation base command.", "active");
add("anode.recirculationCurrentGain_A_inv", ...
    "Anode recirculation current gain", "anode", "1/A", ...
    params.anode.recirculation.current_gain_A_inv.value, 0, 1, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_recirculation_current_gain_A_inv", "runtime", "no", ...
    "validated", "medium", "Current-related anode recirculation compensation.", "active");
add("anode.purgeEnabled", "Anode purge enabled", "anode", "-", ...
    params.anode.purge.enabled.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "anode_purge_enable", "runtime", "no", ...
    "validated", "medium", "Anode purge on/off command.", "active");
add("anode.purgeOnN2MoleFraction", "Anode purge-on N2 threshold", ...
    "anode", "-", params.anode.purge.on_n2_mole_fraction.value, 0, 1, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_purge_on_n2_mole_fraction", "runtime", "no", "validated", "medium", ...
    "N2 fraction that opens the purge path.", "active");
add("anode.purgeOffN2MoleFraction", "Anode purge-off N2 threshold", ...
    "anode", "-", params.anode.purge.off_n2_mole_fraction.value, 0, 1, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_purge_off_n2_mole_fraction", "runtime", "no", "validated", "medium", ...
    "N2 fraction that closes the purge path.", "active");

add("stack.numCells", "Stack cell count", "stack", "-", ...
    params.stack.num_cells.value, 1, 1000, "platform_default", ...
    "stack_num_cells", "", "", "stack", "compile", "validated", "high", ...
    "Number of cells used by the active stack model.", "active");
add("stack.area_cm2", "Stack active area", "stack", "cm^2", ...
    params.stack.area_cm2.value, 1, 1000, "platform_default", ...
    "stack_area", "", "", "stack", "compile", "validated", "high", ...
    "Active electrochemical area of each stack cell.", "active");
add("stack.iL_A_cm2", "Stack limiting current density", "stack", ...
    "A/cm^2", params.stack.iL_A_cm2.value, 1e-3, 5, "platform_default", ...
    "stack_iL", "", "", "stack", "compile", "validated", "high", ...
    "Limiting current density used by the active electrochemical model.", "active");
add("stack.io_A_cm2", "Stack exchange current density", "stack", ...
    "A/cm^2", params.stack.io_A_cm2.value, 1e-8, 0.1, "platform_default", ...
    "stack_io", "", "", "stack", "compile", "validated", "high", ...
    "Exchange current density used by the active electrochemical model.", "active");

add("thermal.stackTemperatureSet_C", "Stack temperature setpoint", "thermal", ...
    "degC", params.thermal.stack_temperature_set_C.value, 60, 100, ...
    "platform_default", "routeA_stack_temperature_set_C", "", ...
    "stack_temperature_set_C", "runtime", "no", "validated", "medium", ...
    "Cooling-system stack temperature setpoint; the current model uses the same T_stack path as cathode humidifier TIn/RH temperature reference.", "active");

add("solver.stopTime_s", "Simulation stop time", "solver", "s", ...
    params.numerics.stopTime_s.value, 0, Inf, "platform_default", "", "", "", ...
    "study", "no", "validated", "low", "Simulation stop time.", "active");
add("solver.solver", "Variable-step solver", "solver", "-", ...
    params.numerics.solver.value, [], [], "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Active variable-step solver name.", "active");
add("solver.relTol", "Relative tolerance", "solver", "-", ...
    params.numerics.relTol.value, eps, 1, "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Variable-step solver relative tolerance.", "active");
add("solver.absTol", "Absolute tolerance", "solver", "-", ...
    params.numerics.absTol.value, eps, Inf, "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Variable-step solver absolute tolerance.", "active");
add("solver.maxStep_s", "Maximum solver step", "solver", "s", ...
    params.numerics.maxStep_s.value, 0, Inf, "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Maximum solver step size.", "active");

% Inventory every platform-default leaf that is not yet an active input.
entries = appendPlatformLeaves(entries, params, '');

registry = struct();
registry.schemaVersion = "RouteA_Parameter_Registry_v01";
registry.model = string(paths.modelName);
registry.sourceFunction = "routeA_platform_default_parameters";
registry.entries = entries;
registry.count = numel(entries);
registry.activeCount = sum(arrayfun(@(x) x.status == "active", entries));
registry.inventoryCount = sum(arrayfun(@(x) x.status == "inventory", entries));
registry.panelBasicCount = sum(arrayfun(@(x) x.panelExposure == "basic", entries));
registry.panelAdvancedCount = sum(arrayfun(@(x) x.panelExposure == "advanced", entries));
registry.generatedAt = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

    function add(canonicalName, displayName, domain, unit, defaultValue, ...
            minimum, maximum, source, modelWorkspaceVariable, blockParameter, ...
            profileField, tunableClass, requiresCompile, validationLevel, ...
            riskLevel, description, status)
        entry = entryTemplate();
        entry.canonicalName = string(canonicalName);
        entry.displayName = string(displayName);
        entry.domain = string(domain);
        entry.unit = string(unit);
        entry.defaultValue = defaultValue;
        entry.minimum = minimum;
        entry.maximum = maximum;
        entry.source = string(source);
        entry.modelWorkspaceVariable = string(modelWorkspaceVariable);
        entry.blockParameter = string(blockParameter);
        entry.profileField = string(profileField);
        entry.tunableClass = string(tunableClass);
        entry.requiresCompile = string(requiresCompile);
        entry.validationLevel = string(validationLevel);
        entry.riskLevel = string(riskLevel);
        entry.description = string(description);
        entry.status = string(status);
        entry = applyPanelMetadata(entry);
        entries(end + 1) = entry;
    end
end

function entries = appendPlatformLeaves(entries, value, prefix)
if isstruct(value) && isscalar(value) && ...
        isfield(value, 'value') && isfield(value, 'unit') && ...
        isfield(value, 'source') && isfield(value, 'description')
    entry = entryTemplate();
    entry.canonicalName = "platform." + string(prefix);
    entry.displayName = entry.canonicalName;
    entry.domain = firstToken(prefix);
    entry.unit = string(value.unit);
    entry.defaultValue = value.value;
    entry.minimum = [];
    entry.maximum = [];
    entry.source = "routeA_platform_default_parameters." + string(prefix);
    entry.modelWorkspaceVariable = "";
    entry.blockParameter = "";
    entry.profileField = "";
    entry.tunableClass = "inventory";
    entry.requiresCompile = "unknown";
    entry.validationLevel = "inventory";
    entry.riskLevel = "unknown";
    entry.description = string(value.description);
    entry.status = "inventory";
    entry = applyPanelMetadata(entry);
    entries(end + 1) = entry;
    return;
end

if ~isstruct(value) || ~isscalar(value)
    return;
end
names = fieldnames(value);
for idx = 1:numel(names)
    field = names{idx};
    if isempty(prefix)
        childPrefix = field;
    else
        childPrefix = [prefix '.' field];
    end
    entries = appendPlatformLeaves(entries, value.(field), childPrefix);
end
end

function token = firstToken(value)
parts = split(string(value), '.');
token = parts(1);
end

function entry = applyPanelMetadata(entry)
% Keep panel exposure and application semantics in the same registry row.
if entry.status == "inventory"
    entry.panelExposure = "inventory";
    entry.applyAction = "read_only";
    entry.validationGate = "not_opened";
    entry.unsupportedReason = "Range, model mapping, compile behavior, or response is not closed.";
    return;
end
if entry.status == "unresolved"
    entry.panelExposure = "unresolved";
    entry.applyAction = "read_only";
    entry.validationGate = "not_opened";
    entry.unsupportedReason = "The active model interface is not resolved.";
    return;
end

basicNames = [ ...
    "electrical.mode", "electrical.current.profile", ...
    "electrical.power.profile", "electrical.voltage.profile", ...
    "cathode.airControlMode", "cathode.targetOer", ...
    "cathode.targetMdot_kg_s", "cathode.directCommand", ...
    "cathode.outletPressure_MPa_abs", "cathode.humidifierRH", ...
    "cathode.humidifierEnabled", "cegr.enabled", "cegr.targetRatio", ...
    "solver.stopTime_s", "thermal.stackTemperatureSet_C"];
if any(entry.canonicalName == basicNames)
    entry.panelExposure = "basic";
else
    entry.panelExposure = "advanced";
end

if entry.requiresCompile == "compile"
    entry.applyAction = "compile_and_smoke";
    entry.validationGate = "compile_gate";
else
    entry.applyAction = "collect_and_validate";
    entry.validationGate = "case_validation";
end
entry.unsupportedReason = "";
end

function entry = entryTemplate()
entry = struct( ...
    'canonicalName', "", ...
    'displayName', "", ...
    'domain', "", ...
    'unit', "", ...
    'defaultValue', [], ...
    'minimum', [], ...
    'maximum', [], ...
    'source', "", ...
    'modelWorkspaceVariable', "", ...
    'blockParameter', "", ...
    'profileField', "", ...
    'tunableClass', "", ...
    'requiresCompile', "", ...
    'validationLevel', "", ...
    'riskLevel', "", ...
    'description', "", ...
    'status', "", ...
    'panelExposure', "", ...
    'applyAction', "", ...
    'validationGate', "", ...
    'unsupportedReason', "");
end
