% Route A Stage 1 normal-operation cEGR target-transition audit.
%
% The one platform_default initial state represents j = 0.1 A/cm^2,
% CEGR-enabled topology, and a mode-1 zero-target near-zero reference. Both
% the cEGR transition and the zero-target reference begin from that exact
% operating point.  The saved Simulink operating point retains its model
% time, so cfg research times are translated to absolute model times here.
% The physical Variant remains mode 1 throughout every same-state comparison.
% Strict mode-0 isolation is verified separately and is not a transition
% baseline because it cannot reuse this operating point.

scriptDir = fileparts(mfilename('fullpath'));
modelDir = fullfile(scriptDir, '..', '..', '01_模型', 'RouteA_GasMixture_Derived');
model = 'PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01';
modelFile = fullfile(modelDir, [model '.slx']);
oldDir = pwd;
addpath(scriptDir);
addpath(modelDir);
cd(modelDir);
routeA_stage1_cleanup = onCleanup(@() routeA_restore_model_and_folder( ...
    model, modelFile, oldDir));

cfg = transitionConfig(modelDir);
baselineAudit = runZeroTargetBaseline(model, modelFile, modelDir, cfg);
resetModelFromDisk(model, modelFile);
refreshModelWorkspace(model);
routeA_apply_constant_current_step(model, ...
    cfg.initialStateMetadata.targetCurrentA, cfg.targetCurrentA);

in = Simulink.SimulationInput(model);
[in, initialStateMetadata] = routeA_attach_platform_default_initial_state( ...
    in, model, modelDir, cfg.initialStateFile);
routeA_mark_observability_signals(model);
in = in.setModelParameter( ...
    'StopTime', sprintf('%.16g', cfg.modelStopTime_s), ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SimscapeLogType', 'all');
in = in.setVariable('routeA_air_control_mode_id', 2, 'Workspace', model);
in = in.setVariable('routeA_target_oer', cfg.targetAirEquivalentOer, ...
    'Workspace', model);
in = in.setVariable('routeA_egr_control_mode_id', 1, 'Workspace', model);
in = in.setVariable('routeA_cegr_valve_mode_id', 1, 'Workspace', model);
in = in.setVariable('routeA_target_egr_ratio_comp_in', 0, ...
    'Workspace', model);
in = in.setVariable('routeA_egr_target_input_mode_id', 1, ...
    'Workspace', model);
in = in.setVariable('routeA_target_egr_ratio_comp_in_profile', ...
    cfg.profile, 'Workspace', model);

out = sim(in);
audit = collectAudit(out, model, cfg);
audit.initialState = initialStateMetadata;
audit.zeroTargetBaseline = baselineAudit.systemImpact;
audit.zeroTargetBaselineSteadyState = baselineAudit.steadyState;
audit.systemImpactDeltaMidMinusZeroTarget = impactDelta( ...
    audit.systemImpact.mid, baselineAudit.systemImpact.mid);
audit.systemImpactDeltaPostMinusZeroTarget = impactDelta( ...
    audit.systemImpact.post, baselineAudit.systemImpact.post);
audit.postVsMatchedZeroTarget = returnToInitialStats( ...
    baselineAudit.systemImpact.post, audit.systemImpact.post, cfg);
audit.postVsMatchedZeroTargetPassed = audit.postVsMatchedZeroTarget.passed;
audit.passed = audit.passed && audit.postVsMatchedZeroTargetPassed;
assignin('base', 'routeA_stage1_cegr_transition_audit', audit);
displayAudit(audit);
clear out;
clear routeA_stage1_cleanup;

function cfg = transitionConfig(modelDir)
initialStateFile = fullfile(modelDir, ...
    'RouteA_platform_default_initial_state.mat');
loaded = load(initialStateFile, 'routeA_initial_metadata');
if ~isfield(loaded, 'routeA_initial_metadata')
    error('RouteA:InvalidPlatformDefaultInitialState', ...
        'The platform_default initial-state metadata is unavailable.');
end
metadata = loaded.routeA_initial_metadata;
requiredFields = {'snapshotTimeS', 'targetCurrentA', ...
    'cegrTopologyEnabled', 'cegrValveModeId', 'egrReferenceKind'};
if ~builtin('all', isfield(metadata, requiredFields))
    error('RouteA:InvalidPlatformDefaultInitialStateMetadata', ...
        'The platform_default initial-state metadata is incomplete.');
end
if ~metadata.cegrTopologyEnabled || metadata.cegrValveModeId ~= 1 || ...
        string(metadata.egrReferenceKind) ~= "mode1_zero_target_near_zero"
    error('RouteA:InitialStateModeMismatch', ...
        'The transition audit requires a mode-1 zero-target formal state.');
end

cfg = struct();
cfg.initialStateFile = initialStateFile;
cfg.initialStateMetadata = metadata;
cfg.researchStartTime_s = metadata.snapshotTimeS;
cfg.researchDuration_s = 600;
cfg.modelStopTime_s = cfg.researchStartTime_s + cfg.researchDuration_s;
cfg.targetCurrentA = metadata.targetCurrentA;
cfg.currentTrackingTolerance_A = 5e-3;
cfg.targetAirEquivalentOer = 3;
researchProfile = [ ...
    0, 0; ...
    60, 0; ...
    60.01, 0.10; ...
    240, 0.10; ...
    240.01, 0; ...
    600, 0];
cfg.profile = researchProfile;
cfg.profile(:, 1) = cfg.researchStartTime_s + cfg.profile(:, 1);
cfg.riseCommandTime = cfg.researchStartTime_s + 60.01;
cfg.fallCommandTime = cfg.researchStartTime_s + 240.01;
cfg.transitionLowRatio = 0.01;
cfg.transitionHighRatio = 0.09;
cfg.logicalWindows_s = struct( ...
    'pre', [30, 59], ...
    'mid', [210, 239], ...
    'post', [540, 599]);
cfg.windows = struct( ...
    'pre', cfg.researchStartTime_s + cfg.logicalWindows_s.pre, ...
    'mid', cfg.researchStartTime_s + cfg.logicalWindows_s.mid, ...
    'post', cfg.researchStartTime_s + cfg.logicalWindows_s.post);
cfg.egrTolerance = 0.01;
cfg.tailSpanLimit = 0.01;
cfg.lambdaLowerBound = 1;
cfg.stackCells = 400;
cfg.faradayConstant_C_mol = 96485.33212;
cfg.molarMass_kg_mol = [0.0280134, 0.0319988, 0.00201588, 0.01801528];
cfg.gas = struct( ...
    'n2Index', 1, ...
    'o2Index', 2, ...
    'h2oIndex', 4, ...
    'absoluteResidualTolerance_kg_s', 5e-4, ...
    'relativeResidualTolerance', 0.05);
cfg.steadySpan = struct( ...
    'egrRatio', 0.002, ...
    'egrMdot_kg_s', 5e-4, ...
    'freshAirMdot_kg_s', 5e-4, ...
    'inletTotalMdot_kg_s', 5e-4, ...
    'outletTotalMdot_kg_s', 5e-4, ...
    'stackCurrent_A', 0.5, ...
    'stackVoltage_V', 0.5, ...
    'stackPower_kW', 0.05, ...
    'stackTemperature_C', 0.5, ...
    'compressorMdot_kg_s', 5e-4, ...
    'compressorTemperature_K', 0.5, ...
    'rhCaIn', 0.02, ...
    'rhCaOut', 0.02, ...
    'waterSeparator', 5e-5, ...
    'exhaustMdot_kg_s', 5e-4, ...
    'lambdaCaIn', 0.02, ...
    'inletO2MassFraction', 0.002, ...
    'outletO2MoleFraction', 0.002);
cfg.returnTolerance = struct( ...
    'egrMdot_kg_s', 5e-4, ...
    'freshAirMdot_kg_s', 5e-4, ...
    'inletTotalMdot_kg_s', 5e-4, ...
    'outletTotalMdot_kg_s', 5e-4, ...
    'stackCurrent_A', 0.5, ...
    'stackVoltage_V', 0.5, ...
    'stackPower_kW', 0.05, ...
    'stackTemperature_C', 0.5, ...
    'compressorMdot_kg_s', 5e-4, ...
    'compressorTemperature_K', 0.5, ...
    'rhCaIn', 0.02, ...
    'rhCaOut', 0.02, ...
    'waterSeparator', 5e-5, ...
    'exhaustMdot_kg_s', 5e-4, ...
    'inletO2MassFraction', 0.002, ...
    'inletN2MassFraction', 0.002, ...
    'outletO2MoleFraction', 0.002);
end

function audit = collectAudit(out, model, cfg)
logsout = out.logsout;
ratio = loggedTimeseries(logsout, 'routeA_egr_ratio_comp_in');
area = loggedTimeseries(logsout, 'routeA_egr_valve_area_cmd');
pUp = loggedTimeseries(logsout, 'routeA_p_egr_valve_up');
pDown = loggedTimeseries(logsout, 'routeA_p_egr_valve_down');
compMdot = loggedTimeseries(logsout, 'routeA_mdot_comp_inlet');
compP = loggedTimeseries(logsout, 'routeA_p_comp_inlet');
compT = loggedTimeseries(logsout, 'routeA_T_comp_inlet');
compYi = loggedTimeseries(logsout, 'routeA_yi_comp_inlet');
outletYi = loggedTimeseries(logsout, 'routeA_yi_outlet');
compCmd = loggedTimeseries(logsout, 'routeA_compressor_cmd');
compRpm = loggedTimeseries(logsout, 'routeA_compressor_rpm');
egrMdot = loggedTimeseries(logsout, 'routeA_egr_mdot');
stackCurrent = loggedTimeseries(logsout, 'routeA_stack_current_A');
stackVoltage = loggedTimeseries(logsout, 'routeA_stack_voltage_V');
stackPower = timeseries( ...
    stackCurrent.Data .* stackVoltage.Data * 1e-3, stackCurrent.Time);
stackTemperature = loggedTimeseries(logsout, 'routeA_stack_temperature_C');
rhIn = waterRelativeHumidity(outputTimeseries(out, logsout, ...
    'routeA_RH_ca_in', 'routeA_RH_ca_in_ts'), 'routeA_RH_ca_in');
rhOut = waterRelativeHumidity(outputTimeseries(out, logsout, ...
    'routeA_RH_ca_out', 'routeA_RH_ca_out_ts'), 'routeA_RH_ca_out');
waterSep = outputTimeseries(out, logsout, 'routeA_m_water_sep', ...
    'routeA_m_water_sep_ts');
exhaustMdot = outputTimeseries(out, logsout, 'routeA_exhaust_mdot', ...
    'routeA_exhaust_mdot_ts');

target = profileValue(cfg.profile, ratio.Time);
windows = struct();
windowNames = fieldnames(cfg.windows);
for idx = 1:numel(windowNames)
    name = windowNames{idx};
    windows.(name) = windowStats(ratio, target, cfg.windows.(name));
end

speciesMdot = out.get('routeA_mdot_species_ca_in_ts');
stackCurrentForLambda = out.get('routeA_stack_current_A_ts');
lambda = inletOxygenStoich(speciesMdot, stackCurrentForLambda);
[species, speciesTotal, speciesMassFraction] = inletSpeciesMetrics(speciesMdot);
inletTotalMdot = timeseries(speciesTotal, speciesMdot.Time);
inletO2MassFraction = timeseries(speciesMassFraction(:, 2), speciesMdot.Time);
compYiData = compositionMatrix(compYi, 'routeA_yi_comp_inlet');
compYiMassFraction = moleFractionToMassFraction(compYiData, ...
    cfg.molarMass_kg_mol);
outletYiData = compositionMatrix(outletYi, 'routeA_yi_outlet');
outletYiMassFraction = moleFractionToMassFraction(outletYiData, ...
    cfg.molarMass_kg_mol);
outletO2MoleFraction = timeseries(outletYiData(:, cfg.gas.o2Index), ...
    outletYi.Time);
externalMoleFraction = externalAirMoleFraction(model);
externalMassFraction = moleFractionToMassFraction(externalMoleFraction, ...
    cfg.molarMass_kg_mol);
egrMdotAbs = timeseries(abs(egrMdot.Data), egrMdot.Time);
egrAtCompTime = interp1(egrMdot.Time, egrMdotAbs.Data, ...
    compMdot.Time, 'linear', 'extrap');
freshAirApprox = timeseries(abs(compMdot.Data) - egrAtCompTime, ...
    compMdot.Time);
egrAtOutletTime = interpolateMagnitude(egrMdot, outletYi.Time);
exhaustAtOutletTime = interpolateMagnitude(exhaustMdot, outletYi.Time);
outletTotalMdot = timeseries(egrAtOutletTime + exhaustAtOutletTime, ...
    outletYi.Time);

systemImpact = struct();
windowNames = fieldnames(cfg.windows);
for idx = 1:numel(windowNames)
    name = windowNames{idx};
    window = cfg.windows.(name);
    systemImpact.(name) = systemImpactStats(window, ...
        stackCurrent, stackVoltage, stackPower, stackTemperature, ...
        compMdot, compP, compT, compYi, compCmd, compRpm, ...
        egrMdotAbs, freshAirApprox, ...
        rhIn, rhOut, waterSep, exhaustMdot, inletTotalMdot, ...
        species, speciesMdot.Time, ...
        compYiData, compYiMassFraction, ...
        outletTotalMdot, outletYiData, outletYiMassFraction, outletYi.Time, ...
        externalMoleFraction, externalMassFraction);
end
gasConservation = struct();
for idx = 1:numel(windowNames)
    name = windowNames{idx};
    gasConservation.(name) = gasConservationStats( ...
        systemImpact.(name), cfg);
end
steadyState = struct();
for idx = 1:numel(windowNames)
    name = windowNames{idx};
    window = cfg.windows.(name);
    steadyState.(name) = steadyStateStats(window, cfg, ratio, ...
        stackCurrent, stackVoltage, stackPower, stackTemperature, ...
        compMdot, compT, rhIn, rhOut, waterSep, exhaustMdot, ...
        lambda, inletO2MassFraction, inletTotalMdot, outletTotalMdot, ...
        egrMdotAbs, freshAirApprox, outletO2MoleFraction);
end
steadyPassed = builtin('all', structfun(@(s) s.passed, steadyState));
withinRunPreToPost = returnToInitialStats(systemImpact.pre, ...
    systemImpact.post, cfg);
transitionTiming = transitionTimingStats(ratio, cfg);
inletO2OperationalMask = speciesMdot.Time >= cfg.windows.pre(1) & ...
    speciesMdot.Time <= cfg.windows.post(2);
inletO2NonfiniteOperationalCount = nonfiniteCount( ...
    inletO2MassFraction.Data(inletO2OperationalMask));
inletO2NonfiniteStartupCount = nonfiniteCount(inletO2MassFraction.Data) - ...
    inletO2NonfiniteOperationalCount;

mw = get_param(model, 'ModelWorkspace');
maxArea = mw.getVariable('cegr_valve_max_area');
areaFraction = area.Data / maxArea;
pressureDeltaMPa = (pUp.Data - pDown.Data) * 1e-6;

finiteCounts = struct( ...
    'egrRatio', nonfiniteCount(ratio.Data), ...
    'valveArea', nonfiniteCount(area.Data), ...
    'pressureUpstream', nonfiniteCount(pUp.Data), ...
    'pressureDownstream', nonfiniteCount(pDown.Data), ...
    'compressorMdot', nonfiniteCount(compMdot.Data), ...
    'compressorPressure', nonfiniteCount(compP.Data), ...
    'compressorTemperature', nonfiniteCount(compT.Data), ...
    'compressorInletYi', nonfiniteCount(compYi.Data), ...
    'compressorCommand', nonfiniteCount(compCmd.Data), ...
    'compressorRpm', nonfiniteCount(compRpm.Data), ...
    'egrMdot', nonfiniteCount(egrMdot.Data), ...
    'outletYi', nonfiniteCount(outletYiData), ...
    'outletTotalMdot', nonfiniteCount(outletTotalMdot.Data), ...
    'stackCurrent', nonfiniteCount(stackCurrent.Data), ...
    'stackVoltage', nonfiniteCount(stackVoltage.Data), ...
    'stackPower', nonfiniteCount(stackPower.Data), ...
    'stackTemperature', nonfiniteCount(stackTemperature.Data), ...
    'rhCaIn', nonfiniteCount(rhIn.Data), ...
    'rhCaOut', nonfiniteCount(rhOut.Data), ...
    'waterSeparator', nonfiniteCount(waterSep.Data), ...
    'exhaustMdot', nonfiniteCount(exhaustMdot.Data), ...
    'inletSpeciesMdot', nonfiniteCount(species), ...
    'inletTotalMdot', nonfiniteCount(inletTotalMdot.Data), ...
    'inletO2MassFraction', nonfiniteCount(inletO2MassFraction.Data), ...
    'lambdaCaIn', nonfiniteCount(lambda.Data));
finiteCountsPhysical = rmfield(finiteCounts, ...
    {'lambdaCaIn', 'inletO2MassFraction'});
finiteOk = builtin('all', struct2array(finiteCountsPhysical) == 0) && ...
    inletO2NonfiniteOperationalCount == 0;
trackingPassed = windows.pre.meanAbsError <= cfg.egrTolerance && ...
    windows.mid.meanAbsError <= cfg.egrTolerance && ...
    windows.post.meanAbsError <= cfg.egrTolerance && ...
    windows.pre.tailSpan <= cfg.tailSpanLimit && ...
    windows.mid.tailSpan <= cfg.tailSpanLimit && ...
    windows.post.tailSpan <= cfg.tailSpanLimit;
pressurePassed = mean(pressureDeltaMPa(windowMask(pUp, cfg.windows.mid))) > 0;
areaPassed = min(areaFraction) >= 0 && max(areaFraction) < 1 - 1e-6;
lambdaOperationalMask = lambda.Time >= cfg.windows.pre(1) & ...
    lambda.Time <= cfg.windows.post(2);
lambdaNonfiniteOperationalCount = nonfiniteCount( ...
    lambda.Data(lambdaOperationalMask));
lambdaNonfiniteStartupCount = finiteCounts.lambdaCaIn - ...
    lambdaNonfiniteOperationalCount;
lambdaOperationalMin = min(lambda.Data(lambdaOperationalMask));
lambdaPassed = lambdaOperationalMin > cfg.lambdaLowerBound;
currentOperationalMask = stackCurrent.Time >= cfg.researchStartTime_s & ...
    stackCurrent.Time <= cfg.modelStopTime_s;
currentTrackingErrorA = max(abs( ...
    stackCurrent.Data(currentOperationalMask) - cfg.targetCurrentA));
currentPassed = currentTrackingErrorA <= cfg.currentTrackingTolerance_A;

audit = struct();
audit.timestamp = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
audit.model = string(model);
audit.researchStartModelTime_s = cfg.researchStartTime_s;
audit.researchDuration_s = cfg.researchDuration_s;
audit.modelStopTime_s = cfg.modelStopTime_s;
audit.profile = cfg.profile;
audit.logicalWindows_s = cfg.logicalWindows_s;
audit.windows = windows;
audit.systemImpact = systemImpact;
audit.gasConservation = gasConservation;
audit.gasObservability = gasObservability();
audit.gasConservationPassed = builtin('all', ...
    structfun(@(s) s.passed, gasConservation));
audit.steadyState = steadyState;
audit.steadyPassed = steadyPassed;
audit.withinRunPreToPost = withinRunPreToPost;
audit.withinRunPreToPostPassed = withinRunPreToPost.passed;
audit.systemImpactDeltaMidMinusPre = impactDelta( ...
    systemImpact.mid, systemImpact.pre);
audit.transitionTiming = transitionTiming;
audit.inletSpeciesComponentIndexO2 = 2;
audit.targetCurrentA = cfg.targetCurrentA;
audit.currentTrackingMaxErrorA = currentTrackingErrorA;
audit.actualPowerKW = stackPower.Data(end);
audit.stackPowerTailSpanKW = tailSpan(stackPower.Data);
audit.lambdaCaInMin = min(lambda.Data);
audit.lambdaCaInOperationalMin = lambdaOperationalMin;
audit.pressureDeltaMidMPa = mean(pressureDeltaMPa(windowMask(pUp, cfg.windows.mid)));
audit.valveAreaFractionMin = min(areaFraction);
audit.valveAreaFractionMax = max(areaFraction);
audit.compressorMdotFinalKgS = compMdot.Data(end);
audit.compressorPressureFinalPa = compP.Data(end);
audit.compressorTemperatureFinal = compT.Data(end);
audit.rhCaInFinal = rhIn.Data(end);
audit.rhCaOutFinal = rhOut.Data(end);
audit.waterSepFinal = waterSep.Data(end);
audit.exhaustMdotFinalKgS = exhaustMdot.Data(end);
audit.nonfiniteCounts = finiteCounts;
audit.lambdaNonfiniteOperationalCount = lambdaNonfiniteOperationalCount;
audit.lambdaNonfiniteStartupCount = lambdaNonfiniteStartupCount;
audit.inletO2NonfiniteOperationalCount = inletO2NonfiniteOperationalCount;
audit.inletO2NonfiniteStartupCount = inletO2NonfiniteStartupCount;
audit.finiteOk = finiteOk && lambdaNonfiniteOperationalCount == 0;
audit.trackingPassed = trackingPassed;
audit.pressurePassed = pressurePassed;
audit.areaPassed = areaPassed;
audit.lambdaPassed = lambdaPassed;
audit.currentPassed = currentPassed;
audit.passed = finiteOk && trackingPassed && pressurePassed && ...
    areaPassed && lambdaPassed && currentPassed && steadyPassed && ...
    audit.gasConservationPassed;
end

function stats = windowStats(signal, target, window)
mask = signal.Time >= window(1) & signal.Time <= window(2);
actual = signal.Data(mask);
expected = target(mask);
stats = struct();
stats.start_s = window(1);
stats.end_s = window(2);
stats.targetMean = mean(expected);
stats.actualMean = mean(actual);
stats.meanAbsError = mean(abs(actual - expected));
stats.actualMin = min(actual);
stats.actualMax = max(actual);
stats.tailSpan = max(actual) - min(actual);
end

function stats = systemImpactStats(window, stackCurrent, stackVoltage, ...
    stackPower, stackTemperature, compMdot, compP, compT, compYi, ...
    compCmd, compRpm, egrMdot, ...
    freshAir, rhIn, rhOut, waterSep, exhaustMdot, inletTotalMdot, ...
    speciesMdot, speciesTime, ...
    compYiData, compYiMassFraction, ...
    outletTotalMdot, outletYiData, outletYiMassFraction, outletYiTime, ...
    externalMoleFraction, externalMassFraction)
stats = struct();
stats.window_s = window;
stats.stackCurrent_A = windowMean(stackCurrent, window);
stats.stackVoltage_V = windowMean(stackVoltage, window);
stats.stackPower_kW = windowMean(stackPower, window);
stats.stackTemperature_C = windowMean(stackTemperature, window);
stats.compressorMdot_kg_s = windowMean(compMdot, window);
stats.compressorPressure_Pa = windowMean(compP, window);
stats.compressorTemperature_K = windowMean(compT, window);
stats.compressorCommand = windowMean(compCmd, window);
stats.compressorRpm = windowMean(compRpm, window);
stats.egrMdot_kg_s = windowMean(egrMdot, window);
stats.freshAirApprox_kg_s = windowMean(freshAir, window);
stats.rhCaIn = windowMean(rhIn, window);
stats.rhCaOut = windowMean(rhOut, window);
stats.waterSeparator = windowMean(waterSep, window);
stats.exhaustMdot_kg_s = windowMean(exhaustMdot, window);
stats.cathodeInletTotalMdot_kg_s = windowMean(inletTotalMdot, window);
mask = speciesTime >= window(1) & speciesTime <= window(2);
stats.cathodeInletSpeciesMdot_kg_s = mean(speciesMdot(mask, :), 1);
stats.cathodeInletSpeciesMassFraction = normalizeComposition( ...
    stats.cathodeInletSpeciesMdot_kg_s);
compYiMask = compYi.Time >= window(1) & compYi.Time <= window(2);
stats.compressorInletYi = mean(compYiData(compYiMask, :), 1);
stats.compressorInletMassFraction = mean(compYiMassFraction(compYiMask, :), 1);
stats.compressorInletSpeciesMdot_kg_s = ...
    abs(stats.compressorMdot_kg_s) * stats.compressorInletMassFraction;
outletMask = outletYiTime >= window(1) & outletYiTime <= window(2);
stats.cathodeOutletTotalMdot_kg_s = windowMean(outletTotalMdot, window);
stats.cathodeOutletYi = mean(outletYiData(outletMask, :), 1);
stats.cathodeOutletSpeciesMassFraction = normalizeComposition( ...
    mean(outletYiMassFraction(outletMask, :), 1));
stats.cathodeOutletSpeciesMdot_kg_s = ...
    stats.cathodeOutletTotalMdot_kg_s * ...
    stats.cathodeOutletSpeciesMassFraction;
stats.cathodeRecycleMdot_kg_s = stats.egrMdot_kg_s;
stats.cathodeRecycleYi = stats.cathodeOutletYi;
stats.cathodeRecycleSpeciesMassFraction = ...
    stats.cathodeOutletSpeciesMassFraction;
stats.freshAirMdot_kg_s = stats.freshAirApprox_kg_s;
stats.externalMoleFraction = externalMoleFraction;
stats.externalMassFraction = externalMassFraction;
stats.freshAirSpeciesMdot_kg_s = ...
    stats.freshAirMdot_kg_s * externalMassFraction;
end

function stats = gasConservationStats(impact, cfg)
n2 = cfg.gas.n2Index;
o2 = cfg.gas.o2Index;
h2o = cfg.gas.h2oIndex;
inlet = impact.cathodeInletSpeciesMdot_kg_s;
outlet = impact.cathodeOutletSpeciesMdot_kg_s;
fresh = impact.freshAirSpeciesMdot_kg_s;
recycle = impact.cathodeRecycleMdot_kg_s * ...
    impact.cathodeOutletSpeciesMassFraction;
compressor = impact.compressorInletSpeciesMdot_kg_s;
mixExpected = fresh + recycle;
stackCurrent = abs(impact.stackCurrent_A);
o2Faraday = cfg.stackCells * stackCurrent / ...
    (4 * cfg.faradayConstant_C_mol) * cfg.molarMass_kg_mol(o2);
stats = struct();
stats.window_s = impact.window_s;
stats.inletSpeciesMdot_kg_s = inlet;
stats.outletSpeciesMdot_kg_s = outlet;
stats.freshAirSpeciesMdot_kg_s = fresh;
stats.recycleSpeciesMdot_kg_s = recycle;
stats.compressorInletSpeciesMdot_kg_s = compressor;
stats.mixExpectedSpeciesMdot_kg_s = mixExpected;
stats.n2StackResidual_kg_s = inlet(n2) - outlet(n2);
stats.o2NetConsumption_kg_s = inlet(o2) - outlet(o2);
stats.o2FaradayConsumption_kg_s = o2Faraday;
stats.o2FaradayResidual_kg_s = ...
    stats.o2NetConsumption_kg_s - o2Faraday;
stats.h2oNetResidual_kg_s = inlet(h2o) - outlet(h2o);
stats.mixResidualSpeciesMdot_kg_s = compressor - mixExpected;
stats.n2MixResidual_kg_s = stats.mixResidualSpeciesMdot_kg_s(n2);
stats.o2MixResidual_kg_s = stats.mixResidualSpeciesMdot_kg_s(o2);
stats.h2oMixResidual_kg_s = stats.mixResidualSpeciesMdot_kg_s(h2o);
stats.outletFlowClosure_kg_s = impact.cathodeOutletTotalMdot_kg_s - ...
    impact.cathodeRecycleMdot_kg_s - impact.exhaustMdot_kg_s;
stats.n2StackPassed = residualPassed(stats.n2StackResidual_kg_s, ...
    max(abs(inlet(n2)), abs(outlet(n2))), cfg.gas);
stats.o2FaradayPassed = residualPassed(stats.o2FaradayResidual_kg_s, ...
    max(abs(stats.o2NetConsumption_kg_s), abs(o2Faraday)), cfg.gas);
stats.n2MixPassed = residualPassed(stats.n2MixResidual_kg_s, ...
    max(abs(compressor(n2)), abs(mixExpected(n2))), cfg.gas);
stats.o2MixPassed = residualPassed(stats.o2MixResidual_kg_s, ...
    max(abs(compressor(o2)), abs(mixExpected(o2))), cfg.gas);
stats.finite = builtin('all', isfinite([ ...
    stats.n2StackResidual_kg_s, stats.o2FaradayResidual_kg_s, ...
    stats.n2MixResidual_kg_s, stats.o2MixResidual_kg_s, ...
    stats.outletFlowClosure_kg_s]));
stats.passed = stats.finite && stats.n2StackPassed && ...
    stats.o2FaradayPassed && stats.n2MixPassed && stats.o2MixPassed;
end

function passed = residualPassed(residual, reference, gasCfg)
tolerance = max(gasCfg.absoluteResidualTolerance_kg_s, ...
    gasCfg.relativeResidualTolerance * max(reference, 1e-12));
passed = isfinite(residual) && abs(residual) <= tolerance;
end

function value = windowMean(signal, window)
mask = signal.Time >= window(1) & signal.Time <= window(2);
value = mean(signal.Data(mask));
end

function stats = steadyStateStats(window, cfg, ratio, stackCurrent, ...
    stackVoltage, stackPower, stackTemperature, compMdot, compT, ...
    rhIn, rhOut, waterSep, exhaustMdot, lambda, inletO2, ...
    inletTotalMdot, outletTotalMdot, egrMdot, freshAirMdot, ...
    outletO2MoleFraction)
stats = struct();
stats.window_s = window;
stats.egrRatioSpan = signalSpan(ratio, window);
stats.egrMdotSpan_kg_s = signalSpan(egrMdot, window);
stats.freshAirMdotSpan_kg_s = signalSpan(freshAirMdot, window);
stats.inletTotalMdotSpan_kg_s = signalSpan(inletTotalMdot, window);
stats.outletTotalMdotSpan_kg_s = signalSpan(outletTotalMdot, window);
stats.stackCurrentSpan_A = signalSpan(stackCurrent, window);
stats.stackVoltageSpan_V = signalSpan(stackVoltage, window);
stats.stackPowerSpan_kW = signalSpan(stackPower, window);
stats.stackTemperatureSpan_C = signalSpan(stackTemperature, window);
stats.compressorMdotSpan_kg_s = signalSpan(compMdot, window);
stats.compressorTemperatureSpan_K = signalSpan(compT, window);
stats.rhCaInSpan = signalSpan(rhIn, window);
stats.rhCaOutSpan = signalSpan(rhOut, window);
stats.waterSeparatorSpan = signalSpan(waterSep, window);
stats.exhaustMdotSpan_kg_s = signalSpan(exhaustMdot, window);
stats.lambdaCaInSpan = signalSpan(lambda, window);
stats.inletO2MassFractionSpan = signalSpan(inletO2, window);
stats.outletO2MoleFractionSpan = signalSpan(outletO2MoleFraction, window);
stats.passed = stats.egrRatioSpan <= cfg.steadySpan.egrRatio && ...
    stats.egrMdotSpan_kg_s <= cfg.steadySpan.egrMdot_kg_s && ...
    stats.freshAirMdotSpan_kg_s <= cfg.steadySpan.freshAirMdot_kg_s && ...
    stats.inletTotalMdotSpan_kg_s <= cfg.steadySpan.inletTotalMdot_kg_s && ...
    stats.outletTotalMdotSpan_kg_s <= cfg.steadySpan.outletTotalMdot_kg_s && ...
    stats.stackCurrentSpan_A <= cfg.steadySpan.stackCurrent_A && ...
    stats.stackVoltageSpan_V <= cfg.steadySpan.stackVoltage_V && ...
    stats.stackPowerSpan_kW <= cfg.steadySpan.stackPower_kW && ...
    stats.stackTemperatureSpan_C <= cfg.steadySpan.stackTemperature_C && ...
    stats.compressorMdotSpan_kg_s <= cfg.steadySpan.compressorMdot_kg_s && ...
    stats.compressorTemperatureSpan_K <= cfg.steadySpan.compressorTemperature_K && ...
    stats.rhCaInSpan <= cfg.steadySpan.rhCaIn && ...
    stats.rhCaOutSpan <= cfg.steadySpan.rhCaOut && ...
    stats.waterSeparatorSpan <= cfg.steadySpan.waterSeparator && ...
    stats.exhaustMdotSpan_kg_s <= cfg.steadySpan.exhaustMdot_kg_s && ...
    stats.lambdaCaInSpan <= cfg.steadySpan.lambdaCaIn && ...
    stats.inletO2MassFractionSpan <= cfg.steadySpan.inletO2MassFraction && ...
    stats.outletO2MoleFractionSpan <= cfg.steadySpan.outletO2MoleFraction;
end

function stats = returnToInitialStats(initial, final, cfg)
stats = struct();
stats.egrMdot_kg_s = final.egrMdot_kg_s - initial.egrMdot_kg_s;
stats.freshAirMdot_kg_s = ...
    final.freshAirMdot_kg_s - initial.freshAirMdot_kg_s;
stats.inletTotalMdot_kg_s = ...
    final.cathodeInletTotalMdot_kg_s - initial.cathodeInletTotalMdot_kg_s;
stats.outletTotalMdot_kg_s = ...
    final.cathodeOutletTotalMdot_kg_s - initial.cathodeOutletTotalMdot_kg_s;
stats.stackCurrent_A = final.stackCurrent_A - initial.stackCurrent_A;
stats.stackVoltage_V = final.stackVoltage_V - initial.stackVoltage_V;
stats.stackPower_kW = final.stackPower_kW - initial.stackPower_kW;
stats.stackTemperature_C = final.stackTemperature_C - initial.stackTemperature_C;
stats.compressorMdot_kg_s = ...
    final.compressorMdot_kg_s - initial.compressorMdot_kg_s;
stats.compressorTemperature_K = ...
    final.compressorTemperature_K - initial.compressorTemperature_K;
stats.rhCaIn = final.rhCaIn - initial.rhCaIn;
stats.rhCaOut = final.rhCaOut - initial.rhCaOut;
stats.waterSeparator = final.waterSeparator - initial.waterSeparator;
stats.exhaustMdot_kg_s = ...
    final.exhaustMdot_kg_s - initial.exhaustMdot_kg_s;
stats.inletO2MassFraction = ...
    final.cathodeInletSpeciesMassFraction(2) - ...
    initial.cathodeInletSpeciesMassFraction(2);
stats.inletN2MassFraction = ...
    final.cathodeInletSpeciesMassFraction(1) - ...
    initial.cathodeInletSpeciesMassFraction(1);
stats.outletO2MoleFraction = final.cathodeOutletYi(2) - ...
    initial.cathodeOutletYi(2);
stats.passed = abs(stats.egrMdot_kg_s) <= cfg.returnTolerance.egrMdot_kg_s && ...
    abs(stats.freshAirMdot_kg_s) <= cfg.returnTolerance.freshAirMdot_kg_s && ...
    abs(stats.inletTotalMdot_kg_s) <= cfg.returnTolerance.inletTotalMdot_kg_s && ...
    abs(stats.outletTotalMdot_kg_s) <= cfg.returnTolerance.outletTotalMdot_kg_s && ...
    abs(stats.stackCurrent_A) <= cfg.returnTolerance.stackCurrent_A && ...
    abs(stats.stackVoltage_V) <= cfg.returnTolerance.stackVoltage_V && ...
    abs(stats.stackPower_kW) <= cfg.returnTolerance.stackPower_kW && ...
    abs(stats.stackTemperature_C) <= cfg.returnTolerance.stackTemperature_C && ...
    abs(stats.compressorMdot_kg_s) <= cfg.returnTolerance.compressorMdot_kg_s && ...
    abs(stats.compressorTemperature_K) <= cfg.returnTolerance.compressorTemperature_K && ...
    abs(stats.rhCaIn) <= cfg.returnTolerance.rhCaIn && ...
    abs(stats.rhCaOut) <= cfg.returnTolerance.rhCaOut && ...
    abs(stats.waterSeparator) <= cfg.returnTolerance.waterSeparator && ...
    abs(stats.exhaustMdot_kg_s) <= cfg.returnTolerance.exhaustMdot_kg_s && ...
    abs(stats.inletO2MassFraction) <= cfg.returnTolerance.inletO2MassFraction && ...
    abs(stats.inletN2MassFraction) <= cfg.returnTolerance.inletN2MassFraction && ...
    abs(stats.outletO2MoleFraction) <= cfg.returnTolerance.outletO2MoleFraction;
end

function value = signalSpan(signal, window)
mask = signal.Time >= window(1) & signal.Time <= window(2);
data = signal.Data(mask);
data = data(isfinite(data));
if isempty(data)
    value = Inf;
else
    value = max(data) - min(data);
end
end

function timing = transitionTimingStats(ratio, cfg)
timing = struct();
time = ratio.Time(:);
values = ratio.Data(:);
riseMask = time >= cfg.riseCommandTime;
riseTime = time(riseMask);
riseValues = values(riseMask);
rise10 = firstCrossingTime(riseTime, riseValues, ...
    cfg.transitionLowRatio, 'up');
rise90 = firstCrossingTime(riseTime, riseValues, ...
    cfg.transitionHighRatio, 'up');
fallMask = time >= cfg.fallCommandTime;
fallTime = time(fallMask);
fallValues = values(fallMask);
fall90 = firstCrossingTime(fallTime, fallValues, ...
    cfg.transitionHighRatio, 'down');
fall10 = firstCrossingTime(fallTime, fallValues, ...
    cfg.transitionLowRatio, 'down');
timing.rise10ModelTime_s = rise10;
timing.rise90ModelTime_s = rise90;
timing.rise10to90_s = rise90 - rise10;
timing.fall90ModelTime_s = fall90;
timing.fall10ModelTime_s = fall10;
timing.fall90to10_s = fall10 - fall90;
timing.rise10ResearchTime_s = rise10 - cfg.researchStartTime_s;
timing.rise90ResearchTime_s = rise90 - cfg.researchStartTime_s;
timing.fall90ResearchTime_s = fall90 - cfg.researchStartTime_s;
timing.fall10ResearchTime_s = fall10 - cfg.researchStartTime_s;
end

function crossing = firstCrossingTime(time, values, threshold, direction)
if strcmp(direction, 'up')
    idx = find(values >= threshold, 1, 'first');
else
    idx = find(values <= threshold, 1, 'first');
end
if isempty(idx)
    crossing = NaN;
else
    crossing = time(idx);
end
end

function delta = impactDelta(later, earlier)
delta = struct();
names = fieldnames(later);
for idx = 1:numel(names)
    name = names{idx};
    if strcmp(name, 'window_s')
        continue;
    end
    delta.(name) = later.(name) - earlier.(name);
end
end

function values = profileValue(profile, time)
values = interp1(profile(:, 1), profile(:, 2), time, 'previous', 'extrap');
end

function mask = windowMask(signal, window)
mask = signal.Time >= window(1) & signal.Time <= window(2);
end

function signal = loggedTimeseries(logsout, name)
element = logsout.get(name);
if isempty(element) || isempty(element.Values)
    error('RouteA:Stage1MissingLoggedSignal', ...
        'The required logged signal is unavailable: %s.', name);
end
signal = element.Values;
end

function signal = outputTimeseries(out, logsout, logName, outputName)
if datasetHasElement(logsout, logName)
    element = logsout.get(logName);
    if ~isempty(element) && ~isempty(element.Values)
        signal = element.Values;
        return;
    end
end
signal = out.get(outputName);
end

function present = datasetHasElement(dataset, name)
present = false;
try
    names = dataset.getElementNames;
    present = any(strcmp(names, name));
catch
end
end

function lambda = inletOxygenStoich(speciesMdot, stackCurrent)
species = squeeze(speciesMdot.Data).';
if size(species, 1) ~= numel(speciesMdot.Time) || size(species, 2) < 2
    error('RouteA:Stage1SpeciesFlowShape', ...
        'Unexpected cathode inlet species-flow data shape.');
end
current = stackCurrent.Data(:);
currentAtSpeciesTime = interp1(stackCurrent.Time, current, ...
    speciesMdot.Time, 'linear', 'extrap');
o2SupplyMolS = abs(species(:, 2)) / 0.0319988;
o2ConsumptionMolS = 400 * abs(currentAtSpeciesTime) / (4 * 96485.33212);
lambda = timeseries(o2SupplyMolS ./ o2ConsumptionMolS, speciesMdot.Time);
end

function [species, total, massFraction] = inletSpeciesMetrics(speciesMdot)
species = compositionMatrix(speciesMdot, 'routeA_mdot_species_ca_in');
magnitude = abs(species);
total = sum(magnitude, 2);
massFraction = magnitude ./ total;
end

function data = compositionMatrix(signal, signalName)
data = squeeze(signal.Data);
if isvector(data)
    if isscalar(signal.Time)
        data = reshape(data, 1, []);
    else
        data = data(:);
    end
end
if size(data, 1) ~= numel(signal.Time)
    data = data.';
end
if size(data, 1) ~= numel(signal.Time)
    error('RouteA:Stage1CompositionShape', ...
        'Unexpected signal shape for %s.', signalName);
end
end

function rh = waterRelativeHumidity(signal, signalName)
data = compositionMatrix(signal, signalName);
if size(data, 2) < 4
    error('RouteA:Stage1RelativeHumidityShape', ...
        'The water relative-humidity component is unavailable: %s.', ...
        signalName);
end
rh = timeseries(data(:, 4), signal.Time);
end

function massFraction = moleFractionToMassFraction(moleFraction, molarMass)
weighted = moleFraction .* molarMass;
massFraction = weighted ./ sum(weighted, 2);
end

function normalized = normalizeComposition(values)
total = sum(values, 2);
normalized = values ./ total;
end

function moleFraction = externalAirMoleFraction(model)
mw = get_param(model, 'ModelWorkspace');
yO2 = mw.getVariable('env_yO2');
yH2O = mw.getVariable('env_yH20');
moleFraction = [1 - yO2 - yH2O, yO2, 0, yH2O];
end

function values = interpolateMagnitude(signal, time)
values = interp1(signal.Time, abs(signal.Data), time, 'linear', 'extrap');
values = values(:);
end

function observability = gasObservability()
observability = struct( ...
    'cathodeInlet', ...
        'direct: CathodeInletMassFlowSensor_FC M_i, species mass flow', ...
    'cathodeOutlet', ...
        'direct y_i: CathodeOutletChamber yC_i via OutletHumiditySensor', ...
    'cathodeOutletFlow', ...
        'derived: abs(cEGR branch mdot) + abs(exhaust branch mdot)', ...
    'cathodeRecycleFlow', ...
        'direct: EGRMassFlowSensor M', ...
    'cathodeRecycleComposition', ...
        'derived from cathodeOutlet y_i; no branch M_i converter', ...
    'externalAirFlow', ...
        'derived: mixed compressor inlet mdot - recycle mdot', ...
    'externalAirComposition', ...
        'direct boundary: Air Intake y0 in model workspace', ...
    'water', ...
        'phase-sensitive diagnostic; not used as strict N2/O2 gate');
end

function value = tailSpan(values)
values = values(:);
count = max(3, ceil(0.1 * numel(values)));
tail = values(end-count+1:end);
value = max(tail) - min(tail);
end

function count = nonfiniteCount(values)
count = sum(~isfinite(values(:)));
end

function baseline = runZeroTargetBaseline(model, modelFile, modelDir, cfg)
resetModelFromDisk(model, modelFile);
refreshModelWorkspace(model);
routeA_apply_constant_current_step(model, ...
    cfg.initialStateMetadata.targetCurrentA, cfg.targetCurrentA);

in = Simulink.SimulationInput(model);
[in, baselineInitialStateMetadata] = routeA_attach_platform_default_initial_state( ...
    in, model, modelDir, cfg.initialStateFile);
routeA_mark_observability_signals(model);
in = in.setModelParameter( ...
    'StopTime', sprintf('%.16g', cfg.modelStopTime_s), ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SimscapeLogType', 'all');
in = in.setVariable('routeA_air_control_mode_id', 2, 'Workspace', model);
in = in.setVariable('routeA_target_oer', cfg.targetAirEquivalentOer, ...
    'Workspace', model);
in = in.setVariable('routeA_egr_control_mode_id', 1, 'Workspace', model);
in = in.setVariable('routeA_cegr_valve_mode_id', 1, 'Workspace', model);
in = in.setVariable('routeA_target_egr_ratio_comp_in', 0, ...
    'Workspace', model);
in = in.setVariable('routeA_egr_target_input_mode_id', 1, ...
    'Workspace', model);
in = in.setVariable('routeA_target_egr_ratio_comp_in_profile', ...
    [cfg.researchStartTime_s, 0; cfg.modelStopTime_s, 0], ...
    'Workspace', model);

out = sim(in);
cfgBaseline = cfg;
cfgBaseline.profile = [cfg.researchStartTime_s, 0; ...
    cfg.modelStopTime_s, 0];
baseline = collectAudit(out, model, cfgBaseline);
baseline.initialState = baselineInitialStateMetadata;
end

function displayAudit(audit)
fprintf('\nRoute A Stage 1 cEGR target-transition audit\n');
fprintf('  pre  target=%.4g actual=%.6g error=%.6g span=%.6g\n', ...
    audit.windows.pre.targetMean, audit.windows.pre.actualMean, ...
    audit.windows.pre.meanAbsError, audit.windows.pre.tailSpan);
fprintf('  mid  target=%.4g actual=%.6g error=%.6g span=%.6g\n', ...
    audit.windows.mid.targetMean, audit.windows.mid.actualMean, ...
    audit.windows.mid.meanAbsError, audit.windows.mid.tailSpan);
fprintf('  post target=%.4g actual=%.6g error=%.6g span=%.6g\n', ...
    audit.windows.post.targetMean, audit.windows.post.actualMean, ...
    audit.windows.post.meanAbsError, audit.windows.post.tailSpan);
fprintf('  EGR timing rise10-90=%.6g s fall90-10=%.6g s\n', ...
    audit.transitionTiming.rise10to90_s, ...
    audit.transitionTiming.fall90to10_s);
fprintf('  steady pre=%d mid=%d post=%d\n', ...
    audit.steadyState.pre.passed, audit.steadyState.mid.passed, ...
    audit.steadyState.post.passed);
fprintf(['  within-run pre-to-post drift (diagnostic only): dI=%.6g A ', ...
    'dV=%.6g V dT=%.6g C dRHout=%.6g dO2mf=%.6g\n'], ...
    audit.withinRunPreToPost.stackCurrent_A, ...
    audit.withinRunPreToPost.stackVoltage_V, ...
    audit.withinRunPreToPost.stackTemperature_C, ...
    audit.withinRunPreToPost.rhCaOut, ...
    audit.withinRunPreToPost.inletO2MassFraction);
fprintf(['  post vs matched zero-target reference passed=%d ', ...
    'dI=%.6g A dV=%.6g V dT=%.6g C dO2mf=%.6g\n'], ...
    audit.postVsMatchedZeroTargetPassed, ...
    audit.postVsMatchedZeroTarget.stackCurrent_A, ...
    audit.postVsMatchedZeroTarget.stackVoltage_V, ...
    audit.postVsMatchedZeroTarget.stackTemperature_C, ...
    audit.postVsMatchedZeroTarget.inletO2MassFraction);
fprintf(['  targetI=%.6g A trackingErr=%.6g A Pfinal=%.6g kW ', ...
    'lambdaMin=%.6g lambdaOperationalMin=%.6g pDeltaMid=%.6g MPa ', ...
    'areaFrac=[%.6g, %.6g]\n'], ...
    audit.targetCurrentA, audit.currentTrackingMaxErrorA, ...
    audit.actualPowerKW, audit.lambdaCaInMin, audit.lambdaCaInOperationalMin, ...
    audit.pressureDeltaMidMPa, ...
    audit.valveAreaFractionMin, audit.valveAreaFractionMax);
fprintf('  nonfinite counts: %s\n', formatNonfiniteCounts(audit.nonfiniteCounts));
fprintf('  startup-only undefined counts: lambda=%d inletO2MassFraction=%d\n', ...
    audit.lambdaNonfiniteStartupCount, audit.inletO2NonfiniteStartupCount);
displayGasAudit(audit);
displaySystemImpact(audit.systemImpact, audit.systemImpactDeltaMidMinusPre, ...
    audit.systemImpactDeltaMidMinusZeroTarget);
fprintf(['  passed=%d finite=%d EGRtracking=%d pressure=%d area=%d ', ...
    'lambda=%d current=%d matchedReturn=%d\n'], ...
    audit.passed, audit.finiteOk, audit.trackingPassed, ...
    audit.pressurePassed, audit.areaPassed, audit.lambdaPassed, ...
    audit.currentPassed, audit.postVsMatchedZeroTargetPassed);
end

function displayGasAudit(audit)
fprintf('  gas observability: inlet=%s | outlet=%s | recycleFlow=%s\n', ...
    audit.gasObservability.cathodeInlet, ...
    audit.gasObservability.cathodeOutlet, ...
    audit.gasObservability.cathodeRecycleFlow);
fprintf('    recycleComposition=%s\n', ...
    audit.gasObservability.cathodeRecycleComposition);
fprintf('    externalFlow=%s | externalComposition=%s\n', ...
    audit.gasObservability.externalAirFlow, ...
    audit.gasObservability.externalAirComposition);
names = {'pre', 'mid', 'post'};
for idx = 1:numel(names)
    name = names{idx};
    value = audit.systemImpact.(name);
    gas = audit.gasConservation.(name);
    fprintf(['  gas %-4s inlet=%.6g kg/s outlet=%.6g kg/s ', ...
        'recycle=%.6g kg/s fresh=%.6g kg/s\n'], ...
        name, value.cathodeInletTotalMdot_kg_s, ...
        value.cathodeOutletTotalMdot_kg_s, ...
        value.cathodeRecycleMdot_kg_s, value.freshAirMdot_kg_s);
    fprintf('    inlet species=[%s] outlet species=[%s] kg/s\n', ...
        num2str(value.cathodeInletSpeciesMdot_kg_s, ' %.6g'), ...
        num2str(value.cathodeOutletSpeciesMdot_kg_s, ' %.6g'));
    fprintf('    recycle y_i=[%s] external y_i=[%s]\n', ...
        num2str(value.cathodeRecycleYi, ' %.6g'), ...
        num2str(value.externalMoleFraction, ' %.6g'));
    fprintf(['    N2 stackRes=%.6g O2 net=%.6g Faraday=%.6g ', ...
        'O2 residual=%.6g N2/O2 mixRes=[%.6g, %.6g] passed=%d\n'], ...
        gas.n2StackResidual_kg_s, gas.o2NetConsumption_kg_s, ...
        gas.o2FaradayConsumption_kg_s, gas.o2FaradayResidual_kg_s, ...
        gas.n2MixResidual_kg_s, gas.o2MixResidual_kg_s, gas.passed);
end
fprintf('  gas conservation passed=%d (N2/O2 strict; H2O phase-sensitive)\n', ...
    audit.gasConservationPassed);
end

function displaySystemImpact(impact, deltaMidPre, deltaMidZeroTarget)
names = {'pre', 'mid', 'post'};
for idx = 1:numel(names)
    name = names{idx};
    value = impact.(name);
    fprintf(['  impact %-4s I=%.6g A V=%.6g V P=%.6g kW ', ...
        'Tstack=%.6g C comp=%.6g kg/s p=%.6g Pa T=%.6g K ', ...
        'egr=%.6g kg/s fresh~=%.6g kg/s inlet=%.6g kg/s ', ...
        'O2mf=%.6g cmd=%.6g rpm=%.6g\n'], ...
        name, value.stackCurrent_A, value.stackVoltage_V, ...
        value.stackPower_kW, value.stackTemperature_C, ...
        value.compressorMdot_kg_s, value.compressorPressure_Pa, ...
        value.compressorTemperature_K, value.egrMdot_kg_s, ...
        value.freshAirApprox_kg_s, ...
        value.cathodeInletTotalMdot_kg_s, ...
        value.cathodeInletSpeciesMassFraction(2), ...
        value.compressorCommand, value.compressorRpm);
    fprintf('    inlet species mdot=[%s] kg/s mf=[%s] comp y_i=[%s]\n', ...
        num2str(value.cathodeInletSpeciesMdot_kg_s, ' %.6g'), ...
        num2str(value.cathodeInletSpeciesMassFraction, ' %.6g'), ...
        num2str(value.compressorInletYi, ' %.6g'));
    fprintf('    RHin=%.6g RHout=%.6g waterSep=%.6g exhaust=%.6g kg/s\n', ...
        value.rhCaIn, value.rhCaOut, value.waterSeparator, ...
        value.exhaustMdot_kg_s);
end
fprintf(['  impact delta mid-pre: dI=%.6g A dV=%.6g V dP=%.6g kW ', ...
    'dTstack=%.6g C dComp=%.6g kg/s dpComp=%.6g Pa ', ...
    'dTComp=%.6g K dEGR=%.6g kg/s dFresh~=%.6g kg/s ', ...
    'dInlet=%.6g kg/s dO2mf=%.6g dCmd=%.6g dRpm=%.6g\n'], ...
    deltaMidPre.stackCurrent_A, deltaMidPre.stackVoltage_V, ...
    deltaMidPre.stackPower_kW, deltaMidPre.stackTemperature_C, ...
    deltaMidPre.compressorMdot_kg_s, deltaMidPre.compressorPressure_Pa, ...
    deltaMidPre.compressorTemperature_K, deltaMidPre.egrMdot_kg_s, ...
    deltaMidPre.freshAirApprox_kg_s, ...
    deltaMidPre.cathodeInletTotalMdot_kg_s, ...
    deltaMidPre.cathodeInletSpeciesMassFraction(2), ...
    deltaMidPre.compressorCommand, deltaMidPre.compressorRpm);
fprintf(['  impact delta mid-matched-zero-target: dI=%.6g A dV=%.6g V ', ...
    'dP=%.6g kW dTstack=%.6g C dEGR=%.6g kg/s ', ...
    'dFresh~=%.6g kg/s dInlet=%.6g kg/s dO2mf=%.6g\n'], ...
    deltaMidZeroTarget.stackCurrent_A, deltaMidZeroTarget.stackVoltage_V, ...
    deltaMidZeroTarget.stackPower_kW, deltaMidZeroTarget.stackTemperature_C, ...
    deltaMidZeroTarget.egrMdot_kg_s, ...
    deltaMidZeroTarget.freshAirApprox_kg_s, ...
    deltaMidZeroTarget.cathodeInletTotalMdot_kg_s, ...
    deltaMidZeroTarget.cathodeInletSpeciesMassFraction(2));
end

function text = formatNonfiniteCounts(counts)
names = fieldnames(counts);
parts = cell(1, numel(names));
for idx = 1:numel(names)
    parts{idx} = sprintf('%s=%d', names{idx}, counts.(names{idx}));
end
text = strjoin(parts, ', ');
end

function resetModelFromDisk(model, modelFile)
if bdIsLoaded(model)
    close_system(model, 0);
end
load_system(modelFile);
end

function refreshModelWorkspace(model)
mw = get_param(model, 'ModelWorkspace');
if strcmp(mw.DataSource, 'MATLAB File')
    mw.reload;
end
end
