% Route A Stage 1 cathode-cEGR water-management capability audit.
%
% The audit compares only the normal-operation 28 A cases with target cEGR
% ratios of zero and 0.30.  It reports direct Simscape water fluxes and
% storage states separately from L2 observer quantities.  It does not
% claim a liquid-water inventory, drain, or separator-efficiency model.

scriptDir = fileparts(mfilename('fullpath'));
modelDir = fullfile(scriptDir, '..', '..', '01_模型', 'RouteA_GasMixture_Derived');
model = 'PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01';
modelFile = fullfile(modelDir, [model '.slx']);
oldDir = pwd;
addpath(scriptDir);
addpath(modelDir);
cd(modelDir);
routeAWaterCleanup = onCleanup(@() routeA_restore_model_and_folder( ...
    model, modelFile, oldDir));

cfg = waterAuditConfig(modelDir);
cases = runWaterCase(model, modelFile, modelDir, cfg, cfg.targetRatios(1));
for idx = 2:numel(cfg.targetRatios)
    cases(idx) = runWaterCase(model, modelFile, modelDir, cfg, ...
        cfg.targetRatios(idx));
end

audit = summarizeWaterAudit(cases, cfg);
assignin('base', 'routeA_stage1_cathode_water_capability_audit', audit);
displayWaterAudit(audit);
clear routeAWaterCleanup;

function cfg = waterAuditConfig(modelDir)
initialStateFile = fullfile(modelDir, ...
    'RouteA_platform_default_initial_state.mat');
loaded = load(initialStateFile, 'routeA_initial_metadata');
if ~isfield(loaded, 'routeA_initial_metadata')
    error('RouteA:WaterAuditInitialStateMetadata', ...
        'The platform_default initial-state metadata is unavailable.');
end

metadata = loaded.routeA_initial_metadata;
requiredFields = {'snapshotTimeS', 'targetCurrentA', ...
    'currentDensity_A_cm2', 'cegrTopologyEnabled'};
if ~builtin('all', isfield(metadata, requiredFields))
    error('RouteA:WaterAuditInitialStateMetadata', ...
        'The platform_default initial-state metadata is incomplete.');
end
if ~metadata.cegrTopologyEnabled
    error('RouteA:WaterAuditTopology', ...
        'The water audit requires the CEGR-enabled initial topology.');
end

cfg = struct();
cfg.initialStateMetadata = metadata;
cfg.researchStartTime_s = metadata.snapshotTimeS;
cfg.researchDuration_s = 600;
cfg.modelStopTime_s = cfg.researchStartTime_s + cfg.researchDuration_s;
cfg.tailLogicalWindow_s = [540, 600];
cfg.tailWindow_s = cfg.researchStartTime_s + cfg.tailLogicalWindow_s;
cfg.targetCurrentA = metadata.targetCurrentA;
cfg.currentTrackingTolerance_A = 5e-3;
cfg.targetOer = 3;
cfg.targetRatios = [0, 0.30];
cfg.meaClosureTolerance_kg_s = 1e-6;
cfg.localGasBalanceAbsTolerance_kg = 1e-6;
cfg.localGasBalanceRelativeTolerance = 1e-3;
cfg.systemGasBalanceAbsTolerance_kg = 5e-6;
cfg.systemGasBalanceRelativeTolerance = 5e-5;
cfg.species = struct('n2', 1, 'o2', 2, 'h2', 3, 'h2o', 4);
end

function result = runWaterCase(model, modelFile, modelDir, cfg, targetRatio)
resetModelFromDisk(model, modelFile);
refreshModelWorkspace(model);

in = Simulink.SimulationInput(model);
[in, initialStateMetadata] = routeA_attach_platform_default_initial_state( ...
    in, model, modelDir);
routeA_mark_observability_signals(model);
in = in.setModelParameter( ...
    'StopTime', sprintf('%.16g', cfg.modelStopTime_s), ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SimscapeLogType', 'all');
in = in.setVariable('routeA_air_control_mode_id', 2, 'Workspace', model);
in = in.setVariable('routeA_target_oer', cfg.targetOer, 'Workspace', model);
in = in.setVariable('routeA_egr_control_mode_id', 1, 'Workspace', model);
in = in.setVariable('routeA_egr_target_input_mode_id', 0, ...
    'Workspace', model);
in = in.setVariable('routeA_target_egr_ratio_comp_in', targetRatio, ...
    'Workspace', model);
in = in.setVariable('routeA_target_egr_ratio_comp_in_profile', ...
    [cfg.researchStartTime_s, targetRatio; ...
    cfg.modelStopTime_s, targetRatio], 'Workspace', model);

out = sim(in);
result = collectWaterCase(out, model, cfg, targetRatio);
result.initialState = initialStateMetadata;
clear out;
end

function result = collectWaterCase(out, model, cfg, targetRatio)
logsout = out.logsout;
egrRatio = loggedTimeseries(logsout, 'routeA_egr_ratio_comp_in');
stackCurrent = loggedTimeseries(logsout, 'routeA_stack_current_A');
waterSepL2 = outputTimeseries(out, logsout, 'routeA_m_water_sep', ...
    'routeA_m_water_sep_ts');

simlog = out.get(get_param(model, 'SimscapeLogName'));
paths = routeA_block_paths(model);
mea = simscape.logging.findNode(simlog, ...
    [paths.stack '/Membrane Electrode Assembly']);
mixer = simscape.logging.findNode(simlog, ...
    [paths.oxygen '/CompressorInletMixer']);
outlet = simscape.logging.findNode(simlog, paths.outletChamber);
compressorVolume = simscape.logging.findNode(simlog, ...
    [paths.oxygen '/Compressor Volume']);
humidifierPipe = simscape.logging.findNode(simlog, ...
    [paths.cathodeHumidifier '/Pipe (FC)']);
cathodeGas = simscape.logging.findNode(simlog, ...
    [paths.cathodeGas '/Cathode']);
egrPipe = simscape.logging.findNode(simlog, paths.egrPipe);
exhaustPipe = simscape.logging.findNode(simlog, ...
    [paths.cathodeExhaustBlock '/Pipe (N Gas)1']);
egrSensor = simscape.logging.findNode(simlog, paths.egrMassFlowSensor);
exhaustSensor = simscape.logging.findNode(simlog, paths.exhaustMassFlowSensor);
preHumidifierSensor = simscape.logging.findNode(simlog, ...
    paths.oxygenMassFlowSensor);
humidifierGain = simscape.logging.findNode(simlog, ...
    [paths.cathodeHumidifier '/PS Gain1']);

meaWaterProduced = logSeries(mea, 'H2O_produced', 'kg/s', ...
    'MEA H2O_produced');
meaMdotCa = logSeries(mea, 'mdot_ca', 'kg/s', 'MEA mdot_ca');
meaMdotAn = logSeries(mea, 'mdot_an', 'kg/s', 'MEA mdot_an');
mixerPorts = struct( ...
    'A', logSeries(mixer, 'mdot_A_i', 'kg/s', 'CompressorInletMixer mdot_A_i'), ...
    'B', logSeries(mixer, 'mdot_B_i', 'kg/s', 'CompressorInletMixer mdot_B_i'), ...
    'C', logSeries(mixer, 'mdot_C_i', 'kg/s', 'CompressorInletMixer mdot_C_i'));
mixerCond = logSeries(mixer, 'mdot_cond', 'kg/s', ...
    'CompressorInletMixer mdot_cond');
mixerInventory = logSeries(mixer, 'm_I_i', 'kg', ...
    'CompressorInletMixer m_I_i');
compressorVolumeCond = logSeries(compressorVolume, 'mdot_cond', 'kg/s', ...
    'Compressor Volume mdot_cond');
compressorVolumeInventory = logSeries(compressorVolume, 'm_I_i', 'kg', ...
    'Compressor Volume m_I_i');
humidifierPipeInventory = logSeries(humidifierPipe, 'm_I_i', 'kg', ...
    'Cathode Humidifier Pipe m_I_i');
humidifierPipeCond = logSeries(humidifierPipe, 'mdot_c', 'kg/s', ...
    'Cathode Humidifier Pipe mdot_c');
cathodeGasCond = logSeries(cathodeGas, 'mdot_cond', 'kg/s', ...
    'Cathode Gas Channels mdot_cond');
cathodeGasInventory = logSeries(cathodeGas, 'm_I_i', 'kg', ...
    'Cathode Gas Channels m_I_i');
egrPipeInventory = logSeries(egrPipe, 'm_I_i', 'kg', 'EGR Pipe m_I_i');
egrPipeCond = logSeries(egrPipe, 'mdot_c', 'kg/s', 'EGR Pipe mdot_c');
exhaustPipeInventory = logSeries(exhaustPipe, 'm_I_i', 'kg', ...
    'Cathode Exhaust Pipe m_I_i');
exhaustPipeCond = logSeries(exhaustPipe, 'mdot_c', 'kg/s', ...
    'Cathode Exhaust Pipe mdot_c');
exhaustPipeOutSpecies = logSeries(exhaustPipe, 'mdot_B_i', 'kg/s', ...
    'Cathode Exhaust Pipe mdot_B_i');
outletPorts = struct( ...
    'A', logSeries(outlet, 'mdot_A_i', 'kg/s', 'CathodeOutletChamber mdot_A_i'), ...
    'B', logSeries(outlet, 'mdot_B_i', 'kg/s', 'CathodeOutletChamber mdot_B_i'), ...
    'C', logSeries(outlet, 'mdot_C_i', 'kg/s', 'CathodeOutletChamber mdot_C_i'));
outletCond = logSeries(outlet, 'mdot_cond', 'kg/s', ...
    'CathodeOutletChamber mdot_cond');
outletInventory = logSeries(outlet, 'm_I_i', 'kg', ...
    'CathodeOutletChamber m_I_i');
egrMdot = logSeries(egrSensor, 'M', 'kg/s', 'EGRMassFlowSensor M');
egrSpecies = logSeries(egrSensor, 'M_i', 'kg/s', 'EGRMassFlowSensor M_i');
exhaustMdot = logSeries(exhaustSensor, 'M', 'kg/s', ...
    'ExhaustMassFlowSensor M');
exhaustSpecies = logSeries(exhaustSensor, 'M_i', 'kg/s', ...
    'ExhaustMassFlowSensor M_i');
preHumidifierMdot = logSeries(preHumidifierSensor, 'M', 'kg/s', ...
    'Prehumidifier M');
preHumidifierSpecies = logSeries(preHumidifierSensor, 'M_i', 'kg/s', ...
    'Prehumidifier M_i');
humidifierMIn = logSeries(humidifierGain, 'O', 'kg/s', ...
    'Cathode humidifier MIn');

tail = struct();
tail.actualEgrRatio = scalarStats(egrRatio.Time, egrRatio.Data, ...
    cfg.tailWindow_s);
tail.stackCurrent_A = scalarStats(stackCurrent.Time, stackCurrent.Data, ...
    cfg.tailWindow_s);
tail.meaH2OProduced_kg_s = scalarStats(meaWaterProduced.time, ...
    meaWaterProduced.data, cfg.tailWindow_s);
tail.meaMdotCaSpecies_kg_s = vectorStats(meaMdotCa.time, meaMdotCa.data, ...
    cfg.tailWindow_s);
tail.meaMdotAnSpecies_kg_s = vectorStats(meaMdotAn.time, meaMdotAn.data, ...
    cfg.tailWindow_s);
tail.mixerPortSpecies_kg_s = struct( ...
    'A', vectorStats(mixerPorts.A.time, mixerPorts.A.data, cfg.tailWindow_s), ...
    'B', vectorStats(mixerPorts.B.time, mixerPorts.B.data, cfg.tailWindow_s), ...
    'C', vectorStats(mixerPorts.C.time, mixerPorts.C.data, cfg.tailWindow_s));
tail.mixerCondSpecies_kg_s = vectorStats(mixerCond.time, mixerCond.data, ...
    cfg.tailWindow_s);
tail.mixerInventorySpecies_kg = vectorStats(mixerInventory.time, ...
    mixerInventory.data, cfg.tailWindow_s);
tail.mixerInventoryRateSpecies_kg_s = inventoryRate(mixerInventory.time, ...
    mixerInventory.data, cfg.tailWindow_s);
tail.outletPortSpecies_kg_s = struct( ...
    'A', vectorStats(outletPorts.A.time, outletPorts.A.data, cfg.tailWindow_s), ...
    'B', vectorStats(outletPorts.B.time, outletPorts.B.data, cfg.tailWindow_s), ...
    'C', vectorStats(outletPorts.C.time, outletPorts.C.data, cfg.tailWindow_s));
tail.outletCondSpecies_kg_s = vectorStats(outletCond.time, outletCond.data, ...
    cfg.tailWindow_s);
tail.outletInventorySpecies_kg = vectorStats(outletInventory.time, ...
    outletInventory.data, cfg.tailWindow_s);
tail.outletInventoryRateSpecies_kg_s = inventoryRate(outletInventory.time, ...
    outletInventory.data, cfg.tailWindow_s);
tail.humidifierPipeCondSpecies_kg_s = vectorStats(humidifierPipeCond.time, ...
    humidifierPipeCond.data, cfg.tailWindow_s);
tail.cathodeGasCondSpecies_kg_s = vectorStats(cathodeGasCond.time, ...
    cathodeGasCond.data, cfg.tailWindow_s);
tail.egrPipeCondSpecies_kg_s = vectorStats(egrPipeCond.time, ...
    egrPipeCond.data, cfg.tailWindow_s);
tail.exhaustPipeCondSpecies_kg_s = vectorStats(exhaustPipeCond.time, ...
    exhaustPipeCond.data, cfg.tailWindow_s);
tail.finalExhaustSpecies_kg_s = vectorStats(exhaustPipeOutSpecies.time, ...
    exhaustPipeOutSpecies.data, cfg.tailWindow_s);
tail.egrMdot_kg_s = scalarStats(egrMdot.time, egrMdot.data, cfg.tailWindow_s);
tail.egrSpecies_kg_s = vectorStats(egrSpecies.time, egrSpecies.data, ...
    cfg.tailWindow_s);
tail.exhaustMdot_kg_s = scalarStats(exhaustMdot.time, exhaustMdot.data, ...
    cfg.tailWindow_s);
tail.exhaustSpecies_kg_s = vectorStats(exhaustSpecies.time, ...
    exhaustSpecies.data, cfg.tailWindow_s);
tail.preHumidifierMdot_kg_s = scalarStats(preHumidifierMdot.time, ...
    preHumidifierMdot.data, cfg.tailWindow_s);
tail.preHumidifierSpecies_kg_s = vectorStats(preHumidifierSpecies.time, ...
    preHumidifierSpecies.data, cfg.tailWindow_s);
tail.humidifierMInSpecies_kg_s = vectorStats(humidifierMIn.time, ...
    humidifierMIn.data, cfg.tailWindow_s);
tail.waterSepL2Raw = scalarStats(waterSepL2.Time, waterSepL2.Data, ...
    cfg.tailWindow_s);

h2o = cfg.species.h2o;
meaClosure = tail.meaH2OProduced_kg_s.mean - ...
    tail.meaMdotCaSpecies_kg_s.mean(h2o) - ...
    tail.meaMdotAnSpecies_kg_s.mean(h2o);
mixerGasPhaseBalance = localGasPhaseBalance(mixerPorts, mixerCond, ...
    mixerInventory, h2o, [cfg.researchStartTime_s, cfg.modelStopTime_s], ...
    cfg, 'CompressorInletMixer');
outletGasPhaseBalance = localGasPhaseBalance(outletPorts, outletCond, ...
    outletInventory, h2o, [cfg.researchStartTime_s, cfg.modelStopTime_s], ...
    cfg, 'CathodeOutletChamber');
systemGasPhaseBalance = cathodeSystemGasPhaseBalance( ...
    mixerPorts.A, humidifierMIn, meaMdotCa, exhaustPipeOutSpecies, ...
    [mixerCond, compressorVolumeCond, humidifierPipeCond, cathodeGasCond, ...
    outletCond, egrPipeCond, exhaustPipeCond], ...
    [mixerInventory, compressorVolumeInventory, humidifierPipeInventory, ...
    cathodeGasInventory, outletInventory, egrPipeInventory, ...
    exhaustPipeInventory], h2o, ...
    [cfg.researchStartTime_s, cfg.modelStopTime_s], cfg);
saturation = struct( ...
    'mixer', saturationRatioStats(mixer, cfg, 'CompressorInletMixer'), ...
    'compressorVolume', saturationRatioStats(compressorVolume, cfg, ...
        'Compressor Volume'), ...
    'humidifierPipe', saturationRatioStats(humidifierPipe, cfg, ...
        'Cathode Humidifier Pipe'), ...
    'cathodeGas', saturationRatioStats(cathodeGas, cfg, ...
        'Cathode Gas Channels'), ...
    'outletChamber', saturationRatioStats(outlet, cfg, ...
        'CathodeOutletChamber'), ...
    'egrPipe', saturationRatioStats(egrPipe, cfg, 'EGR Pipe'), ...
    'exhaustPipe', saturationRatioStats(exhaustPipe, cfg, ...
        'Cathode Exhaust Pipe'));
currentData = windowData(stackCurrent.Time, stackCurrent.Data, ...
    [cfg.researchStartTime_s, cfg.modelStopTime_s]);
currentTrackingError = max(abs(currentData - cfg.targetCurrentA));

result = struct();
result.targetRatio = targetRatio;
result.researchStartModelTime_s = cfg.researchStartTime_s;
result.researchDuration_s = cfg.researchDuration_s;
result.tailLogicalWindow_s = cfg.tailLogicalWindow_s;
result.tailModelWindow_s = cfg.tailWindow_s;
result.tail = tail;
result.meaWaterClosure_kg_s = meaClosure;
result.meaWaterClosurePassed = abs(meaClosure) <= ...
    cfg.meaClosureTolerance_kg_s;
% In the official MEA element, mdot_an(H2O) equals -mdot_w.  Positive
% mdot_w denotes anode-to-cathode transport, so this signed quantity is
% positive for anode-to-cathode and negative for cathode-to-anode transfer.
result.netMembraneWaterAnodeToCathode_kg_s = ...
    -tail.meaMdotAnSpecies_kg_s.mean(h2o);
result.mixerGasPhaseBalance = mixerGasPhaseBalance;
result.outletGasPhaseBalance = outletGasPhaseBalance;
result.localGasPhaseBalancePassed = mixerGasPhaseBalance.passed && ...
    outletGasPhaseBalance.passed;
result.systemGasPhaseBalance = systemGasPhaseBalance;
result.systemGasPhaseBalancePassed = systemGasPhaseBalance.passed;
result.saturation = saturation;
result.currentTrackingMaxError_A = currentTrackingError;
result.currentPassed = currentTrackingError <= cfg.currentTrackingTolerance_A;
result.finite = tailFinite(tail);
result.evidencePassed = result.finite && result.currentPassed && ...
    result.meaWaterClosurePassed && result.localGasPhaseBalancePassed && ...
    result.systemGasPhaseBalancePassed;
end

function audit = summarizeWaterAudit(cases, cfg)
audit = struct();
audit.timestamp = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
audit.model = string(cfg.initialStateMetadata.model);
audit.initialState = cfg.initialStateMetadata;
audit.targetRatios = cfg.targetRatios;
audit.researchDuration_s = cfg.researchDuration_s;
audit.tailLogicalWindow_s = cfg.tailLogicalWindow_s;
audit.scope = 'cathode-cEGR water side only';
audit.cases = cases;
audit.observability = observabilityMap();
audit.localGasPhaseClosurePassed = ...
    builtin('all', [cases.localGasPhaseBalancePassed]);
audit.systemGasPhaseClosurePassed = ...
    builtin('all', [cases.systemGasPhaseBalancePassed]);
audit.gasVaporAndPhaseFluxEvidencePassed = ...
    builtin('all', [cases.evidencePassed]);
audit.liquidWaterInventoryClosed = false;
audit.liquidWaterTransportClosed = false;
audit.liquidDrainClosed = false;
audit.separatorEfficiencyClosed = false;
audit.fullWaterBalanceClosed = false;
audit.liquidGapReason = [ ...
    "No explicit liquid-water port, liquid transport branch, drain flow, ", ...
    "or separator efficiency model is currently exposed by the cathode-cEGR ", ...
    "physical network. Enabled Constant Volume Chamber (FC) blocks remove ", ...
    "condensed species from the gas chamber immediately; m_I_i is the ", ...
    "remaining gas-species inventory, not a liquid-water inventory."];
audit.auditPassed = audit.gasVaporAndPhaseFluxEvidencePassed;
end

function observability = observabilityMap()
observability = struct( ...
    'externalAirWater', ...
        'direct: fresh-air branch at CompressorInletMixer port-A species flow', ...
    'cathodeHumidifierWaterInput', ...
        'direct gas-phase source: Pipe (FC) MIn water component; external liquid or vapor mechanism is L2', ...
    'reactionWater', ...
        'direct: MEA H2O_produced', ...
    'meaCathodeAndAnodeWaterFlux', ...
        'direct: MEA mdot_ca and mdot_an species flows', ...
    'membraneWaterPartition', ...
        'derived: -MEA mdot_an(H2O), positive for anode-to-cathode; drag and diffusion are not split', ...
    'cathodeInletAndOutletVapor', ...
        'direct: prehumidifier, EGR, and exhaust Mass Flow Rate Sensor M_i', ...
    'condensationFlux', ...
        'direct gas-phase sink: Chamber mdot_cond and Pipe mdot_c across all gas volumes', ...
    'chamberComponentInventory', ...
        'direct gas-species chamber inventory: m_I_i; condensed water is not stored', ...
    'cathodeSystemGasInventory', ...
        'derived direct: sum m_I_i across seven cathode-cEGR gas volumes', ...
    'saturationRatio', ...
        'derived direct: water partial pressure divided by saturation pressure at each gas volume', ...
    'liquidInventory', ...
        'unobservable: no explicit liquid state is exposed; condensation is immediately removed', ...
    'liquidTransportAndDrain', ...
        'unobservable: no liquid port or drain branch exists', ...
    'separatorObserver', ...
        'L2 only: saturation-excess KPI; not a physical separator mass flow', ...
    'separatorEfficiency', ...
        'unobservable: no component performance evidence');
end

function displayWaterAudit(audit)
fprintf('\nRoute A Stage 1 cathode-cEGR water capability audit\n');
fprintf('  initial phase: %s | t0=%.6f s | I=%.6g A | tail=[%.0f,%.0f) s\n', ...
    audit.initialState.normalOperationPhase, ...
    audit.initialState.snapshotTimeS, ...
    audit.initialState.targetCurrentA, ...
    audit.tailLogicalWindow_s(1), audit.tailLogicalWindow_s(2));
for idx = 1:numel(audit.cases)
    value = audit.cases(idx);
    h2o = 4;
    fprintf('\n  target=%.2f actual=%.9g evidencePassed=%d\n', ...
        value.targetRatio, value.tail.actualEgrRatio.mean, ...
        value.evidencePassed);
    fprintf(['    MEA H2O: produced=%.9g kg/s cathode=%.9g anode=%.9g ', ...
        'closure=%.3g kg/s net-membrane(AtoC)=%.9g kg/s\n'], ...
        value.tail.meaH2OProduced_kg_s.mean, ...
        value.tail.meaMdotCaSpecies_kg_s.mean(h2o), ...
        value.tail.meaMdotAnSpecies_kg_s.mean(h2o), ...
        value.meaWaterClosure_kg_s, ...
        value.netMembraneWaterAnodeToCathode_kg_s);
    fprintf(['    mixer H2O ports[A B C]=[%s] cond=%.9g kg/s ', ...
        'full-window gas residual=%.3g kg\n'], ...
        num2str([value.tail.mixerPortSpecies_kg_s.A.mean(h2o), ...
        value.tail.mixerPortSpecies_kg_s.B.mean(h2o), ...
        value.tail.mixerPortSpecies_kg_s.C.mean(h2o)], ' %.9g'), ...
        value.tail.mixerCondSpecies_kg_s.mean(h2o), ...
        value.mixerGasPhaseBalance.residual_kg);
    fprintf(['    outlet H2O ports[A B C]=[%s] cond=%.9g kg/s ', ...
        'full-window gas residual=%.3g kg\n'], ...
        num2str([value.tail.outletPortSpecies_kg_s.A.mean(h2o), ...
        value.tail.outletPortSpecies_kg_s.B.mean(h2o), ...
        value.tail.outletPortSpecies_kg_s.C.mean(h2o)], ' %.9g'), ...
        value.tail.outletCondSpecies_kg_s.mean(h2o), ...
        value.outletGasPhaseBalance.residual_kg);
    fprintf(['    branch H2O: egr=%.9g pre-exhaust=%.9g final-exhaust=%.9g ', ...
        'preHum=%.9g humidifier-gas-source=%.9g kg/s L2observer=%.9g\n'], ...
        value.tail.egrSpecies_kg_s.mean(h2o), ...
        value.tail.exhaustSpecies_kg_s.mean(h2o), ...
        -value.tail.finalExhaustSpecies_kg_s.mean(h2o), ...
        value.tail.preHumidifierSpecies_kg_s.mean(h2o), ...
        value.tail.humidifierMInSpecies_kg_s.mean(h2o), ...
        value.tail.waterSepL2Raw.mean);
    fprintf(['    tail condensation H2O: humidifier-pipe=%.9g cathode-gas=%.9g ', ...
        'EGR-pipe=%.9g exhaust-pipe=%.9g kg/s\n'], ...
        value.tail.humidifierPipeCondSpecies_kg_s.mean(h2o), ...
        value.tail.cathodeGasCondSpecies_kg_s.mean(h2o), ...
        value.tail.egrPipeCondSpecies_kg_s.mean(h2o), ...
        value.tail.exhaustPipeCondSpecies_kg_s.mean(h2o));
    fprintf(['    saturation ratio max-full/tail-mean: mixer=%.6g/%.6g ', ...
        'comp=%.6g/%.6g humid=%.6g/%.6g cathode=%.6g/%.6g ', ...
        'outlet=%.6g/%.6g egr=%.6g/%.6g exhaust=%.6g/%.6g\n'], ...
        value.saturation.mixer.fullMaximum, value.saturation.mixer.tailMean, ...
        value.saturation.compressorVolume.fullMaximum, ...
        value.saturation.compressorVolume.tailMean, ...
        value.saturation.humidifierPipe.fullMaximum, ...
        value.saturation.humidifierPipe.tailMean, ...
        value.saturation.cathodeGas.fullMaximum, ...
        value.saturation.cathodeGas.tailMean, ...
        value.saturation.outletChamber.fullMaximum, ...
        value.saturation.outletChamber.tailMean, ...
        value.saturation.egrPipe.fullMaximum, value.saturation.egrPipe.tailMean, ...
        value.saturation.exhaustPipe.fullMaximum, ...
        value.saturation.exhaustPipe.tailMean);
    fprintf(['    system H2O full-window: fresh=%.9g humidifier=%.9g ', ...
        'MEA=%.9g exhaust=%.9g cond=%.9g delta-gas=%.9g residual=%.3g kg\n'], ...
        value.systemGasPhaseBalance.integratedFreshAir_kg, ...
        value.systemGasPhaseBalance.integratedHumidifier_kg, ...
        value.systemGasPhaseBalance.integratedMeaCathode_kg, ...
        value.systemGasPhaseBalance.integratedExhaust_kg, ...
        value.systemGasPhaseBalance.integratedCondensation_kg, ...
        value.systemGasPhaseBalance.deltaGasInventory_kg, ...
        value.systemGasPhaseBalance.residual_kg);
end
fprintf('\n  gas-vapor and phase-flux evidence passed=%d\n', ...
    audit.gasVaporAndPhaseFluxEvidencePassed);
fprintf('  liquid inventory/transport/drain/efficiency closed=[%d %d %d %d]\n', ...
    audit.liquidWaterInventoryClosed, audit.liquidWaterTransportClosed, ...
    audit.liquidDrainClosed, audit.separatorEfficiencyClosed);
end

function signal = logSeries(node, propertyName, unit, label)
if ~isprop(node, propertyName)
    error('RouteA:WaterAuditMissingSimscapeQuantity', ...
        'The required Simscape quantity is unavailable: %s.', label);
end
series = node.(propertyName).series;
signal = struct();
signal.time = series.time;
signal.time = signal.time(:);
signal.data = normalizeSeriesData(series.values(unit), signal.time, label);
end

function data = normalizeSeriesData(data, time, label)
data = squeeze(data);
if isvector(data)
    data = data(:);
end
if size(data, 1) ~= numel(time)
    data = data.';
end
if size(data, 1) ~= numel(time)
    error('RouteA:WaterAuditSeriesShape', ...
        'Unexpected Simscape data shape for %s.', label);
end
end

function signal = loggedTimeseries(logsout, name)
element = logsout.get(name);
if isempty(element) || isempty(element.Values)
    error('RouteA:WaterAuditMissingLoggedSignal', ...
        'The required logged signal is unavailable: %s.', name);
end
signal = element.Values;
end

function signal = outputTimeseries(out, logsout, logName, outputName)
if datasetHasElement(logsout, logName)
    element = logsout.get(logName);
    if ~isempty(element) && ~isempty(element.Values)
        signal = element.Values;
        return;
    end
end
signal = out.get(outputName);
end

function present = datasetHasElement(dataset, name)
names = dataset.getElementNames;
present = any(strcmp(names, name));
end

function stats = scalarStats(time, data, window)
values = windowData(time, data, window);
values = values(:);
stats = struct();
stats.start_s = window(1);
stats.end_s = window(2);
stats.sampleCount = numel(values);
stats.nonfiniteCount = sum(~isfinite(values));
finiteValues = values(isfinite(values));
if isempty(finiteValues)
    stats.mean = NaN;
    stats.std = NaN;
    stats.span = Inf;
    stats.minimum = NaN;
    stats.maximum = NaN;
    return;
end
stats.mean = mean(finiteValues);
stats.std = std(finiteValues);
stats.span = max(finiteValues) - min(finiteValues);
stats.minimum = min(finiteValues);
stats.maximum = max(finiteValues);
end

function stats = vectorStats(time, data, window)
values = windowData(time, data, window);
stats = struct();
stats.start_s = window(1);
stats.end_s = window(2);
stats.sampleCount = size(values, 1);
stats.nonfiniteCount = sum(~isfinite(values), 1);
stats.mean = mean(values, 1);
stats.std = std(values, 0, 1);
stats.span = max(values, [], 1) - min(values, [], 1);
stats.minimum = min(values, [], 1);
stats.maximum = max(values, [], 1);
end

function rate = inventoryRate(time, data, window)
mask = time >= window(1) & time < window(2);
time = time(mask);
data = data(mask, :);
if numel(time) < 2 || time(end) <= time(1)
    rate = NaN(1, size(data, 2));
    return;
end
rate = (data(end, :) - data(1, :)) / (time(end) - time(1));
end

function balance = localGasPhaseBalance(ports, condensate, inventory, ...
    speciesIndex, window, cfg, label)
time = inventory.time;
mask = time >= window(1) & time <= window(2);
time = time(mask);
inventoryData = inventory.data(mask, speciesIndex);
balance = struct();
balance.label = label;
balance.window_s = window;
balance.sampleCount = numel(time);
if numel(time) < 2 || time(end) <= time(1)
    balance.integratedPortAndCondensation_kg = NaN;
    balance.deltaGasInventory_kg = NaN;
    balance.residual_kg = NaN;
    balance.tolerance_kg = NaN;
    balance.passed = false;
    return;
end

portA = resampleSpecies(ports.A, time, speciesIndex, label);
portB = resampleSpecies(ports.B, time, speciesIndex, label);
portC = resampleSpecies(ports.C, time, speciesIndex, label);
condRate = resampleSpecies(condensate, time, speciesIndex, label);
netGasRate = portA + portB + portC - condRate;
integratedNet = trapz(time, netGasRate);
deltaInventory = inventoryData(end) - inventoryData(1);
residual = integratedNet - deltaInventory;
throughput = trapz(time, abs(portA) + abs(portB) + abs(portC) + abs(condRate));
tolerance = cfg.localGasBalanceAbsTolerance_kg + ...
    cfg.localGasBalanceRelativeTolerance * max(throughput, 1e-12);
balance.integratedPortAndCondensation_kg = integratedNet;
balance.deltaGasInventory_kg = deltaInventory;
balance.residual_kg = residual;
balance.tolerance_kg = tolerance;
balance.passed = isfinite(residual) && abs(residual) <= tolerance;
end

function balance = cathodeSystemGasPhaseBalance(freshAir, humidifier, ...
    meaCathode, exhaustPortB, condensateSignals, inventorySignals, speciesIndex, ...
    window, cfg)
time = inventorySignals(1).time;
mask = time >= window(1) & time <= window(2);
time = time(mask);
balance = struct();
balance.window_s = window;
balance.sampleCount = numel(time);
if numel(time) < 2 || time(end) <= time(1)
    balance.integratedFreshAir_kg = NaN;
    balance.integratedHumidifier_kg = NaN;
    balance.integratedMeaCathode_kg = NaN;
    balance.integratedExhaust_kg = NaN;
    balance.integratedCondensation_kg = NaN;
    balance.deltaGasInventory_kg = NaN;
    balance.residual_kg = NaN;
    balance.tolerance_kg = NaN;
    balance.passed = false;
    return;
end

freshRate = resampleSpecies(freshAir, time, speciesIndex, 'fresh-air water');
humidifierRate = resampleSpecies(humidifier, time, speciesIndex, ...
    'humidifier water source');
meaRate = resampleSpecies(meaCathode, time, speciesIndex, ...
    'MEA cathode water source');
exhaustRate = -resampleSpecies(exhaustPortB, time, speciesIndex, ...
    'final exhaust water flow');
condensationRate = zeros(size(time));
for idx = 1:numel(condensateSignals)
    condensationRate = condensationRate + resampleSpecies( ...
        condensateSignals(idx), time, speciesIndex, 'condensation flow');
end
gasInventory = zeros(size(time));
for idx = 1:numel(inventorySignals)
    gasInventory = gasInventory + resampleSpecies( ...
        inventorySignals(idx), time, speciesIndex, 'gas water inventory');
end

integratedFreshAir = trapz(time, freshRate);
integratedHumidifier = trapz(time, humidifierRate);
integratedMeaCathode = trapz(time, meaRate);
integratedExhaust = trapz(time, exhaustRate);
integratedCondensation = trapz(time, condensationRate);
deltaGasInventory = gasInventory(end) - gasInventory(1);
integratedNet = integratedFreshAir + integratedHumidifier + ...
    integratedMeaCathode - integratedExhaust - integratedCondensation;
residual = integratedNet - deltaGasInventory;
throughput = trapz(time, abs(freshRate) + abs(humidifierRate) + ...
    abs(meaRate) + abs(exhaustRate) + abs(condensationRate));
tolerance = cfg.systemGasBalanceAbsTolerance_kg + ...
    cfg.systemGasBalanceRelativeTolerance * max(throughput, 1e-12);
balance.integratedFreshAir_kg = integratedFreshAir;
balance.integratedHumidifier_kg = integratedHumidifier;
balance.integratedMeaCathode_kg = integratedMeaCathode;
balance.integratedExhaust_kg = integratedExhaust;
balance.integratedCondensation_kg = integratedCondensation;
balance.deltaGasInventory_kg = deltaGasInventory;
balance.integratedNet_kg = integratedNet;
balance.residual_kg = residual;
balance.tolerance_kg = tolerance;
balance.passed = isfinite(residual) && abs(residual) <= tolerance;
end

function stats = saturationRatioStats(node, cfg, label)
pressure = logSeries(node, 'p_I', 'Pa', [label ' p_I']);
temperature = logSeries(node, 'T_I', 'K', [label ' T_I']);
moleFraction = logSeries(node, 'y_I_i', '1', [label ' y_I_i']);
time = pressure.time;
p = resampleSpecies(pressure, time, 1, label);
T = resampleSpecies(temperature, time, 1, label);
yH2O = resampleSpecies(moleFraction, time, cfg.species.h2o, label);
temperatureC = T - 273.15;
pSatPa = 611.21 .* exp((18.678 - temperatureC ./ 234.5) .* ...
    (temperatureC ./ (257.14 + temperatureC)));
ratio = yH2O .* p ./ pSatPa;
fullMask = time >= cfg.researchStartTime_s & time <= cfg.modelStopTime_s;
tailMask = time >= cfg.tailWindow_s(1) & time < cfg.tailWindow_s(2);
if ~any(fullMask) || ~any(tailMask) || any(~isfinite(ratio))
    error('RouteA:WaterAuditSaturation', ...
        'Could not evaluate water saturation ratio for %s.', label);
end
stats = struct();
stats.fullMaximum = max(ratio(fullMask));
stats.tailMaximum = max(ratio(tailMask));
stats.tailMean = mean(ratio(tailMask));
stats.tailMinimum = min(ratio(tailMask));
end

function values = resampleSpecies(signal, targetTime, speciesIndex, label)
if size(signal.data, 2) < speciesIndex
    error('RouteA:WaterAuditMissingSpecies', ...
        'Water species is unavailable in %s.', label);
end
sourceTime = signal.time;
sourceData = signal.data(:, speciesIndex);
if numel(sourceTime) == numel(targetTime) && isequal(sourceTime, targetTime)
    values = sourceData;
    return;
end
values = interp1(sourceTime, sourceData, targetTime, 'linear');
if any(~isfinite(values))
    error('RouteA:WaterAuditResample', ...
        'Could not align the water flow time base for %s.', label);
end
end

function values = windowData(time, data, window)
mask = time >= window(1) & time < window(2);
values = data(mask, :);
if isempty(values)
    error('RouteA:WaterAuditEmptyWindow', ...
        'No samples were found in the requested statistics window.');
end
end

function passed = tailFinite(tail)
h2o = 4;
checks = [ ...
    tail.actualEgrRatio.nonfiniteCount == 0; ...
    tail.stackCurrent_A.nonfiniteCount == 0; ...
    tail.meaH2OProduced_kg_s.nonfiniteCount == 0; ...
    tail.meaMdotCaSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.meaMdotAnSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.mixerCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.outletCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.humidifierPipeCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.cathodeGasCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.egrPipeCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.exhaustPipeCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.finalExhaustSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.egrSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.exhaustSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.preHumidifierSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.humidifierMInSpecies_kg_s.nonfiniteCount(h2o) == 0];
passed = builtin('all', checks);
end

function resetModelFromDisk(model, modelFile)
if bdIsLoaded(model)
    close_system(model, 0);
end
load_system(modelFile);
end

function refreshModelWorkspace(model)
mw = get_param(model, 'ModelWorkspace');
if strcmp(mw.DataSource, 'MATLAB File')
    mw.reload;
end
end
